src/menu/head-menu.tsx, src/menu/menu-group.tsx, src/menu/menu-item.tsx, src/menu/menu.tsx, src/menu/submenu.tsx, test/ssr/__snapshots__/ssr.test.js.snap, test/unit/menu/__snapshots__/demo.test.js.snap, test/unit/menu/__snapshots__/head-menu.test.js.snap, test/unit/menu/__snapshots__/menu-item.test.js.snap, test/unit/menu/__snapshots__/menu.test.js.snap
=> refactor(menu): correct classname

.husky/commit-msg, .husky/pre-commit, examples/anchor/demos/base.vue, package.json, src/cascader/cascader.tsx, src/cascader/components/Item.tsx, src/cascader/components/Panel.tsx, src/cascader/interface.tsx, test/ssr/__snapshots__/ssr.test.js.snap, test/unit/anchor/__snapshots__/demo.test.js.snap
- anchor demo update
- @commitlint and husky upgrade
- cascader code optimize
=> chore: cascader codeoptimize and husky upgrade

src/popup/popup.tsx
=> popup class问题

src/pagination/pagination.tsx
=> fix(pagination): fix pagination jump

examples/config-provider/demos/pagination.vue, src/layout/aside.tsx, src/layout/content.tsx, src/layout/footer.tsx, src/layout/header.tsx, src/layout/layout.tsx, src/popconfirm/popconfirm.tsx, test/ssr/__snapshots__/ssr.test.js.snap, test/unit/popconfirm/__snapshots__/demo.test.js.snap
- use renderTNodeJSX to render default
- add prefix
-  remove outer div
=> chore(layout): layout and popconfirm code optimize

site/index.html, site/package.json
use horizon agent to collect user operational data.
=> feat: add horizon

src/steps/step-item.tsx, test/ssr/__snapshots__/ssr.test.js.snap, test/unit/steps/__snapshots__/demo.test.js.snap
=> refactor(steps): css name follow bem

src/popup/popup.tsx
bug: https://git.woa.com/TDesign/tdesign-web-vue/issues/935
=> popup-鼠标移到弹出层外松开，弹出层不消失

src/pagination/pagination.tsx, test/ssr/__snapshots__/ssr.test.js.snap, test/unit/pagination/__snapshots__/demo.test.js.snap
use input-number replace input
=> fix(pagination): use input-number replace input

src/tree-select/tree-select.tsx
- Component Name: Describe what kind of issues you've done. [pr#xxx](pr url)，[issue#xxx](issue url)，[your github name](your github homepage)
- tree-select：修复组件data异步加载展示异常的问题， [pr#103](https://github.com/Tencent/tdesign-vue/pull/103)，[issue#96](https://github.com/Tencent/tdesign-vue/issues/96)，[@Godlike-meteor](https://github.com/Godlike-meteor)
--------
**brefore**
.....
**after**
......
=> fix(tree-select): fix data lazy load bug

site/src/App.vue, site/src/components/reload-prompt.vue, site/src/sw.js
=> feat: add pwa install

src/tabs/tab-nav.tsx
- tabs：窗口resize时重新计算navbar[Startan](https://github.com/start940315)
=> fix(tab): recaculate nav bar on resize

src/textarea/textarea.tsx
fix  textarea change event parmas
=> fix: textarea parmas

site/docs/getting-started.md
=> docs: update getting started document

package.json, test/ssr/__snapshots__/ssr.test.js.snap
=> feat: 左侧路由支持监听 replaceState 切换高亮

test/ssr/__snapshots__/ssr.test.js.snap, test/ssr/ssr.test.js
处理jest升级后ssr test mockDate固定时间不生效的问题 
改为使用jest的setSystemTime 验证过有效。
为了避免和今天的提交冲突  就固定在今天吧。
=> chore: jest ssr date fixed

src/tabs/tab-panel.tsx, src/tabs/tabs.tsx
- tabs：panel组件更新后更新父组件的tab nav [startan](https://github.com/start940315)
=> feat(tabs): update panels after panel comp updated

src/tabs/tab-panel.tsx, src/tabs/tabs.tsx
- tabs：inject parent，防止tabs和tab_panel不是直接父子关系 [startan](https://github.com/start940315)
=> feat(tabs): inject parent

src/menu/menu-item.tsx
Menu: 修复菜单选项的图标判断逻辑
** Before **
通过 render function 传入 icon 时，错误判断成无 icon 场景，导致收起菜单时，多了一个字符 “1”
** After **
不显示字符 “1“
=> fix(menu): correct plain menu item

src/comment/comment.tsx
- comment: 修复avatar属性不支持slot的问题，[@dreamsqin ](https://github.com/dreamsqin)
--------
```html
<template>
<t-comment
author="评论作者名"
datetime="今天16:38"
content="这里是评论者写的评论内容。"
>
<template #avatar>
<div style="background-color: yellow;width: 50px;height: 50px;text-align: center;line-height: 50px;">avatar</div>
</template>
</t-comment>
</template>
```
**brefore**
.....
**after**
......
=> fix(comment): resolve the issue of avatar unsupported slots

src/date-picker/date-picker.tsx, src/input/input.tsx, test/ssr/__snapshots__/ssr.test.js.snap, test/unit/date-picker/__snapshots__/demo.test.js.snap, test/unit/date-picker/__snapshots__/index.test.js.snap, test/unit/drawer/__snapshots__/demo.test.js.snap, test/unit/form/__snapshots__/demo.test.js.snap, test/unit/input/__snapshots__/demo.test.js.snap, test/unit/input/__snapshots__/index.test.js.snap, test/unit/message/__snapshots__/demo.test.js.snap, test/unit/popup/__snapshots__/demo.test.js.snap, test/unit/select/__snapshots__/demo.test.js.snap, test/unit/time-picker/__snapshots__/demo.test.js.snap, test/unit/transfer/__snapshots__/demo.test.js.snap, test/unit/tree-select/__snapshots__/demo.test.js.snap, test/unit/tree-select/__snapshots__/index.test.js.snap, test/unit/tree/__snapshots__/demo.test.js.snap
修改样式
- Input: 修复清除数据后没有聚焦的问题，[pr#91](https://github.com/Tencent/tdesign-vue/pull/91)，[issue#90](https://github.com/Tencent/tdesign-vue/issues/90)，[@clark-cui](https://github.com/clark-cui)
=> fix(input): 修改样式

src/swiper/swiper.tsx, src/tabs/tab-nav.tsx, test/ssr/__snapshots__/ssr.test.js.snap, test/unit/swiper/__snapshots__/demo.test.js.snap, test/unit/tabs/__snapshots__/demo.test.js.snap, test/unit/tabs/__snapshots__/index.test.js.snap
- fix(ie): 兼容ie9, 调整swiper和tabs的translate3d为translate
=> fix(ie): 兼容ie9, 调整swiper和tabs的translate3d为translate

src/table/base-table/index.tsx
- Component Name: Describe what kind of issues you've done. [pr xxx](pr url)，[#xxx](issue url)，[your github name](your github homepage)
- Table：异步拉取数据 maxHeight 不生效的问题 #134
--------
**brefore**
.....
**after**
......
=> fix(table): 异步拉取数据 maxHeight 不生效的问题 #134

src/table/base-table/index.tsx, test/ssr/__snapshots__/ssr.test.js.snap, test/unit/table/__snapshots__/demo.test.js.snap, test/unit/table/__snapshots__/index.test.js.snap
- Table：固定表头没有对齐的问题
--------
**brefore**
**after**
=> fix(table): 固定表头没有对齐的问题

README.md, site/docs/getting-started.md
=> docs: 加 umd 直接引入方式安装

package.json, site/src/main.js, site/vite.config.js
=> fix: surge hash router

site/docs/getting-started.md
=> docs: complete document about auto import

src/cascader/cascader.tsx, src/cascader/components/InputContent.tsx
=> fix: cascader  input style

src/time-picker/panel/panel-col.tsx, src/time-picker/time-range-picker.tsx, test/unit/time-picker/__snapshots__/demo.test.js.snap
- time-picker: 为了兼容ie9，新增类${componentName}__range 来识别是否是time-range，新增col属性来识别time-picker有多少列
- 组件名称：time-picker，[https://github.com/Tencent/tdesign-vue/pull/229]，[lanniuniu](https://github.com/lanniuniu)
--------
**brefore**
.....
**after**
......
=> fix: 兼容ie time-picker组件 增加的类和属性

src/table/base-table/table-body.tsx
- Table: 合并单元格问题
**brefore**
**after**
=> fix(table): 合并单元格问题 #242

src/utils/ripple.ts
-处理Ripple dataset为null导致的IE异常报错
[https://github.com/Tencent/tdesign-vue/issues/287](#287 )，[https://github.com/brianzhang](brianzhang)
=> fix: ripple-dataset null error

examples/input/demos/status.vue, examples/input/input.md, src/input/input.tsx, src/input/props.ts, src/input/type.ts, test/ssr/__snapshots__/ssr.test.js.snap, test/unit/date-picker/__snapshots__/demo.test.js.snap, test/unit/date-picker/__snapshots__/index.test.js.snap, test/unit/input/__snapshots__/demo.test.js.snap, test/unit/input/__snapshots__/index.test.js.snap, test/unit/select/__snapshots__/demo.test.js.snap, test/unit/time-picker/__snapshots__/demo.test.js.snap
- Input：新增 `tips` `mousenter` `mouseleavt` `paste` 等新特性，[pr#305](https://github.com/Tencent/tdesign-vue/pull/305)，[@chaishi](https://github.com/chaishi)
=> feat(input): add tips/mouseenter/mouseleave/paste to input

examples/tree-select/demos/valuedisplay.vue, src/tree-select/tree-select.tsx
- Component Name: Describe what kind of issues you've done. [pr xxx](pr url)，[#xxx](issue url)，[your github name](your github homepage)
TreeSelect #233
=> feat(tree-select): add valueDisplay props

src/table/base-table/table-header.tsx, test/ssr/__snapshots__/ssr.test.js.snap, test/unit/table/__snapshots__/demo.test.js.snap
- Table：多级表头问题，[#pr#324](https://github.com/Tencent/tdesign-vue/pull/324)，[issue#290](https://github.com/Tencent/tdesign-vue/issues/290)，[@realyuyanan](https://github.com/realyuyanan)
--------
**brefore**
**after**
=> fix(table): 多级表头问题 #290

src/button/button.tsx, src/grid/row.tsx, src/slider/slider-button.tsx
- Component Name: Describe what kind of issues you've done. [pr xxx](pr url)，[#xxx](issue url)，[your github name](your github homepage)
- button：button 在ie9下 删除disabled属性，[pr 323](https://github.com/Tencent/tdesign-vue/pull/323)，[#xxx](issue地址)，[lanniuniu](https://github.com/lanniuniu)
--------
**brefore**
.....
**after**
......
=> fix: button 在ie9下 删除disabled属性

site/src/main.js
=> feat: 优化页面切换体验

src/list/list-item.tsx, test/ssr/__snapshots__/ssr.test.js.snap, test/unit/list/__snapshots__/demo.test.js.snap, test/unit/list/__snapshots__/index.test.js.snap
- list: content 外层增加一个 t-list-item__content 类，以适应 ie9下flex兼容的 table 布局。[pr#348](https://github.com/Tencent/tdesign-vue/pull/348)  [wwervin72](https://github.com/wwervin72)
=> list ie9 flex 兼容

src/select/select.tsx, test/unit/select/__snapshots__/demo.test.js.snap, test/unit/select/__snapshots__/index.test.js.snap
- Select: 更改加载中的元素标签，[pr 356](https://github.com/Tencent/tdesign-vue/pull/356)，[@geff1991](https://github.com/geff1991)
- 更改前
- 更改后
=> feat: 更改加载中的元素标签

examples/tooltip/demos/base.vue
- tooltip: 基础用法 demo 触发条件问题，[issue#353]](https://github.com/Tencent/tdesign-vue/issues/353)，[ccccpj](https://github.com/ccccpj)
=> feat: tooltip demo trigger

site/src/components/demo-page.vue, site/src/routes.js
=> feat: 优化开发调试环境

examples/transfer/demos/base.vue, examples/transfer/demos/tree.vue
=> docs: 修复transfer demo示例checked-change事件

src/table/base-table/table-cell.tsx
- fix(table): 固定列宽为string时偏移问题
=> fix(table): 固定列宽为string时偏移问题

src/time-picker/panel/index.tsx, src/time-picker/panel/panel-col.tsx
- 日常 bug 修复
- https://github.com/Tencent/tdesign-vue/issues/107
- 改onmousewheel事件为scroll事件
- fix(time-picker): 修复部分鼠标滚动选择出现偏差的问题
=> fix(timepicker): panel scroll

src/skeleton/skeleton.tsx
日常 bug 修复
- fix(skeleton): row col not working
=> fix(skeleton): row col not working

src/form/form-model.ts, src/form/form.tsx
日常 bug 修复
- 值为数组，则 max 和 min 表示校验数组长度 [issue301](https://github.com/Tencent/tdesign-react/issues/301)
- 阻止input回车提交表单 [issue400](https://github.com/Tencent/tdesign-vue/issues/400)
=> fix(form): max min and input keydown

examples/notification/demos/footer.vue, examples/notification/demos/operation.vue, test/ssr/__snapshots__/ssr.test.js.snap
- 演示代码改进, notification 示例增加 closeBtn api 相关的demo
before
after
=> feat(notification demo): notification operation example add close demo

src/grid/row.tsx
bug 修复
- fix(grid):  row-gap属性ie生效版本调整为11
PR地址：https://github.com/Tencent/tdesign-vue/pull/457
PR人：[lanniuniu](https://github.com/lanniuniu)
=> fix: 修复row-gap生效版本

CONTRIBUTING.md, site/vite.config.js
文档改进
项目初始化文档修改
子系统需要ssh拉取，同时vite开发环境路径配置有误，修改如图所示
build: 完善初始化文档
=> build: 完善初始化文档

examples/table/demos/filter-controlled.vue, examples/table/demos/multi-header.vue, examples/table/demos/pagination-ajax.vue, src/hooks/useDefaultValue.ts, src/table/hooks/useAsyncLoading.tsx, src/table/hooks/useClassName.ts, src/table/hooks/useColumnController.tsx, src/table/hooks/useFilter.tsx, src/table/hooks/useSorter.tsx, src/table/hooks/useTableBody.tsx, src/table/hooks/useTableHeader.tsx, src/table/primary-table.tsx
=> 20220127 feature table composition api

examples/table/demos/tree-select.vue, examples/table/demos/tree.vue, examples/table/table.md, src/table/README.md, src/table/_table.tsx, src/table/ellipsis.tsx, src/table/enhanced-table.tsx, src/table/enhanced-table/tree-store.ts, src/table/hooks/useClassName.ts, src/table/hooks/useTableBody.tsx, src/table/hooks/useTableHeader.tsx, src/table/hooks/useTreeData.tsx, src/table/index.ts, src/table/primary-table.tsx, src/table/sorter-button.tsx, src/table/type.ts
=> feat(table): tree data

src/table/ellipsis.tsx, src/table/hooks/useClassName.ts, src/table/hooks/useTableBody.tsx, src/table/hooks/useTreeData.tsx, src/table/primary-table.tsx, src/table/tr.tsx
=> feat(table): move tr to tr.tsx from  userTableBody.tsx

src/config-provider/useConfig.tsx
=> feat(useconfig): add useConfig hook

examples/select/demos/panel.vue, src/select/select.tsx
- Select: 自定义创建示例，自定义面板的选择器示例。 [pr 483](https://github.com/Tencent/tdesign-vue/pull/483)，[issuse#388](https://github.com/Tencent/tdesign-vue/issues/388)，[@geff1991](https://github.com/geff1991)
=> fix(select): 自定义创建示例

src/popup/container.tsx, src/utils/dom.ts
兼容部分浏览不支持dom.remove
- fix(popup): 兼容dom.remove
=> fix(ie：remove): ie:dom.remove

examples/config-provider/config-provider.md, src/button/button.tsx, src/cascader/components/Item.tsx, src/config-provider/config-receiver.ts, src/config-provider/type.ts, src/dropdown/dropdown-item.tsx, src/menu/menu-item.tsx, src/menu/submenu.tsx, src/select/option.tsx, src/tabs/tab-nav-item.tsx, src/transfer/components/transfer-list.tsx, src/tree/tree-item.tsx, src/utils/ripple.ts
- 新特性提交，支持通过全局配置关闭斜八度波纹动画
- API见文档，使用方式如
```
<ConfigProvider :global-config="{ animation: { exclude:['ripple'] } }">
```
- 由于涉及的组件有的用vue2写法有的用vue3写法 所以没法像vue3一样直接上hooks，见 https://github.com/Tencent/tdesign-vue-next/pull/389 。所以还是保留了directive的实现方式，通过mixins获取全局的动画配置，然后简单改造一下ripple这个directive，如果计算得到全局的ripple配置为false就不继续执行动画；
- 其他动画关闭支持待提交其他PR来处理
- feat(全局配置): 支持关闭斜八度波纹动画
=> feat: 支持通过全局配置关闭斜八度波纹动画

src/time-picker/time-picker.tsx, src/time-picker/time-range-picker.tsx
- 日常 bug 修复 修复0.34版本popup重构导致visible处理方式变更
- fix(time-picker): 修复禁用态仍可打开panel的问题
=> fix(timepicker): trigger panel when disable

src/drawer/drawer.tsx
- 日常 bug 修复
- fix https://github.com/Tencent/tdesign-vue/issues/504
- fix(drawer): 修复drawer组件destroyOnClose为true时报错问题
=> fix(drawer): 修复drawer组件destroyOnClose为true时报错问题

CHANGELOG.md, package.json
=> Docs/changelog 0.36.0

src/tree/td-tree.tsx
性能优化
tree 里节点渲染
https://github.com/Tencent/tdesign-vue/issues/478
treeStore中的treeNode已经进行数据重写，而且vue内部已经注入了get set的监听 如果显示则重新生成新的vnode，没有就维持住旧的节点，只是进行隐藏即可
splice 性能差 耗时严重，重新生成即可
直接渲染的结果
降低到30ms左右
=> feat: 提升tree-item的vnode节点渲染速度

examples/tag-input/demos/base.vue, src/input-number/input-number.tsx, src/input/input.tsx, src/select/select.tsx, test/ssr/__snapshots__/ssr.test.js.snap, test/unit/calendar/__snapshots__/demo.test.js.snap, test/unit/calendar/__snapshots__/index.test.js.snap, test/unit/date-picker/__snapshots__/demo.test.js.snap, test/unit/date-picker/__snapshots__/index.test.js.snap, test/unit/drawer/__snapshots__/demo.test.js.snap, test/unit/form/__snapshots__/demo.test.js.snap, test/unit/input-number/__snapshots__/demo.test.js.snap, test/unit/input-number/__snapshots__/index.test.js.snap, test/unit/input/__snapshots__/demo.test.js.snap, test/unit/input/__snapshots__/index.test.js.snap, test/unit/message/__snapshots__/demo.test.js.snap, test/unit/pagination/__snapshots__/demo.test.js.snap, test/unit/popup/__snapshots__/demo.test.js.snap, test/unit/select/__snapshots__/demo.test.js.snap, test/unit/select/__snapshots__/index.test.js.snap, test/unit/slider/__snapshots__/index.test.js.snap, test/unit/tag-input/__snapshots__/demo.test.js.snap, test/unit/time-picker/__snapshots__/demo.test.js.snap, test/unit/transfer/__snapshots__/demo.test.js.snap, test/unit/tree-select/__snapshots__/demo.test.js.snap, test/unit/tree-select/__snapshots__/index.test.js.snap, test/unit/tree/__snapshots__/demo.test.js.snap
修复不同状态的标签输入框样式异常
- fix(input): 
- 修复前后置标签输入框同事存在时左侧样式异常
- dom节点调整 https://github.com/Tencent/tdesign-common/pull/276
- chore(select): 增加select 组件 polyfill class，重构兼容代码，无需记录changelog
- fix(tag-input): 修复不同状态的标签输入框样式异常
=> refactor: input wrapclass

src/select/select.tsx, test/ssr/__snapshots__/ssr.test.js.snap, test/unit/calendar/__snapshots__/demo.test.js.snap, test/unit/calendar/__snapshots__/index.test.js.snap, test/unit/pagination/__snapshots__/demo.test.js.snap, test/unit/select/__snapshots__/demo.test.js.snap, test/unit/select/__snapshots__/index.test.js.snap, test/unit/transfer/__snapshots__/demo.test.js.snap
增加select icon的兼容class
- fix(select): 增加select icon的兼容class，解决样式问题
=> fix(select): add select right icon polyfill

src/select/select.tsx, test/ssr/__snapshots__/ssr.test.js.snap, test/unit/calendar/__snapshots__/demo.test.js.snap, test/unit/calendar/__snapshots__/index.test.js.snap, test/unit/pagination/__snapshots__/demo.test.js.snap, test/unit/select/__snapshots__/index.test.js.snap
- Select: 单选已选值不在可选项时，显示为空的问题。 [pr 483](https://github.com/Tencent/tdesign-vue/pull/530)，[issuse#526](https://github.com/Tencent/tdesign-vue/issues/526)，[@geff1991](https://github.com/geff1991)
=> fix: 单选已选值不在可选项时不显示的问题

examples/select-input/demos/width.vue, src/hooks/useDefaultValue.ts, src/hooks/useVModel.ts, src/input/input.tsx, src/select-input/useMultiple.tsx, src/select-input/useSingle.tsx, src/tag-input/tag-input.tsx, src/tag-input/useTagList.tsx, src/tag-input/useTagScroll.ts, test/ssr/__snapshots__/ssr.test.js.snap
简化useVModle和useDefaultValue 参数。
fix(tag-input): 
- 修复 breakline 模式下的clearIcon样式重叠 https://github.com/Tencent/tdesign-common/pulls
- 修复 autowidth 模式下的 padding 不对称 https://github.com/Tencent/tdesign-common/pulls
- 修复超出滚动失效
- 修复paste事件未生效
fix(input): 修复在readonly模式下的聚焦样式
=> fix(tag-input): scroll error and autowidth style

src/input-number/input-number.tsx, test/unit/input-number/__snapshots__/index.test.js.snap, test/unit/input-number/index.test.js
- 日常 bug 修复 修复Input-number小数计算问题
- 测试用例 补充小数相关的测试用例
- fix https://github.com/Tencent/tdesign-vue/issues/559
- fix(input-number): 小数计算错误问题
=> fix(input-number): decimal calculate

examples/form/demos/clear-validate.vue, examples/form/demos/validator.vue, test/ssr/__snapshots__/ssr.test.js.snap
- 演示代码改进 展示大部分表单组件在复杂状态下 status变化的demo
- fix(form): 修复表单中组件状态颜色异常问题
=> chore: update form validator demo

src/message/animation.ts
- fix(Message): IE浏览器下`animation.onfinish`方法调用时出现`TypeError: Object doesn't support property or method 'animate'`
=> Fix: animation.onfinish IE Error

src/popup/popup.tsx
=> fix: 修复 popular ie9/10 document 收不到冒泡事件

src/time-picker/panel/index.tsx, src/time-picker/time-picker.tsx, src/time-picker/time-range-picker.tsx
- 日常 bug 修复 close、open事件回调增加参数
- fix(time-picker):  close、open事件回调增加参数
=> fix(time-picker): close&open event params

src/date-picker/date-picker.tsx, src/date-picker/interface.ts, src/input/input.tsx, src/time-picker/time-picker.tsx, src/time-picker/time-range-picker.tsx, test/ssr/__snapshots__/ssr.test.js.snap, test/unit/date-picker/__snapshots__/demo.test.js.snap, test/unit/date-picker/__snapshots__/index.test.js.snap, test/unit/time-picker/__snapshots__/demo.test.js.snap
=> fix: clearable of datepicker and timepicker

src/input-number/input-number.tsx
处理 inputnumber value = null 的情况，不会有 toFixed 调用报错
- fix(InputNumber): 修复 `value` 为 null 时组件报错的问题 
=> fix: inputnumber null value

src/select/select.tsx
- Select: 未选值时，键盘事件不生效的问题。 [pr 603](https://github.com/Tencent/tdesign-vue/pull/603)，[@geff1991](https://github.com/geff1991)
=> fix: keyboard event

src/popup/popup.tsx
https://github.com/Tencent/tdesign-vue/issues/558
- fix(popup): 修复 document click 多次触发导致的关闭
=> fix(popup): 修复 document click 多次触发导致的关闭

.github/ISSUE_TEMPLATE/config.yml, .github/workflows/issue-synchronize.temp.yml
=> fix: update issue helper

examples/message/demos/placement.vue, src/message/animation.ts
无
docs(message): fix style of input in placement api
fix(message): changed direction of fadeout animation in center
=> fix(message): change direction of fadeout animation in center, and style of button in doc

src/message/animation.ts
=> fix: 修复ie9 message没有触发fadeOut回调的缺陷

src/upload/upload.tsx
- [✅ ] 日常 bug 修复
> handleSuccess回调并发导致v-model设置数据丢失
修改files用concat拼接方式为push数据
```js
this.multiple && this.files.push(...newFiles);
```
- fix(Upload): 处理handleSuccess回调并发导致v-model设置数据丢失
=> 【Upload】- handleSuccess回调并发导致v-model设置数据丢失

.husky/pre-commit, package.json
=> ci: 清除package.json的husky，添加pre-commit的邮件检查

src/select-input/useSingle.tsx
=> fix: select-input single inputValue

CHANGELOG.md, package.json
=> docs: CHANGELOG for 0.38.1

src/tree-select/tree-select.tsx
#550
- fix(tree-select): 修复filter状态下，tree无法折叠的BUG;
- fix(tree-select): 修复lazy状态下，label无法正确展示的问题；
=> Fix/tree select/filter

src/cascader/index.ts, src/dropdown/index.ts, src/slider/index.ts, src/transfer/index.ts
`TdCascaderProps` `TdDropdownProps` `TdDropdownItemProps` `TdSliderProps` `TdTransferProps` 没有导出
- fix: 遗漏组件类型导出
=> fix: typings export

examples/select-input/demos/autowidth-multiple.vue, examples/select-input/demos/borderless-multiple.vue
before
after
- fix(select-input): demo样式修复
=> fix: select-input style

src/upload/flow-list.tsx
=> fix: upload progress text

examples/dropdown/dropdown.md
=> chore: modify dropdown minColumnWidth description

src/table/tr.tsx
- fix(table):IE requestAnimationFrame 兼容方法提取
=> [Fix/table] IE requestAnimationFrame 兼容方法调用提取

examples/form/demos/align.vue, examples/form/demos/base.vue, examples/form/demos/clear-validate.vue, examples/form/demos/custom-validator.vue, examples/form/demos/disabled.vue, examples/form/demos/error-message.vue, examples/form/demos/login.vue, examples/form/demos/reset.vue, examples/form/demos/size.vue, examples/form/demos/validate-complicated-data.vue, examples/form/demos/validate-message.vue, examples/form/demos/validator-status.vue, examples/form/demos/validator.vue, src/form/form-item.tsx, test/ssr/__snapshots__/ssr.test.js.snap, test/unit/form/__snapshots__/demo.test.js.snap
breack change：
label 为空不再渲染宽度作占位
=> feat(form): label 为空时不再处理占位对齐问题

examples/table/demos/drag-col-sort.vue, examples/table/demos/drag-sort.vue, src/table/hooks/useDragSort.ts, src/table/tbody.tsx, src/table/tr.tsx, test/ssr/__snapshots__/ssr.test.js.snap, test/unit/table/__snapshots__/demo.test.js.snap
=> feat(table): 表格拖拽排序支持完全受控

src/form/form-item.tsx
=> fix: 修复 formItem slot label 未占位问题

src/popup/container.tsx, src/popup/popup.tsx
=> feat(popup): 优化部分写法

src/transfer/utils.ts, test/unit/transfer/index.test.js
fix #397
修复 https://github.com/Tencent/tdesign-vue/issues/397
- 修复 `Transfer` 设置 `targetSort` 后未按预期展示的问题
=> fix(transfer): 修复targetSort展示问题

examples/tree/demos/line.vue
注意这个文件的最后一行：
```css
transform-origin: 50%, 50%;
```
根据 [MDN](https://developer.mozilla.org/zh-CN/docs/Web/CSS/transform-origin) 的描述，这个属性的值应该用空格分隔，而不是逗号，因此我修复了它。
其他的修改同样是 ESLint / Prettier 介入的结果。
=> fix(examples): 修复 CSS 的问题

examples/input-number/demos/status.vue, examples/popup/demos/placement.vue, examples/select-input/demos/autowidth-multiple.vue, examples/select-input/demos/borderless-multiple.vue, examples/select-input/demos/collapsed-items.vue, examples/select-input/demos/multiple.vue, examples/table/demos/data-sort.vue, examples/table/demos/expandable.vue, examples/table/demos/multiple-sort.vue, examples/table/demos/select-multiple.vue, examples/table/demos/select-single.vue, examples/table/demos/show-columns.vue, examples/table/demos/single-sort.vue, examples/table/demos/tree-select.vue, examples/tooltip/demos/base.vue, examples/transfer/demos/empty.vue, test/ssr/__snapshots__/ssr.test.js.snap
我修复了两个 CSS 风格的问题：
1. 去掉冗余的单位（`0px` -> `0`）
2. 使用简写风格（`margin: 0; margin-bottom: 4px;` -> `margin: 0 0 4px;`）
除此之外，在提交代码时，触发了 Git Hook，使得 Prettier 和 ESLint 介入修复了一些代码风格。
=> style(examples): 修改 CSS 格式 & ESLint & Prettier

src/tree-select/tree-select.tsx
#722 
#635 
1、修复：value 为数字0时，不渲染label的问题；
2、修复：onBlur 和 onClear 触发时，不会清除filter function的问题。
- fix(tree-select):修复value渲染异常，修复触发onBlur和onClear时不会清除filter function的问题。
=> fix(tree-select): bug

.github/workflows/auto-release.yml
修改 package.json 的 pr 中，在评论区中生成 changelog 内容。
=> feat: auto generate changelog

src/form/const.ts, src/form/form-item.tsx, test/ssr/__snapshots__/ssr.test.js.snap, test/unit/config-provider/__snapshots__/demo.test.js.snap, test/unit/form/__snapshots__/demo.test.js.snap, test/unit/input-number/__snapshots__/demo.test.js.snap, test/unit/tree/__snapshots__/demo.test.js.snap
=> fix: form helpNode staus error

src/index.ts
VueCompositionAPI 只能注册一次，如果有其他的库调用过 `Vue.use(VueCompositionAPI)`，`tdesign-vue` 再次注册会报错：
解决方案为注册前加判断逻辑：`if (Vue._installedPlugins.indexOf(VueCompositionAPI) === -1) Vue.use(VueCompositionAPI);`
=> fix: 防止VueCompositionAPI重复注册

src/dialog/dialog.tsx
https://github.com/Tencent/tdesign-vue/issues/612
- fix(dialog): 修复 dialog 初始化时滚动穿透问题
=> fix: 修复 dialog 初始化时滚动穿透问题

examples/message/demos/plugin.vue, examples/message/message.md, src/message/messageList.tsx, src/message/plugin.tsx, src/message/props.ts, src/message/type.ts, test/ssr/__snapshots__/ssr.test.js.snap, test/unit/message/__snapshots__/demo.test.js.snap
message增加全局配置默认值能力
fix #663
resolve #663 
message确实全局配置默认属性的能力
通过`$meesage.config`设置全局默认值
- feat(message): message增加全局配置默认值能力
=> feat(message): message增加全局配置默认值能力

examples/pagination/demos/base.vue, examples/pagination/pagination.md, src/pagination/pagination.tsx, src/pagination/props.ts, src/pagination/type.ts, test/ssr/__snapshots__/ssr.test.js.snap, test/unit/pagination/__snapshots__/demo.test.js.snap
- feat(Pagination): 新增 showFirstAndLastPageBtn、showPreviousAndNextBtn、showPageSize、showPageNumber api
=> feat: 新增 showFirstAndLastPageBtn、showPreviousAndNextBtn、showPageSize、showPageNumber api

src/date-picker/panel/date-range.tsx
fix [756](https://github.com/Tencent/tdesign-vue/issues/756)
- fix(DatePicker):  修复DatePicker 点击快捷选择日期按钮左边面板日期时间不联动
=> fix: 修复DatePicker 点击快捷选择日期按钮左边面板日期时间不联动

package.json
=> feat: remove unused dep

examples/config-provider/config-provider.md, src/config-provider/type.ts, src/table/interface.ts
- fix(ConfigProvider): 修复`animation`属性`exclude`和`include`在TS中都必填的问题
- fix(Table): `renderExpandedRow`为非必填
=> fix: ts type

site/src/components/base-usage.vue
=> fix: 修复 popup live demo 问题

examples/dialog/dialog.md
https://github.com/Tencent/tdesign-react/issues/713
https://github.com/Tencent/tdesign-common/issues/448
该问题来自于 tdesign-common 的 md 文案修改。
tdesign-common/dialog 中删去了关于 “插件函数式调用” 的相关公共描述。理由是该公共描述涉及 vue 特定的语法糖，从而在 tdesign-react 的网站中描述会使读者产生困惑。故需从 common 仓库删除，在 [tdesign-vue](https://github.com/Davont/tdesign-vue) 本仓库中自维护 。
> 备注：**该 PR 不会对 文案本身产生任何修改，只涉及 md 文案引用方式。**
- docs(Dialog): 更新 dialog “插件函数式调用”的描述
=> docs(Dialog): 更新 dialog “插件函数式调用”的描述

examples/dropdown/demos/slot.vue, src/dropdown/dropdown-menu.tsx, src/dropdown/dropdown.tsx
- 日常 bug 修复
- https://github.com/Tencent/tdesign-vue/issues/840
- fix(dropdown): 插槽模式下maxHeight失效的问题
- fix(dropdown): 透传popup事件问题
=> fix(dropdown): maxHeight for slot and popup event

package.json
- 新特性提交 更新图标 新增`file-icon`图标 修改部分图标路径
- feat(Icon): 更新图标 新增`file-icon`图标 调整`file-excel`、`file-pdf`、`file-powerpoint`、`file-unknown`、`file-word`和`star-filled`图标的绘制路径
=> chore: update icon

.github/workflows/pr-spelling.template.yml, .github/workflows/typos-config.toml, CHANGELOG.md, examples/calendar/demos/cell.vue, examples/calendar/demos/slot-props-api.vue, examples/dialog/demos/attach.vue, examples/message/demos/plugin.vue, script/test/generate-coverage.js, site/src/components/base-usage.vue, src/form/form-item.tsx, src/table/enhanced-table.tsx, src/table/hooks/useTreeData.tsx, src/table/tr.tsx, src/time-picker/interface.ts, test/ssr/__snapshots__/ssr.test.js.snap, test/unit/calendar/__snapshots__/demo.test.js.snap
=> feat: add spell check

examples/anchor/demos/container.vue
https://github.com/Tencent/tdesign-common/pull/464
=> feat(anchor): 增加 demo 演示功能

src/transfer/components/transfer-list.tsx
fix #869
fix #869 
- fix(Transfer): 修复列表数量变化时的页码展示问题
=> fix(transfer): update current page when total size change

examples/input/usage/props.json, examples/select-input/demos/single.vue, examples/select-input/usage/index.vue, examples/select-input/usage/props.json, src/input/input.tsx, src/select-input/useSingle.tsx
- fix(select-input): 修复无法触发 `@mouseenter`, @mouseleave` 无效
- fix(input): 修复 `clear` 触发后的 `focus`, 修复外部传入`onMouseenter`, `onMouseleave`, `onwheel` 事件导致组件内对应`方法`无法执行
=> fix: select-input event

.github/workflows/pr-compressed-size.yml, src/swiper/style/index.js
- 组件样式/交互改进 替换swiper样式路径
- 关联Common改动 https://github.com/Tencent/tdesign-common/pull/476
=> chore: replace swiper style path

examples/select/usage/index.vue
- 演示代码改进
- https://github.com/Tencent/tdesign-vue/issues/876
=> chore: fix select live demo

src/tabs/tab-nav-item.tsx, src/tabs/tab-nav.tsx, test/unit/tabs/__snapshots__/index.test.js.snap
- fix(Tabs): 修复选项卡新增和删除在normal风格下无效 ([issue #865](https://github.com/Tencent/tdesign-vue/issues/865))
=> fix: tabs addable

examples/input-number/input-number.md, src/common.ts, src/input-number/input-number.tsx, src/input-number/props.ts, src/input-number/type.ts
fix #917
- [✅] 新特性提交
https://github.com/Tencent/tdesign-vue/issues/917
1. 希望在 t-input-number 中能自定义 t-input 的属性
2. 将 props 透传给 t-input
- feat(input-number): 透传 Input 组件全部特性，即 inputProps
- [✅] 文档已补充或无须补充
- [✅] 代码演示已提供或无须提供
- [✅] TypeScript 定义已补充或无须补充
- [✅] Changelog 已提供或无须提供
=> feat(input-number): 透传 Input 组件全部特性，即 inputProps

src/color-picker/utils/click-outsider.ts, src/utils/dom.ts
=> fix: ssr render

site/plugin-tdoc/md-to-vue.js
=> fix: 修复 windows 下usage 路径报错问题

src/popup/container.tsx, src/popup/popup.tsx
- feat(popup): 支持动态设置 trigger & placement
- fix(popup): add zIndex api
- fix(popup): 修复初始化 visible 为 true 时的定位抖动
=> feat(popup): 支持动态设置 trigger/placement & add zIndex api

test/unit/card/index.test.js
=> test(card): remove redundant unit test for card component

examples/input-adornment/demos/select.vue, examples/input-adornment/demos/text.vue, examples/input-adornment/input-adornment.en-US.md, examples/input-adornment/input-adornment.md, examples/tree/demos/controlled.vue, examples/tree/demos/filter.vue, examples/tree/demos/operations.vue, examples/tree/demos/performance.vue, examples/tree/demos/sync.vue, examples/tree/demos/vscroll.vue, site/site.config.mjs, src/components.ts, src/input-adornment/index.ts, src/input-adornment/input-adornment.tsx, src/input-adornment/props.ts, src/input-adornment/style/css.js, src/input-adornment/style/index.js, src/input-adornment/type.ts, src/input/index.ts, test/ssr/__snapshots__/ssr.test.js.snap, test/unit/input/__snapshots__/demo.test.js.snap, test/unit/tree/__snapshots__/demo.test.js.snap
=> feat: 新增 input-adornment 组件

package.json
=> chore: hide theme generator on mobile device

examples/select/demos/noborder.vue, src/select/optionGroup.tsx, src/select/select-panel.tsx, src/select/select.tsx, test/ssr/__snapshots__/ssr.test.js.snap, test/unit/select/__snapshots__/demo.test.js.snap
=> fix(select): t-option异步加载问题修复；分组列表css优化，支持只展示标题；demo更新

script/init/index.js
chore(script): init check component name is not emtry
=> chore(script): init check component name

examples/dialog/demos/modal.vue, package.json, script/init/index.js, src/dialog/dialog.tsx, test/ssr/__snapshots__/ssr.test.js.snap, test/unit/config-provider/__snapshots__/demo.test.js.snap, test/unit/dialog/__snapshots__/demo.test.js.snap
- #993
部分组件新增`ref`参数
涉及组件：`Anchor`,`Badge`,`Collapse`
- fix(dialog): 修复普通对话框 不脱离文档流
- fix(dialog): 修复点击对话框后对话框会隐藏问题
- fix(dialog): 修复modeless 模式 背景样式点击透传
- fix(dialog): 修复attach挂载showInAttachedElement定位问题
=> fix(dialog): 1、修复普通对话框 不脱离文档流

src/dialog/dialog.tsx
=> feat(dialog): 优化动画初始位置

src/calendar/calendar.tsx, src/color-picker/panel/format/index.tsx, test/ssr/__snapshots__/ssr.test.js.snap, test/unit/calendar/__snapshots__/demo.test.js.snap, test/unit/calendar/__snapshots__/index.test.js.snap, test/unit/color-picker/__snapshots__/demo.test.js.snap, test/unit/config-provider/__snapshots__/demo.test.js.snap
common pr: https://github.com/Tencent/tdesign-common/pull/527
calendar 卡片模式
线上：
修复后：
- fix(Calendar/ColorPicker): 修复组件内部 Select 选择框宽度不能自适应的问题。
=> fix: select auto width

src/tag-input/tag-input.tsx
=> fix(tag-input): 修复方法传参

src/input/input.tsx
- https://github.com/Tencent/tdesign-vue-next/issues/1002
- fix(Input): 修复type为password时clearable不生效的问题
=> fix(input): clearable is not working in password type

src/dialog/dialog.tsx
=> fix: 修复mask 点击事件失效

src/card/card.tsx, src/collapse/collapse-panel.tsx, src/collapse/collapse.tsx, src/color-picker/color-picker-panel.tsx, src/color-picker/hooks.ts, src/color-picker/panel/index.tsx, src/color-picker/panel/swatches.tsx, src/config-provider/config-provider.tsx, src/config-provider/config-receiver.ts, src/config-provider/context.ts, src/config-provider/index.ts, src/config-provider/useConfig.tsx, src/hooks/useConfig.ts, src/select-input/useMultiple.tsx, src/select-input/useSingle.tsx, src/table/hooks/useFilter.tsx, test/ssr/__snapshots__/ssr.test.js.snap
- fix(ConfigProvider): 修复 `useConfig` 的意外注册
- fix(ConfigProvider): 修复因为深拷贝配置文件导致的性能问题
=> fix: useconfig cloneDeep

src/table/hooks/useAsyncLoading.tsx, test/ssr/__snapshots__/ssr.test.js.snap, test/unit/table/__snapshots__/demo.test.js.snap
在 https://github.com/Tencent/tdesign-common/pull/507 中移除了对Table组件中Loading组件的大小设置 忽略了加载更多这里的样式问题 同样需要增加size small处理
- fix(table): 修复加载更多的加载组件尺寸异常问题
=> fix(table): async loading size

src/tree-select/tree-select.tsx
https://github.com/Tencent/tdesign-vue/issues/887
TreeSelect过滤后无法选中
- fix(TreeSelect): 修复过滤后无法选中的问题
=> fix(TreeSelect): 修复过滤后无法选中问题

examples/date-picker/demos/base.vue, examples/date-picker/demos/custom-icon.vue, examples/date-picker/demos/date-presets-alt.vue, examples/date-picker/demos/date-range.vue, examples/date-picker/demos/date-time.vue, examples/date-picker/demos/disable-date.vue, examples/date-picker/demos/first-day-of-week.vue, examples/date-picker/demos/month.vue, examples/date-picker/demos/panel.vue, examples/date-picker/demos/year.vue, src/date-picker/DatePicker.tsx, src/date-picker/DatePickerPanel.tsx, src/date-picker/DateRangePicker.tsx, src/date-picker/DateRangePickerPanel.tsx, src/date-picker/base/Cell.tsx, src/date-picker/hooks/useFormat.ts, src/date-picker/hooks/useTableData.ts, src/date-picker/style/index.js, test/ssr/__snapshots__/ssr.test.js.snap, test/unit/date-picker/__snapshots__/demo.test.js.snap
=> feat: 移除旧版本datepicker 样式

src/range-input/range-input.tsx
- fix(datepicker): 修复 clearable 失效问题
=> feat: 修复 clearble 失效问题

.husky/prepare-commit-msg, package.json, site/src/App.vue, src/time-picker/style/index.js
- 升级主题生成器 改名规范为`<td-theme-generator />` 减少控制台告警
- windows bypass husky prepare-commit-msg
- 修改timepicker样式路径
=> chore: infrastructure 

examples/tag-input/tag-input.md, src/tag-input/props.ts, src/tag-input/type.ts, test/ssr/__snapshots__/ssr.test.js.snap, test/unit/collapse/__snapshots__/demo.test.js.snap, test/unit/select-input/__snapshots__/demo.test.js.snap, test/unit/select/__snapshots__/demo.test.js.snap, test/unit/select/__snapshots__/index.test.js.snap, test/unit/tag-input/__snapshots__/demo.test.js.snap
- feat(tag-input): 默认超出的换行为break-line
=> feat: tag input default break

src/select/select-panel.tsx
- #1062 
- fix(Select): `option`数量小于`threshold`时不开启虚拟滚动
=> fix(select): threshold config 

src/affix/affix.tsx
=> fix(affix): 节点挂载后吸顶没有执行的问题

src/table/base-table.tsx
#1053 
-  fix(table): paginationAffixedBottom 透传Affix 参数不生效
=> fix(table): paginationAffixedBottom 透传Affix 参数不生效

src/select/select.tsx
https://github.com/Tencent/tdesign-vue/issues/1069
- fix(select): 单选下 valueType 为 object 时, onChange返回值类型修复
=> fix(select): 单选下 valueType 为 object 时, onChange返回值类型修复

src/hooks/useDefaultValue.ts, src/hooks/useVModel.ts
https://github.com/Tencent/tdesign-vue/issues/1030
在 useDefaultValue、useVModel中，通过 value 的初始值是否为 `undefined` 来判断是否受控的逻辑，会在用户未初始化变量的情况下导致进入非受控的情况，同步 Vue3 对此场景的修复改动( https://github.com/Tencent/tdesign-vue-next/pull/764 ）
- fix(select): 修复 useDefaultValue、useVModel 初值为 undefined 时, 组件初始化为非受控的问题
=> fix(select): 修复 useDefaultValue、useVModel 初值为 undefined 时, 组件初始化为非受控的问题

examples/select-input/demos/autocomplete.vue, examples/select-input/demos/autowidth.vue, examples/select-input/demos/borderless.vue, examples/select-input/demos/custom-tag.vue, examples/select-input/demos/label-suffix.vue, examples/select-input/demos/single.vue, src/style/index.js
common pr: https://github.com/Tencent/tdesign-common/pull/514
- feat: 去除全局 reset 样式，改为组件内部实现
=> fix: reset component style

src/color-picker/color-picker.tsx, src/color-picker/panel/index.tsx
#1044
#1044
- fix(color-picker): fixed 颜色选择器关闭时， select组件popup未关闭问题 
=> fix(color-picker): fix: 颜色选择器样式异常(#1044)

site/src/components/page.vue
=> chore: filter patch version

examples/date-picker/usage/date-picker-props.json, examples/date-picker/usage/date-range-picker-props.json, examples/date-picker/usage/index.vue, script/generate-usage/config.js, src/date-picker/DatePicker.tsx, src/date-picker/DatePickerPanel.tsx, src/date-picker/DateRangePicker.tsx, src/date-picker/DateRangePickerPanel.tsx, src/date-picker/hooks/useRange.ts, src/date-picker/hooks/useSingle.ts, src/date-picker/panel/ExtraContent.tsx
=> feat: 修复suffixIcon、clear事件问题

src/range-input/range-input-popup.tsx, test/ssr/__snapshots__/ssr.test.js.snap, test/unit/date-picker/__snapshots__/demo.test.js.snap, test/unit/time-picker/__snapshots__/demo.test.js.snap
- fix(RangeInput): 修复失去焦点高亮样式缺失的问题
=> fix: 修复 rangeinput 样式问题

src/space/space.tsx, test/ssr/__snapshots__/ssr.test.js.snap, test/unit/date-picker/__snapshots__/demo.test.js.snap
=> fix: space filter undefined  tag

src/transfer/components/transfer-list.tsx
https://github.com/Tencent/tdesign-vue/issues/1096
- fix(Transfer): 修复穿梭框进行穿梭时报错的问题
=> fix(transfer): fix error when pagination is empty

examples/date-picker/date-picker.md, examples/date-picker/demos/date-presets-alt.vue, src/date-picker/DatePicker.tsx, src/date-picker/DateRangePicker.tsx, src/date-picker/DateRangePickerPanel.tsx, src/date-picker/date-range-picker-panel-props.ts, src/date-picker/date-range-picker-props.ts, src/date-picker/hooks/useRange.ts, src/date-picker/hooks/useRangeValue.ts, src/date-picker/hooks/useSingle.ts, src/date-picker/hooks/useSingleValue.ts, src/date-picker/panel/PanelContent.tsx, src/date-picker/panel/RangePanel.tsx, src/date-picker/panel/SinglePanel.tsx, src/date-picker/props.ts, src/date-picker/type.ts, src/select/select.tsx, src/time-picker/panel/single-panel.tsx, src/time-picker/time-range-picker.tsx, test/ssr/__snapshots__/ssr.test.js.snap
- fix(DatePicker): 修复日期格式化问题 by @HQ-Lin 
- feat(DatePicker): 新增 `panelPreselection api` by @HQ-Lin 
- fix(TimePicker): 优化允许输入滚动的使用体验 by @uyarn 
- fix(TimeRangePicker): 修复允许输入的缺陷   by @uyarn 
- fix(Select): 修复远程搜索动态生成选项失败的缺陷 by @uyarn 
=> feat: 新增 panelPreselection api & 修复日期格式化问题

src/select/select-panel.tsx
=> fix(select): 虚拟滚动支持远程搜索场景

src/dialog/dialog.tsx
- fix(Dialog): 修复阻止冒泡导致 popup 无法正常关闭
=> fix: 修复 dialog 阻止冒泡导致 popup 无法正常关闭

src/drawer/drawer.tsx, test/ssr/__snapshots__/ssr.test.js.snap, test/unit/drawer/__snapshots__/demo.test.js.snap
- https://github.com/Tencent/tdesign-vue/issues/1142
- fix(Drawer): 修复头部渲染异常问题
=> fix: 修复 drawer header 渲染问题

src/popup/popup.tsx
- feat(popup): rename injection key to avoid conflict
=> feat(popup): rename injection key to avoid conflict

examples/table/usage/base-table-props.json, examples/table/usage/index.vue, examples/table/usage/primary-table-props.json, script/generate-usage/config.js
=> feat: 优化 table live demo

src/date-picker/DateRangePicker.tsx, src/date-picker/date-range-picker-props.ts, src/date-picker/panel/RangePanel.tsx, src/date-picker/props.ts
=> feat: 优化面板月份展示

src/date-picker/DatePicker.tsx
- feat(DatePicker): 支持面板年月动态响应 value 变化
=> feat(DatePicker): 支持面板年月动态响应 value 变化

src/select/select-panel.tsx, src/select/select.tsx
-fix(Select): 修复 panelTopContent、panelBottomContent 透传失效
=> fix: 修复 select panelTopContent、panelBottomContent 透传失效

src/table/hooks/useColumnController.tsx
#1161 
- fix(table): 多级表头表格，列配置全选功能选不全
=> fix(table): 多级表头表格，列配置全选功能选不全

src/table/hooks/tree-store.ts
=> feat(table): 修复懒加载插入位置

src/date-picker/base/Header.tsx, src/date-picker/panel/PanelContent.tsx, src/date-picker/panel/RangePanel.tsx, test/ssr/__snapshots__/ssr.test.js.snap
=> feat: 调整 datepicker bem 命名

src/select/select.tsx
- fix(select): 修复部分情况可能导致监听事件未移除的问题（#1170）
- fix(select): 修复 keys 透传问题
=> fix(select): 修复部分情况可能导致监听事件未移除，keys透传问题

examples/time-picker/demos/hm.vue, src/time-picker/panel/single-panel.tsx, test/ssr/__snapshots__/ssr.test.js.snap, test/unit/time-picker/__snapshots__/demo.test.js.snap
=> feat(time-picker): support millisecond

src/select/select.tsx
- fix(select): 处理 select event watch 逻辑问题 （#1170）
=> fix(select): 处理 select event watch 逻辑问题

src/date-picker/panel/PanelContent.tsx
- fix(`DatePicker`): 修复时间选择器滚动错误
=> fix: 修复时间选择器滚动错误

examples/dialog/demos/attach.vue
[#1197](https://github.com/Tencent/tdesign-vue/issues/1197)
test(dialog): dialog测试用例补充
=> test(dialog): dialog测试用例补充

src/dialog/dialog.tsx
fix(dialog): preventScrollThrough是否防止点击穿透功能实现
=> fix(dialog): preventScrollThrough是否防止点击穿透功能实现

src/select/select.tsx
https://github.com/Tencent/tdesign-vue/issues/1212
原有实现只处理了 props 的用法
- fix(Select): 修复 `empty` slot 用法不生效的问题
=> fix: select empty slot render

src/date-picker/DatePicker.tsx, src/date-picker/hooks/useSingle.ts
=> fix(datepicker): 修复单独配置 clearable 失效问题

src/tree-select/tree-select.tsx, test/ssr/__snapshots__/ssr.test.js.snap, test/unit/config-provider/__snapshots__/demo.test.js.snap, test/unit/form/__snapshots__/demo.test.js.snap, test/unit/tree-select/__snapshots__/demo.test.js.snap, test/unit/tree-select/__snapshots__/index.test.js.snap
#1210 
主要是解决TreeSelect组件样式展示的问题，在输入项过长的情况下，仍能边界清晰的展示操作ICON
- fix(tree-select): 修复样式展示问题
=> fix(tree-select): update tree-select styles

.github/workflows/auto-release.yml, .github/workflows/pull-request.yml
=> chore: feature branch ci

examples/rate/rate.en-US.md, examples/rate/rate.md, src/rate/props.ts, src/rate/type.ts
=> feat: 更新 Rate api

src/pagination/pagination.tsx, src/transfer/components/transfer-operations.tsx, test/ssr/__snapshots__/ssr.test.js.snap, test/unit/config-provider/__snapshots__/demo.test.js.snap, test/unit/pagination/__snapshots__/demo.test.js.snap, test/unit/table/__snapshots__/demo.test.js.snap, test/unit/transfer/__snapshots__/demo.test.js.snap
- feat(Pagination): 极简模式下合并快速跳转与页码跳转控制器
=> feat(Pagination): 极简模式下合并快速跳转与页码跳转控制器

README.md, package.json
- feat(主题生成器): 支持字体相关配置
- feat(style): 新增字体相关CSS Token，支持通过CSS Token修改字体相关配置 具体请参考 [font tokens](https://github.com/Tencent/tdesign-common/blob/develop/style/web/theme/_font.less)
- fix(Table): 修复深色模式下垂直和水平方向滚动条交汇处出现白点的样式问题 by @RayJason
=> feat: theme generator add font panel

examples/select/demos/size.vue, src/select/option.tsx, src/tree/td-tree.tsx, src/tree/tree-item.tsx, test/ssr/__snapshots__/ssr.test.js.snap, test/unit/select/__snapshots__/demo.test.js.snap
- fix(tree): 修复样式调整tree组件子节点渲染导致的样式异常
=> chore: fix style

CHANGELOG.md, package.json
=> chore: release 0.45.2

src/date-picker/base/Header.tsx, src/select/select.tsx
=> fix: 修复 datepicker 下拉样式问题

src/table/hooks/useColumnResize.ts
#1225 
1. 添加注释
- fix(table): 宽度计算函数添加注释
=> fix(table): 表格宽度计算函数添加注释

examples/link/demos/base.vue, examples/link/demos/disabled.vue, examples/link/demos/hover.vue, examples/link/demos/icon.vue, examples/link/demos/size.vue, examples/link/demos/theme.vue, examples/link/demos/underline.vue, examples/link/link.en-US.md, examples/link/link.md, examples/link/usage/index.vue, examples/link/usage/props.json, site/site.config.mjs, src/components.ts, src/link/index.ts, src/link/link.tsx, src/link/props.ts, src/link/style/css.js, src/link/style/index.js, src/link/type.ts, src/utils/render-tnode.ts, test/ssr/__snapshots__/ssr.test.js.snap, test/unit/link/__snapshots__/demo.test.js.snap, test/unit/link/__snapshots__/index.test.js.snap, test/unit/link/demo.test.js, test/unit/link/index.test.js
=> feat(link): 完成Link组件样式

src/date-picker/DatePicker.tsx, src/date-picker/DateRangePicker.tsx, src/date-picker/panel/RangePanel.tsx
- fix(`DatePicker`): 修复输入框有值时面板切换失效问题
=> fix(`DatePicker`): 修复输入框有值时面板切换失效问题

examples/form/demos/disabled.vue, examples/input-number/demos/center.vue, examples/input-number/demos/format.vue, examples/input-number/demos/large-number.vue, examples/input-number/demos/left.vue, examples/input-number/demos/normal.vue, examples/input-number/demos/status.vue, examples/input-number/input-number.en-US.md, examples/input-number/input-number.md, src/form/const.ts, src/hooks/useCommonClassName.ts, src/hooks/useFormDisabled.ts, src/hooks/useVModel.ts, src/input-number/index.ts, src/input-number/input-number.tsx, src/input-number/props.ts, src/input-number/type.ts, src/input-number/useInputNumber.tsx, test/ssr/__snapshots__/ssr.test.js.snap, test/unit/color-picker/__snapshots__/demo.test.js.snap, test/unit/config-provider/__snapshots__/demo.test.js.snap, test/unit/form/__snapshots__/demo.test.js.snap, test/unit/input-number/__snapshots__/demo.test.js.snap, test/unit/input-number/__snapshots__/index.test.js.snap, test/unit/input-number/index.test.js, test/unit/pagination/__snapshots__/demo.test.js.snap, test/unit/slider/__snapshots__/demo.test.js.snap, test/unit/slider/__snapshots__/index.test.js.snap, test/unit/table/__snapshots__/demo.test.js.snap, test/unit/transfer/__snapshots__/demo.test.js.snap
- feat(Input): 错误文本提示，不再占普通用文档流（Breaking Change）
- feat(InputNumber): 内置的 input 组件 ref 名称由 `refInputElem` 更为 `inputRef`（Breaking Change）
- feat(InputNumber): 错误文本提示，不再占普通用文档流（Breaking Change）
- feat(InputNumber): 支持超过 16 位的大数
- feat(InputNumber): 支持 `decimal` 和 `format` 组合使用，即 `format` 新增第二个参数小数点格式化之后的值，方便大数场景应用
- feat(InputNumber): 新增事件 `onValidate`，当数值超过最大值或小于最小值时触发，可用于显示错误提示文本
- feat(InputNumber): 错误提示文本区域支持左侧对齐和输入框对齐两种方式， [issue#1229](https://github.com/Tencent/tdesign-vue/issues/1229)
- fix(InputNumber): 修复在输入数值不满足条件时，没有触发 onChange 事件问题
- fix(InputNumber): 修复计算过程中的精度问题
=> chore: sync feature into develop

package.json, src/select/optionGroup.tsx
- feat(Icon): 新增qq、wechat、wecom、relativity和pin-filled等图标
=> chore: fix classprefix

examples/select/demos/virtual-scroll.vue
[148](https://github.com/Tencent/tdesign/issues/148)
优化了部分select公共样式
【问题1】下拉菜单缺少描边。
【方案1】描边样式为：gray4/0.5/inside。
~~【问题2】多选选择器，选中态字体颜色不对。(问题不存在)~~
~~【【方案2】应为brand8-normal。~~
【问题3】分组选择器，分割线的margin和padding不对。
【方案3】间距为2。分割线的padding为2，8，2，8。
【问题4】分组选择器，下拉菜单中，【分组】的样式透明度不对。
【方案4】应为26%。
【问题5】大尺寸输入框padding不对。
【方案5】应为12。
【问题6】大/中尺寸输入框中字号不对。
【方案6】分别应为16、14。
【建议7】【不同尺寸的选择器】中，建议小尺寸的下拉菜单为240，即与输入框保持一致。
【问题8】下拉菜单中，选中项没有居中对齐。
【方案8】文字纵向需居中对齐。
~~【【问题9】自定义下拉选项选择器样式不对。（高度为用户自定义）~~
~~【【方案9】下拉菜单选项中，内容区上下padding应为3。~~
【问题10】自定义面板选择器，下拉菜单选中态的padding不对。
【方案10】选中态的padding为8，且状态为【fill】，而不是hug。
【问题11】自定义选中项选择器，输入框高度不对。
【方案11】应为32。
【问题12】大尺寸中下拉菜单中，选中态的padding不对。
【方案12】padding值为6，12，6，12。
- fix(select): 优化了部分样式
=> feat: optimize select styles

examples/select/demos/base.vue, examples/select/demos/collapsed.vue, examples/select/demos/creatable.vue, examples/select/demos/custom-options.vue, examples/select/demos/custom-selected.vue, examples/select/demos/disabled.vue, examples/select/demos/filterable.vue, examples/select/demos/group.vue, examples/select/demos/label-in-value.vue, examples/select/demos/max.vue, examples/select/demos/multiple.vue, examples/select/demos/noborder.vue, examples/select/demos/panel.vue, examples/select/demos/popup-props.vue, examples/select/demos/prefix.vue, examples/select/demos/remote-search.vue, examples/select/demos/size.vue, examples/select/demos/status.vue, examples/select/demos/virtual-scroll.vue, test/ssr/__snapshots__/ssr.test.js.snap, test/unit/select/__snapshots__/demo.test.js.snap
- chore: 更新select的示例代码 用space组件替换 减少重复代码 修复虚拟滚动代码示例
=> chore: update select demo

src/dropdown/dropdown-menu.tsx, src/tree/tree-item.tsx
- fix(tree): 修复expandOnClickNode下点击tree的label会触发checkbox选中的问题
- fix(dropdown): 修复控制台告警
=> fix(tree): expandOnClicknode conflict

src/tree/tree-item.tsx
=> fix: classname could be null or object

examples/config-provider/config-provider.md, site/docs/getting-started.md
- docs: 优化关于自动引入的使用说明
- docs: 新增关于修改全局组件前缀的使用方式
=> chore: update usage docs

CHANGELOG.md, package.json
=> chore: release 0.46.1

src/upload/dragger.tsx, src/upload/flow-list.tsx, src/upload/image.tsx, src/upload/single-file.tsx, src/upload/upload.tsx
- fix(upload): 修复`displayFileList` slot失效的问题
- fix(upload): 修复`theme`为`file`时，onRemove回调没有返回file的问题
- fix(upload): 修复`theme`为`file`，删除文案不可配置的问题
- feat(upload): `locale` API支持全部文案
=> fix(upload): fileListDisplay and remove params

examples/avatar/demos/adjust.vue, examples/avatar/demos/base.vue, examples/avatar/demos/group-cascading.vue, examples/avatar/demos/group-max.vue, examples/avatar/demos/group.vue, examples/avatar/demos/shape.vue, examples/avatar/demos/size.vue, test/ssr/__snapshots__/ssr.test.js.snap, test/unit/avatar/__snapshots__/demo.test.js.snap
https://github.com/Tencent/tdesign-vue/issues/1281
- chore: avatar 组件示例代码的 Space 组件优化
=> chore: update avatar demo

examples/grid/grid.en-US.md, examples/grid/grid.md, src/grid/col-props.ts, src/grid/row-props.ts, src/grid/row.tsx, src/grid/type.ts, test/ssr/__snapshots__/ssr.test.js.snap, test/unit/card/__snapshots__/demo.test.js.snap, test/unit/grid/__snapshots__/demo.test.js.snap, test/unit/skeleton/__snapshots__/demo.test.js.snap
关联子仓库: https://github.com/Tencent/tdesign-common/pull/758
- [x ] 日常 bug 修复
https://github.com/Tencent/tdesign-vue/issues/1297
- fix(Grid): `justify`和 `align` 同为 `center` 属性冲突问题
- feat(Grid): `align` 可选值新增 `start/end/center` 等
=>  feat: add new enum values of align for grid 

examples/config-provider/config-provider.md, examples/config-provider/demos/global.vue, site/docs/getting-started.md, site/docs/starter.md, test/ssr/__snapshots__/ssr.test.js.snap, test/unit/config-provider/__snapshots__/demo.test.js.snap
=> chore: update docs

examples/link/demos/base.vue, examples/link/demos/disabled.vue, examples/link/demos/hover.vue, examples/link/demos/icon.vue, examples/link/demos/size.vue, examples/link/demos/theme.vue, examples/link/demos/underline.vue, test/ssr/__snapshots__/ssr.test.js.snap, test/unit/link/__snapshots__/demo.test.js.snap
https://github.com/Tencent/tdesign-vue/issues/1281#DEMO
更新 `Link` 的示例代码，用 `space` 组件替换以减少重复代码
- chore(Link): 更新 `Link` 的示例代码，用 `space` 组件替换以减少重复代码
=> chore(link): update link demo

examples/table/demos/editable-cell.vue, src/table/primary-table.tsx
同步Vue3版本的修改
- fix(table): 修复了editableCellState表现与预期相反的问题
=> fix(table): 修复了editableCellState表现与预期相反的问题

examples/popup/demos/base.vue, examples/popup/demos/container.vue, examples/popup/demos/style.vue, examples/popup/demos/trigger-element.vue, examples/popup/demos/trigger.vue, examples/select/demos/noborder.vue, test/ssr/__snapshots__/ssr.test.js.snap, test/unit/popup/__snapshots__/demo.test.js.snap, test/unit/select/__snapshots__/demo.test.js.snap
- https://github.com/Tencent/tdesign-vue/issues/1378
- chore: 调整popup调整结构之后的demo
- chore: `select`新增无边框自适应宽度示例
=> chore: update popup demo

src/notification/notification.tsx
与Vue3版本中的Notification组件的表现保持一致。
鼠标移入时移除定时器，移出时重新添加定时器。
- feat(notification): 鼠标移入时不会关闭通知
=> feat(notification): 鼠标移入时不会关闭通知

src/alert/__tests__/__snapshots__/demo.test.js.snap, src/alert/_example/base.vue, src/alert/_example/close.vue, src/alert/_example/collapse.vue, src/alert/_example/icon.vue, src/alert/_example/operation.vue, src/alert/_example/title.vue, test/ssr/__snapshots__/ssr.test.js.snap
https://github.com/Tencent/tdesign-vue/issues/1281#DEMO
chore(Alert): 更新 Alert的示例代码，用 space 组件替换以减少重复代码
=> chore: update alert demo

src/date-picker/panel/RangePanel.tsx
- fix(`DatePicker`): 修复左右面板切换错位问题
=> fix: 修复左右面板切换错位问题

package.json
=> chore: 优化站点 tab 切换滚动条进度体验

src/calendar/__tests__/__snapshots__/demo.test.js.snap, src/config-provider/__tests__/__snapshots__/demo.test.js.snap, src/select/hooks/useSelectOptions.ts, src/select/index.ts, src/select/select.tsx, test/ssr/__snapshots__/ssr.test.js.snap
- fix(select): 去除组件注册时的 map props
=> fix(select): 去除组件注册时的 map props

src/input-number/index.ts
- fix(InputNumber): 修复string与number比较错误及其导致的分页组件样式异常的问题 [common#784](https://github.com/Tencent/tdesign-common/pull/784)
=> fix(input-number): string and number compare

TEST_GUIDE.md
=> docs: optimize test guide doc

src/upload/upload.tsx
- https://github.com/Tencent/tdesign-vue/issues/1397
- fix(Upload): 修复theme为`flow-list`时 remove事件file参数丢失的问题
=> fix(upload): flow-list remove params

src/select/select-panel.tsx
#1414 
- fix(select): 修复 creatable 模式下的 filter 能力
=> fix(select): 修复 creatable 模式下的 filter 能力

src/popup/popup.tsx
- fix(Popup): 修复overlayInnerClassName丢失的问题
=> feat(popup): add `overlayInnerClassName` prop

src/date-picker/DateRangePickerPanel.tsx
- fix(`DatePicker`): 修复 `cell-click` 事件 `partial` 字段错误
=> fix: 修复 cell-click partial 字段错误

src/message/__tests__/__snapshots__/demo.test.js.snap, src/message/_example/base.vue, src/message/_example/close-all.vue, src/message/_example/close.vue, src/message/_example/loading.vue, src/message/_example/placement.vue, src/message/_example/plugin.vue, src/message/_example/toggle.vue, test/ssr/__snapshots__/ssr.test.js.snap
- chore(message): 使用spac组件替换demo
=> chore: update message demo

src/table/hooks/useRowSelect.tsx
https://github.com/Tencent/tdesign-vue/issues/1377
- fix(table): 修复table列在设置type: multiple时，设置className不起作用
=> fix(table): 当列类型设置为multiple时,设置className不起作用 (#1377)

src/watermark/watermark.tsx
removable不生效，content不可动态修改
fix #1472
fix #1472
- fix(watermark): removable属性设置不生效，content不支持动态修改变化
=> fix(watermark): removable不生效，content不可动态修改

src/time-picker/__tests__/__snapshots__/demo.test.js.snap, src/time-picker/_example/base.vue, src/time-picker/_example/clearable.vue, src/time-picker/_example/disabled.vue, src/time-picker/_example/format.vue, src/time-picker/_example/hide-clear-button.vue, src/time-picker/_example/hm.vue, src/time-picker/_example/hms.vue, src/time-picker/_example/keyboard.vue, src/time-picker/_example/panel.vue, src/time-picker/_example/range.vue, src/time-picker/_example/show-steps.vue, src/time-picker/_example/step.vue, src/time-picker/_example/twelve-hour-meridian.vue, src/time-picker/_example/twelve-hour.vue, src/time-picker/panel/single-panel.tsx, test/ssr/__snapshots__/ssr.test.js.snap
- https://github.com/Tencent/tdesign-vue-next/issues/1012
- https://github.com/Tencent/tdesign-vue/issues/1281
- fix(TimePicker): 修复部分设备滚动边界的跳动异常 ([issue #1012](https://github.com/Tencent/tdesign-vue-next/issues/1012))
- chore: 使用space组件替换示例代码
=> fix(timepicker): scroll boundary

src/dialog/plugin.tsx
[#1417 ](https://github.com/Tencent/tdesign-vue/issues/1417)
- fix(dialog): 修复插件调用时丢失淡入动画问题
=> fix(dialog): 修复插件调用时丢失淡入动画问题

src/tree-select/_example/base.vue, src/tree-select/tree-select.tsx, src/tree/td-tree.tsx
- https://github.com/Tencent/tdesign-vue/issues/1458
- https://github.com/Tencent/tdesign-vue/issues/1450
- fix(Tree):  父节点disable时不允许选中但允许展开
- fix(TreeSelect): 修复数字类型的value时控制台报错的异常
- chore: tree-select增加disable示例
=> fix(tree): enable expand when disabled

site/docs/getting-started.md, src/input-number/_usage/props.json
- https://github.com/Tencent/tdesign-vue/issues/1463
- docs: 强化对vue版本的提醒
- docs: inputNumber的live demo增加largeNumber选项
=> chore: optimize docs and reminder

script/generate-usage/config.js, src/tree/_usage/index.vue
=> chore: 修复 tree live demo 问题

src/table/hooks/useColumnController.tsx
#1479 
- fix(table): 修复onColumnControllerVisibleChange的trigger参数不正确的问题
=> fix(table): 修复onColumnControllerVisibleChange的trigger参数不正确的问题

src/date-picker/DateRangePickerPanel.tsx
- fix(`DatePicker`): 修复 `cell-click` 返回日期错误
=> fix: 修复 cell-click 返回日期错误

site/src/components/page.vue
=> chore: 修复版本切换问题

.github/workflows/auto-release.yml
=> chore: fix release script security

src/date-picker/DateRangePicker.tsx, src/date-picker/DateRangePickerPanel.tsx, src/date-picker/hooks/useRange.ts
- feat(`DatePicker`): 支持二次更改时间选择器时可单次变更日期
=> feat: 支持二次更改时间选择器时可单次变更日期

src/time-picker/panel/single-panel.tsx
- fix(TimePicker): 修复往前点击时间时滚动异常的问题
=> fix(timepicker): click ahead time scroll to prev position

src/date-picker/DatePicker.tsx
- feat(`DatePicker`): 默认时间调整成 00:00:00
=> feat: 默认时间调整成 00:00:00

src/steps/__tests__/__snapshots__/demo.test.js.snap, src/steps/_example/vertical-no-sequence.vue, src/steps/_example/vertical-sequence.vue, test/ssr/__snapshots__/ssr.test.js.snap
https://github.com/Tencent/tdesign/issues/218
- fix(steps): 步骤条demo错误
=> fix: 修复steps步骤条demo

src/jumper/__tests__/index.test.js, src/jumper/props.ts
#1418 
- test(Jumper): 补充单元测试
- fix(jumper): 修复 tips props 类型缺失
=> test(Jumper): add test for jumper

package.json
=> fix: 修复默认导入引用文件缺失问题

src/pagination/__tests__/index.test.js, src/pagination/pagination.tsx
#1418 
搜代码，simpleClass 和 pageCountOption 这两个 没有用到。
- test(Pagination): 增加 pagination 单元测试
=> test: add test for pagination

src/table/base-table.tsx, src/table/hooks/useFixed.ts
- https://github.com/Tencent/tdesign-vue/issues/1437
- fix(Table): 修复数据变化时 分页吸底位置没有变化的问题
=> fix(table): recalculate affix position

src/time-picker/panel/single-panel.tsx
- https://github.com/Tencent/tdesign-vue-next/issues/1693
- fix(TimePicker): 修复部分场景滚动异常无法选中23:59:59的问题
=> fix(timepicker): scroll position on Windows

src/layout/__tests__/__snapshots__/demo.test.js.snap, src/layout/_example/base.vue, test/ssr/__snapshots__/ssr.test.js.snap
- https://github.com/Tencent/tdesign-vue/issues/1281
- chore: 使用Space组件替换layout示例
=> chore: update layout demo

script/generate-usage/config.js, site/site.config.mjs, src/components.ts, src/rate/__tests__/__snapshots__/demo.test.js.snap, src/rate/__tests__/demo.test.js, src/rate/_example/base.vue, src/rate/_example/custom.vue, src/rate/_example/icon.vue, src/rate/_example/size.vue, src/rate/_example/status.vue, src/rate/_example/texts.vue, src/rate/_usage/index.vue, src/rate/index.ts, src/rate/rate.tsx, src/rate/style/css.js, src/rate/style/index.js, src/time-picker/time-picker.tsx, test/ssr/__snapshots__/ssr.test.js.snap
=> feat(Rate): support rate component

src/affix/__tests__/index.test.js, src/affix/affix.tsx
#1437 
- fix(table): 初始化获取数据，吸底滚动条位置计算不正确问题
=> fix(table): 初始化获取数据，吸底滚动条位置计算不正确问题

src/collapse/__tests__/index.test.js, src/table/hooks/useFixed.ts
- fix(Table): 处理不存在分页吸底和滚动条吸底的表格控制台报错的问题
=> fix(table): optional affix ref

CHANGELOG.md, package.json
=> chore: release 0.48.1

src/swiper/swiper.tsx
close #1543 
- fix(swiper): 修复active类名问题
=> fix(swiper): 修复active类名问题

site/site.config.mjs, src/components.ts, src/hooks/useVModel.ts, src/image-viewer/_example/album.vue, src/image-viewer/_example/albumIcons.vue, src/image-viewer/_example/base.vue, src/image-viewer/_example/block.vue, src/image-viewer/_example/button.vue, src/image-viewer/_example/error.vue, src/image-viewer/_example/modeless.vue, src/image-viewer/_example/multiple.vue, src/image-viewer/base/ImageItem.tsx, src/image-viewer/base/ImageModalIcon.tsx, src/image-viewer/base/ImageViewerModal.tsx, src/image-viewer/base/ImageViewerUtils.tsx, src/image-viewer/const.ts, src/image-viewer/hooks.ts, src/image-viewer/image-viewer.en-US.md, src/image-viewer/image-viewer.md, src/image-viewer/image-viewer.tsx, src/image-viewer/index.ts, src/image-viewer/props.ts, src/image-viewer/style/css.js, src/image-viewer/style/index.js, src/image-viewer/type.ts, src/image-viewer/utils.ts
https://github.com/Tencent/tdesign/issues/227
- feat(ImageViewer): 新增 `image-viewer` 组件
=> feat(新增image-viewer): 新增image-viewer

src/select/select-panel.tsx, src/select/select.tsx
…条目可通过键盘选择
- fix(select): 修复可创建新条目场景下回车选择错误的问题(#1563 )
- fix(select): 修复创建条目和选中已有条目同时触发的问题
- fix(select): 完善键盘事件, 创建的新条目可通过键盘选择
=> fix(select): 键盘事件问题修复，逻辑完善

src/date-picker/DatePicker.tsx, src/date-picker/DateRangePicker.tsx, src/date-picker/hooks/useSingle.ts
- fix(`DatePicker`): 修复手动清空输入框关闭弹窗没有重置数据问题
=> fix: 优化 datepicker 输入事件交互

src/swiper/__tests__/__snapshots__/demo.test.js.snap, src/swiper/_example/size.vue, test/ssr/__snapshots__/ssr.test.js.snap
无
官方demo显示异常
修复后
- fix(swiper): 修复swiper组件的demo显示不正确问题
=> fix(swiper): 修复swiper组件的demo显示不正确问题

src/time-picker/time-picker.tsx, src/time-picker/time-range-picker.tsx
https://github.com/Tencent/tdesign/issues/224
- style(time-picker): 调整time-pick样式
=> style(TimePicker): 调整TimePicker边距

src/select/__tests__/__snapshots__/demo.test.js.snap, src/select/_example/popup-props.vue, test/ssr/__snapshots__/ssr.test.js.snap
close #1573 
关联 PR: https://github.com/Tencent/tdesign-common/pull/876
=> docs(select): update custom width demo 

CHANGELOG.md, package.json
=> chore: release 0.48.4

src/upload/constants.ts, src/upload/interface.ts, src/upload/themes/custom-file.tsx, src/upload/themes/dragger-file.tsx, src/upload/themes/image-card.tsx, src/upload/themes/multiple-flow-list.tsx, src/upload/themes/normal-file.tsx
https://github.com/Tencent/tdesign-vue-next/pull/1775
- fix(Upload): 修复 `upload` 导出预期外的变量导致组件注册时出现告警
=> fix: upload export warn

src/date-picker/DatePicker.tsx, src/date-picker/DateRangePicker.tsx, src/date-picker/date-picker.en-US.md, src/date-picker/date-picker.md, src/date-picker/date-range-picker-props.ts, src/date-picker/hooks/useRange.ts, src/date-picker/hooks/useSingle.ts, src/date-picker/props.ts, src/date-picker/type.ts
=> feat: support valueType

src/select/option.tsx, src/select/select.tsx
- fix(select): select value 参数类型检测报错修复; 增加 value 传值异常流的控制台提示
=> fix(select): select value 参数类型检测报错修复; 增加 value 传值异常流的控制台提示

src/form/__tests__/__snapshots__/demo.test.js.snap, src/image-viewer/base/Container.tsx, src/image-viewer/base/ImageViewerModal.tsx, src/image-viewer/image-viewer.tsx, src/upload/__tests__/__snapshots__/demo.test.js.snap, test/ssr/__snapshots__/ssr.test.js.snap
- fix(ImageViewer): 移除包裹在trigger上的额外元素
=> fix(image-viewer): 移除额外的根元素

src/dropdown/_example/slot.vue, src/dropdown/hooks/useDropdownOptions.ts
=> chore: fix dropdown refactor issue

src/dropdown/dropdown-menu.tsx
=> fix(dropdown): no children item class

src/date-picker/DateRangePicker.tsx
=> fix(daterangepicker): 修复范围选择器面板年份异常

src/input/input.tsx
https://codesandbox.io/s/tdesign-vue-demo-forked-xne31n?file=/src/demo.vue
当配置有format时， 初始化或者赋值时，input展示数据未格式化。只有失焦时才格式化。
codesandbox示例：
赋值时：
希望：
- fix(input): 初始化或者赋值时，format不生效
=> fix(input): 初始化或者赋值时，format不生效

src/date-picker/DateRangePicker.tsx, src/date-picker/DateRangePickerPanel.tsx, src/date-picker/hooks/useRange.ts
=> fix: 修复 range 数据格式化异常问题

src/upload/hooks/useUpload.ts
- fix(upload): 只有多个上传请求同时触发时才需 onOneFileFail
=> fix(upload): 只有多个上传请求同时触发时才需 onOneFileFail

CHANGELOG.md
=> docs: optimize 0.49.0 changelog

package.json
Co-authored-by: @yilaierwang 
- feat: 主题生成器新增阴影配置 co-authored @yilaierwang
=> feat: add boxshadow theme generator

test/ssr/__snapshots__/ssr.test.js.snap
=> chore: update snapshot for jest

src/upload/_example/image.vue, src/upload/hooks/useUpload.ts, src/upload/themes/dragger-file.tsx, src/upload/themes/image-card.tsx, src/upload/themes/multiple-flow-list.tsx, src/upload/themes/normal-file.tsx, test/ssr/__snapshots__/ssr.test.js.snap
- fix(Upload): 修复 `name` 无效问题
- fix(Upload): 图片上传，自定义上传方法不支持图片回显问题
- feat(Upload): 多图片上传，图片文件名支持 `abridgeName`
=> [Upload] some features and bugs

src/calendar/__tests__/__snapshots__/demo.test.js.snap, src/calendar/__tests__/__snapshots__/index.test.js.snap, src/collapse/__tests__/__snapshots__/demo.test.js.snap, src/collapse/__tests__/index.test.js, src/collapse/collapse-panel.tsx, src/image-viewer/base/ImageItem.tsx, src/image-viewer/image-viewer.tsx, src/tabs/tab-nav-item.tsx, src/utils/helper.ts, test/ssr/__snapshots__/ssr.test.js.snap
问题1：Collapse折叠面板点击标题没有展开
解决方法：headerRightContent插槽点击禁止冒泡
问题2：Tabs切换时会导致内容的document点击事件触发，下面示例为“表格列设置了默认为编辑态，在tabs中切换到表格时，编辑态就会失效”
demo: https://codesandbox.io/s/tdesign-vue-demo-forked-q08idi?file=/src/demo.vue
解决方案：禁止tabs点击切换时的冒泡事件
问题3：ImageViewer组件用了很多行内的transform属性且没有加前缀，在一些低版本的浏览器不兼容，例如IE
解决方案：transform兼容多个前缀赋值
- fix(Collapse): 修复点击标题没有触发折叠功能的问题
- fix(Tabs): 修复tabs切换时会导致表单初始化聚焦失效问题
=> Image、Tabs、Collapse的bug修复和优化

src/select/hooks/useSelectOptions.ts
- fix(select): 添加 options 参数监听, 优化部分场景下 option 更新逻辑 (fixed #1681 )
=> fix(select): 添加 options 参数监听, 优化部分场景下 option 更新逻辑

src/date-picker/DateRangePickerPanel.tsx
#1580 
1. 修复 `t-date-picker__cell--active-start` 和 `t-date-picker__cell--active-end` 在第二次操作时错序的问题（即 `t-date-picker__cell--active-end` 被添加到了选中的最小日期上）
2. 修复 hover 已选择日期动画导致 cell 闪烁问题（见 issue 视频）
3. 修复伪元素模拟背景色，在部分情况下出现断层问题（见 issue 截图）
=> fix(date-picker): 边缘闪烁和部分情况下背景色错误问题

src/dialog/__tests__/__snapshots__/demo.test.js.snap, src/dialog/dialog.tsx
[#1452](https://github.com/Tencent/tdesign-vue-next/issues/1452)
- feat(dialog):  优化非模态对话框拖拽事件鼠标表现 
=> fix(dialog): 非模态对话框 优化拖拽事件鼠标表现 

src/config-provider/__tests__/__snapshots__/demo.test.js.snap, src/dialog/__tests__/__snapshots__/demo.test.js.snap, src/dialog/dialog.tsx, src/space/space.tsx, src/textarea/textarea.tsx
- https://github.com/Tencent/tdesign-vue/issues/1656
- https://github.com/Tencent/tdesign-vue/issues/1673
- https://github.com/Tencent/tdesign-vue/issues/1679
- fix(Textarea): 修复禁用状态字数限制区域的样式问题
- fix(Space): 修复子节点为空的报错
- fix(Dialog): 修复theme为非default时body节点类名的问题
=> fix: space empty slot and textarea limit field style

src/select/optionGroup.tsx, src/select/select.tsx
- fix(Select): 修复单选清除失效的问题
- fix(Select): 修复分组样式问题
=> fix(Select): clearable and group style

CHANGELOG.md, package.json
=> feat: release 0.49.2

src/tooltip/__tests__/index.test.js
- test(tooltip): `Tooltip`新增测试用例
=> test(tooltip): tooltip 新增测试用例

src/popup/__tests__/index.test.js
=> test(popup): 新增`Popup`单元测试

.eslintignore, src/date-picker/hooks/useRange.ts, src/date-picker/hooks/useSingle.ts
- fix(Datepicker): 修复 `popupProps.onVisibleChange` 方法不能正常触发的问题
=> fix: datepicker popupProps onVisibleChange

src/textarea/props.ts, src/textarea/type.ts
- #1692 
- fix(textarea):  修复`status`的类型问题
=> fix(textarea): 补充类型检查

src/dropdown/dropdown.tsx
- fix(Dropdown): 修复下拉菜单可视无法完全受控的问题
=> fix(dropdown): visible controlled

src/checkbox/group.tsx
- https://github.com/Tencent/tdesign-vue/issues/1705
- fix(Checkbox): 修复Checkbox的options 参数属性变化时未重新渲染的问题
=> fix(checkbox): rerender when options change

src/transfer/components/transfer-list.tsx
- #1615 
- fix(Transfer): 修复带分页的穿梭框两侧全量勾选操作的错误
=> fix(transfer): 带分页的穿梭框左边全选添加至右边，右边在全选勾选回去报错

src/config-provider/config-provider.tsx
#1709 
- fix(config-provider): 直接包裹router-view控制台报错
=> fix(config-provider): 直接包裹router-view控制台报错

src/time-picker/__tests__/index.test.jsx
- https://github.com/Tencent/tdesign-vue/issues/1418
- chore: 补充`TimePicker` 测试用例
=> chore: add timepicker unit test

src/select/option.tsx, src/select/select-panel.tsx, src/select/select.tsx, src/select/util.ts
- fix(select): 修复创建项目在已有选项中存在时重复显示问题
- fix(select): 修复多选时待创建选项显示样式问题
- fix(select): 优化键盘事件的逻辑
=> fix(select): 修复与优化创建项目时的逻辑

src/time-picker/panel/props.ts
- fix(TimePicker): 修复panel demo滚动问题
=> chore: showpanel default value

src/form/form-item-props.ts
- fix(Form): 修复0.49.4版本表单检验异常的问题
=> fix(Form): validate message

src/collapse/_example/mutex.vue, src/collapse/_example/other.vue, src/collapse/collapse-panel.tsx, src/collapse/collapse.tsx
- https://github.com/Tencent/tdesign-vue/issues/1752
- fix(Collapse): 修复动态设置`collapse-panel`时panel展示异常的问题
=> fix(Collapse): fix dynamic panel

CHANGELOG.md, package.json
=> chore: release 0.49.5

CHANGELOG.md, package.json
=> chore: release 0.49.6

src/select/_example/filterable.vue, src/select/select-panel.tsx
- fix(select): 搜索修复模糊大小写 (fixed: #1786)
=> fix(select): 搜索修复模糊大小写

src/image-viewer/__tests__/index.test.jsx, src/image-viewer/base/ImageViewerModal.tsx, src/image-viewer/image-viewer.tsx
- fix(image-viewer): 修复`image-viewer`的部分样式问题
=> feat: 修复 image-viewer 样式问题

src/textarea/props.ts
=> fix(textarea): fix stats props

src/date-picker/panel/RangePanel.tsx, src/date-picker/panel/SinglePanel.tsx
- fix(DatePicker): 修复disableDate 动态调整失效的问题
=> fix: 修复DatePicker disableDate 动态调整失效

src/date-picker/base/Table.tsx
=> fix: 修复周选择器高亮错误问题

src/input-number/_example/center.vue, src/input-number/input-number.en-US.md, src/input-number/input-number.md, src/input-number/props.ts, src/input-number/type.ts, src/input-number/useInputNumber.tsx
- https://github.com/Tencent/tdesign-vue/issues/1815
- https://github.com/Tencent/tdesign-vue/issues/1409
- feat(InputNumber): 支持 `allowInputOverLimit`，用于设置是否允许输入数字超过 `max` `min` 范围的值
- fix(InputNumber): 修复删除数字时数据类型会从 number 变为 string 问题
=> feat(input-number): support allow-input-over-limit

src/select-input/select-input.tsx, src/select/select.tsx
- https://github.com/Tencent/tdesign-vue/issues/1802
- feat(SelectInput): 支持`multiple`和`single`模式切换，适用于动态表单或低码平台场景
=> fix(SelectInput): support switch multiple type

src/tabs/tabs.tsx
#1696 
onRemoveTab方法中触发panel的onRemove方法，这里造成循环调用。 list方式在使用时，在list item中定义onRemove方法，这里可以去掉
- fix(tabs): list定义的tabs删除时，remove方法循环调用
=> fix(tabs): list定义的tabs删除时，remove方法循环调用

src/select/select.tsx
- feat(Switch): 优化`Switch`样式 区分打开与关闭按钮大小 @Wen1kang
- docs: 更新主题配置的文档描述 https://github.com/Tencent/tdesign-common/pull/1034
=> chore: update common and add changelog

src/table/editable-cell.tsx
- fix(Table): 可编辑行，修复因没有监听数据变化，出现的校验不通过问题，[issue#1822](https://github.com/Tencent/tdesign-vue/issues/1822)
https://user-images.githubusercontent.com/11605702/203541752-305d5ffd-5d3d-48f9-923a-0d2a63e4edf1.mov
=> fix(table): editable-cell can not watch data change

global.d.ts, tsconfig.json
=> chore: add global.d.ts for solar component tips

src/dialog/dialog.en-US.md, src/dialog/dialog.md, src/dialog/props.ts, src/dialog/type.ts, src/drawer/drawer.en-US.md, src/drawer/drawer.md, src/drawer/type.ts, src/message/message.en-US.md, src/message/message.md, src/message/props.ts, src/message/type.ts, src/notification/notification.en-US.md, src/notification/notification.md, src/notification/props.ts, src/notification/type.ts
- fix(Drawer): 修复 `closeOnOverlayClick` 存在默认值导致全局配置失效问题
- docs: 更新 Drawer/Message/Notification/Dialog 等组件文档
=> 更新 Drawer/Message/Notification/Dialog 等组件文档

src/auto-complete/_example/base.vue, src/auto-complete/auto-complete.tsx, src/auto-complete/option-list.tsx
- fix(AutoComplete): 支持使用 `triggerElement` 自定义触发元素
=> fix(auto-complete): support triggerElement

src/dialog/dialog.tsx, test/snap/__snapshots__/csr.test.js.snap
- fix(Dialog): 修复 destroyOnClose 设置后关闭弹窗无动画效果问题 
=> fix(dialog): 修复 destroyOnClose 设置后关闭弹窗无动画效果问题 && 调整 body 锁定逻辑

src/calendar/__tests__/__snapshots__/index.test.jsx.snap, src/calendar/_example/card.vue, src/calendar/_example/cell-append.vue, src/calendar/_example/cell.vue, src/calendar/calendar.tsx
- https://github.com/Tencent/tdesign-vue/issues/1854
- fix(Menu): 修复二级菜单子菜单纵向左边距丢失的问题
- feat(Calendar): 卡片样式菜单操作栏样式调整
=> feat(calendar): adjust card calendar panel size

CHANGELOG.md, package.json, src/tree/hooks/style/css.js, src/tree/hooks/style/index.js
=> chore: release 0.51.1

src/dialog/dialog.tsx, src/image-viewer/__tests__/index.test.jsx, src/image-viewer/base/Container.tsx
=> fix: 修复image-viewer 移除动画缺失问题

src/textarea/textarea.tsx
-  #1862
- fix(Textarea): 修复多行文本autofocus失效的问题
=> fix(textarea): fix autofoucs invalid

src/input-number/_example/center.vue, src/input-number/input-number.en-US.md, src/input-number/input-number.md, src/input-number/props.ts, src/input-number/type.ts, src/input-number/useInputNumber.tsx
- fix(InputNumber): 无法输入小数点后面的第一位数字 `0`，[tdesign-vue-next#2103](https://github.com/Tencent/tdesign-vue-next/issues/2103)
- fix(InputNumber): 修复无法使用清空按钮清除输入数字问题，[issue#1855](https://github.com/Tencent/tdesign-vue/issues/1855)
=> fix(input-number): clear number on clearIcon click

src/dialog/dialog.tsx, src/drawer/drawer.tsx, src/utils/dom.ts
=> fix(dialog): 修复滚动条判断问题

src/tree-select/tree-select.tsx
=> fix(tree-select): fix label dispaly error

src/select-input/select-input.tsx, src/select/select.tsx
- fix(selectinput): 修复 popup 与包裹元素导出 ref 重名的问题
=> fix(selectinput): 修复 popup 与包裹元素导出 ref 重名的问题

CHANGELOG.md, package.json
=> chore: release 0.52.1

src/space/__tests__/index.test.jsx, src/space/space.tsx
修复插槽无效
- #1921 
- fix(space): 修复`separator` slot无效的问题
=> fix(space): fix slot invalid

src/date-picker/DateRangePicker.tsx, src/date-picker/hooks/useRangeValue.ts
- fix(Datepicker): 修复右侧面板月份展示错误问题
=> fix(datepicker): 修复右侧面板月份展示错误问题

src/loading/plugin.tsx
https://github.com/Tencent/tdesign-vue/issues/1918
- fix(loading): 修复LoadingPlugin.hide多次调用后报错
=> fix(loading): 修复LoadingPlugin.hide多次调用报错的问题

src/date-picker/DateRangePicker.tsx, src/range-input/range-input.tsx
=> fix: 修复datepicker tips样式问题

src/dropdown/dropdown-menu.tsx, src/select/select-panel.tsx
- https://github.com/Tencent/tdesign-vue/issues/1919
- https://github.com/Tencent/tdesign-vue/issues/1906
- fix(Dropdown): 修复超长下拉菜单子菜单位置异常的问题
- fix(Select): 修复虚拟滚动未关闭下拉框切换页面导致告警的问题
=> fix(dropdown): overflow children position

src/date-picker/hooks/useRange.ts, src/date-picker/hooks/useSingle.ts
=> fix: datepicker 兼容传入空字符串

src/range-input/range-input.tsx
- https://github.com/Tencent/tdesign-vue/issues/1892
- fix(timepicker): 修复清空`rangepicker`返回值异常的问题
=> fix(timepicker): fix onclear value

src/input/input.tsx
- https://github.com/Tencent/tdesign-vue/issues/1912
- fix(Input): 修复Input文字长度省略异常的问题
=> fix(input): fix input width

src/drawer/drawer.tsx
=> fix: 修复 drawer 默认 visible 时内容不展示问题

src/select/_example/virtual-scroll.vue, src/select/hooks/useSelectOptions.ts, src/select/select.tsx
- fix(select): 提升部分情况下组件内部 options 处理的性能
=> fix(select): 内部 option 处理逻辑优化

package.json, src/config-provider/config-receiver.ts, src/config-provider/type.ts, src/form/form-item.tsx, src/hooks/useGlobalIcon.ts, src/popconfirm/popconfirm.tsx
=> chore: add icon global config type from icon package

src/tree-select/_example/base.vue, src/tree-select/tree-select.tsx
- https://github.com/Tencent/tdesign-vue/issues/1929
- feat(tree-select): `onVisibleChange`事件增加回调参数
=> feat(tree-select): add context param when pick value

site/src/components/page.vue
=> chore: fix version choice

src/date-picker/base/Header.tsx
- fix(DatePicker): 修复年份选择器区间展示错误
=> fix(date-picker): 修复年份选择器区间错误

src/input/input.tsx, src/select/_example/panel.vue
- https://github.com/Tencent/tdesign-vue/issues/1839
修复效果见此示例代码
- fix(Input): 修复光标移动至中间输入等部分场景下Input光标位置异常的问题
=> fix(Input): fix input cursor position in popup

src/tabs/_example/combination.vue, src/tabs/tab-nav.tsx
- https://github.com/Tencent/tdesign-vue/issues/1828
- feat(Tabs): 新增初始化时选中选项溢出自动滚动到具体位置的能力
=> feat(tabs): scroll to correct position when overflow on mounted

src/select/hooks/useSelectOptions.ts
- fix(select): 调整 select 标记字段位置
=> fix(select): 调整 select 标记字段位置

src/form/form-item.tsx
- fix(Form): 表单校验，不仅需要监听 value 变化，还需要监听 `name` 和 `rules` 变化，[issue#1942](https://github.com/Tencent/tdesign-vue/issues/1942)
=> fix(Form): validate watch name and rules

src/table/hooks/useFixed.ts
https://github.com/Tencent/tdesign-vue/issues/1978
添加空值判断
修复 `table` 特定情况下报错的问题
=> fix(table): 某些情况colInfo不存在导致赋值报错

src/select/_example/virtual-scroll.vue, src/select/hooks/useSelectOptions.ts
- fix(select): 修复 option slots 部分情况下异常渲染更新的问题
=> fix(select): 修复 option slots 部分情况下异常渲染更新的问题

src/tag/tag.tsx
https://github.com/Tencent/tdesign-vue/issues/1991
- fix(tag): Tag标签disabled 隐藏close icon
=> fix(tag): Tag标签disabled 隐藏close icon

src/input/input.tsx
https://github.com/Tencent/tdesign-vue/issues/1946
- fix(Input): 处理在 clear 事件中无法获取到最新 value 问题
=> fix(input): value in clear event doesn't change after clear

src/date-picker/DateRangePicker.tsx, src/date-picker/hooks/useRange.ts, src/date-picker/hooks/useSingle.ts
=> fix: 修复 datepicker 月份切换问题

src/hooks/useDefaultValue.ts, src/select-input/useOverlayInnerStyle.ts
https://github.com/Tencent/tdesign-vue/issues/2004
- fix(SelectInput): 修复下拉弹窗状态未改变时，重复触发 `onPopupVisibleChange` 事件的问题
=> [WIP]Fix/select input popupvisible

src/hooks/useDefaultValue.ts, src/select-input/useOverlayInnerStyle.ts
Reverts Tencent/tdesign-vue#2015
=> Revert "[WIP]Fix/select input popupvisible"

site/plugin-tdoc/md-to-vue.js
=> docs: 优化最后更新日期展示

src/popup/container.tsx
- feat(popup): remove extra div
=> feat(popup): remove extra div

src/image/image.tsx
link [#2259](https://github.com/Tencent/tdesign-vue-next/pull/2259)
同步 tdesign-vue-next 的修改
- fix(image): 修复动态修改src值图片无法显示问题
=> fix(image): 修复动态修改src值图片无法显示问题

src/hooks/useResizeObserver.ts, src/table/editable-cell.tsx
- fix(Table): 修复可编辑单元格无法退出问题
- refactor: update useResizeObserver
=> [Table] fix editable-cell can not exit

src/color-picker/panel/index.tsx
Before
https://user-images.githubusercontent.com/26377630/215314601-d16b1370-a22c-46f5-8a6a-b0a242cd077a.mp4
After
https://user-images.githubusercontent.com/26377630/215314608-c37c3d75-7ac3-4dbf-8fa1-c678fd701585.mp4
- feat(ColorPicker): 切换单色-渐变模式时触发色值及onChange变化
=> feat(colorpicker): trigger value change when toggle color mode

src/tree-select/tree-select.tsx, src/tree/hooks/useItemEvents.ts, src/tree/hooks/useTreeItem.tsx
- https://github.com/Tencent/tdesign-vue/issues/1989
- https://github.com/Tencent/tdesign-vue/issues/1958
- fix(TreeSelect): 修复TreeSelect组件未失焦时触发blur事件的问题
- fix(TreeSelect): 修复搜索选中选项后保留搜索关键词的问题
- fix(TreeSelect): 修复搜索状态下无命中关键词控制台报错的问题
- fix(Tree): 修复禁用节点文字颜色过淡的问题 
=> fix(tree-select): prevent trigger onBlur when click folder icon

src/table/hooks/useSorter.tsx
- fix(Table): 本地数据排序，异步获取数据，修复取消排序时，清空数据问题
=> [Table] fix async data cancel sort

CHANGELOG.md, package.json
=> chore: release 1.0.7

src/tree-select/tree-select.tsx
- https://github.com/Tencent/tdesign-vue/issues/2081
- feat(TreeSelect): 支持`tips`和`status` API
=> feat(treeselect): support tips and status

src/loading/loading.tsx
- fix(loading): 加载组件包裹元素时，无法显示内容问题
=> fix(loading): can not show content

CHANGELOG.md, package.json
=> chore: release 1.0.8

src/table/hooks/useFixed.ts
https://github.com/Tencent/tdesign-vue/issues/2089
- fix(Table): 固定列column报错 ...
=> fix: newColumnsMap 和 columns数据不一致导致的报错

package.json
Reverts Tencent/tdesign-vue#2078
=> Revert "chore(deps-dev): bump vitest from 0.26.3 to 0.28.3"

src/dialog/dialog.tsx
- https://github.com/Tencent/tdesign-vue/issues/2086
- fix(dialog): 修复closeOnClickOverlay为false时，overlay-click事件未触发问题
=> fix(dialog): overlay-click not emit

src/image-viewer/base/ImageItem.tsx, src/image-viewer/base/ImageViewerUtils.tsx, src/image/image.tsx
- #2063 
- #2064 
- fix(ImageViewer): 支持 errorText mirrorTipText originalSizeTipText rotateTipText 字段配置
- fix(Image): 支持 errorText loadingText 字段全局配置
=> [image、imageViewer] 支持configProvider配置

src/config-provider/useConfig.tsx, src/form/_example/validator.vue, src/form/form-item.tsx, src/image/_example/extra-always.vue, src/image/_example/extra-hover.vue, src/image/_example/gallery-cover.vue, src/image/_example/lazy-single.vue, src/image/image.tsx, src/input-number/useInputNumber.tsx
https://github.com/Tencent/tdesign-vue-next/issues/2304
- fix(InputNumber): 修复小数点后第二个数字若为 0 无法输入问题，[issue#2304](https://github.com/Tencent/tdesign-vue-next/issues/2304)
- fix(Form): 修复其他表单项变化，触发 `<form-item :rules="[]" />` 校验问题，[issues#2100](https://github.com/Tencent/tdesign-vue/issues/2100)
- docs(Image): 修复示例代码问题
- [] 本条 PR 不需要纳入 Changelog
=> image demos & input-number double 00 && form validate

src/form/_example/base.vue, src/form/form-item.tsx
- https://github.com/Tencent/tdesign-vue/issues/2044
- fix(Form): 表单校验问题，修复数组类表单项会因其他项变化引起自身校验问题
=> fix(form): array value would be validated on other form-item changed

src/color-picker/color-picker.tsx
=> fix: fix bug #2111

CHANGELOG.md, package.json
=> chore: release 1.1.1

src/list/__tests__/index.test.jsx, src/list/list-item-props.ts, src/list/list-item.tsx, src/list/list.en-US.md, src/list/list.md, src/list/type.ts
listItem support onClick event
xx~#1916
=> feat(list): listItem support onClick event

src/drawer/drawer.tsx
=> fix(`Drawer`): 修复组件销毁时未正常移除锁定样式

helper/attributes.json, helper/tags.json, helper/web-types.json
=> chore: update all helper tips

src/dialog/_example/modal.vue
=> fix: 模态与非模态类对话框示例优化

package.json
=> fix: babel lint error in ci

src/timeline/__tests__/__snapshots__/vitest-timeline.test.jsx.snap, src/timeline/__tests__/vitest-timeline.test.jsx, src/timeline/timeline-item.tsx
- fix(Timeline): 修复自定义图标未能显示在正中间的问题
https://tdesign.tencent.com/vue/components/timeline#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%8A%82%E7%82%B9
=> fix(timeline): icon is not located in center

src/table/hooks/useClassName.ts
=> fix(table): 检查 navigator 避免ssr报错

src/dialog/dialog.tsx, src/drawer/drawer.tsx, src/table/hooks/useFixed.ts
=> fix: 修复 drawer、dialog 滚动条检测问题

src/tree/tree.en-US.md, src/tree/tree.md
=> docs: TreeNodeFunctions wording

src/transfer/_example/tree.vue
=> fix(transfer): use with tree demo

src/config-provider/config-provider.tsx, src/dialog/dialog.tsx, src/dialog/plugin.tsx
- https://github.com/Tencent/tdesign-vue/issues/1823
- https://github.com/Tencent/tdesign-vue/issues/2188
- feat(Dialog): 支持插件调用形式接收来自ConfigProvider的配置
- fix(Dialog): 修复全局配置confirmBtnTheme属性失效的问题
=> feat(dialog): config-provider affect plugin

src/index.ts
=> feat: export common type

src/date-picker/hooks/useRange.ts, src/date-picker/hooks/useSingleValue.ts
- fix(DatePicker): 修复月份为 0 时展示当前月份问题
=> fix(DatePicker): 修复月份为 0 时展示当前月份问题

src/badge/_example/base.vue, src/badge/badge.tsx
- [tdesign-vue-next/issues/2502](https://github.com/Tencent/tdesign-vue-next/issues/2502)
- fix(Badge): 修复徽标错误行为
=> fix(Badge): 修复徽标错误行为

src/pagination/pagination.tsx
- fix(Pagination): 修复某些情况下mouseover导致按钮闪烁
=> fix(Pagination): 修复某些情况下mouseover导致按钮闪烁

src/tree-select/tree-select.tsx
- https://github.com/Tencent/tdesign-vue/issues/2221
- fix(TreeSelect): 处理 label 不起作用问题
=> fix: label not working

src/select-input/useSingle.tsx, src/tree-select/_example/base.vue
- fix(SelectInput): 修复SelectInput valueDisplay和label插槽位置错误的问题
=> fix(SelectInput): value display label order

src/date-picker/_example/base.vue, src/date-picker/_example/date-presets-alt.vue, src/date-picker/_example/date-range.vue, src/date-picker/date-picker.en-US.md, src/date-picker/date-picker.md, src/date-picker/date-range-picker-props.ts, src/date-picker/hooks/useRange.ts, src/date-picker/hooks/useSingle.ts, src/date-picker/panel/PanelContent.tsx, src/date-picker/props.ts, src/date-picker/type.ts, src/range-input/props.ts, src/range-input/range-input-popup-props.ts, src/range-input/range-input.en-US.md, src/range-input/range-input.md, src/range-input/type.ts
- feat(`DatePicker`): 支持 `size` 属性
- fix(`DatePicker`): 修复时间格式化问题
- fix(`DatePicker`): 修复 `status` 数据类型报错
=> feat(datepicker): 支持 size 属性 & 修复时间格式化问题 & 修复控制台报错

src/form/form-item.tsx
- fix(Form): 修复未设置 label 属性时，仍渲染多余对应节点的问题
=> fix(form): 修复渲染多余 label 节点问题

src/popup/popup.tsx, src/tree-select/__tests__/vitest-tree-select.test.jsx
#2245, #2137
- fix(popup): 修复需多次点击才能关闭的问题
=> fix(popup): fix trigger timing issue (#2245, #2137)

src/hooks/useLazyLoad.ts, src/select/option.tsx, src/table/tr.tsx, src/tree/hooks/useTreeItem.tsx
- fix(table): table lazyload reset bug
=> fix(table): table lazyload reset bug

src/color-picker/_example/panel.vue, src/color-picker/color-picker.en-US.md, src/color-picker/color-picker.md, src/color-picker/panel/index.tsx, src/color-picker/panel/linear-gradient.tsx, src/color-picker/props.ts, src/color-picker/type.ts, src/dropdown/dropdown.tsx, src/time-picker/_example/hms.vue, src/time-picker/panel/single-panel.tsx, src/time-picker/panel/time-picker-panel.tsx, src/time-picker/props.ts, src/time-picker/time-picker.en-US.md, src/time-picker/time-picker.md, src/time-picker/time-picker.tsx, src/time-picker/time-range-picker-props.ts, src/time-picker/time-range-picker.tsx, src/time-picker/type.ts
- https://github.com/Tencent/tdesign-vue/issues/2139
- https://github.com/Tencent/tdesign-vue-next/issues/2595
- feat(ColorPicker): 新增`enableMultipleGradient`, 支持渐变色只存在起始和结束梯度
- feat(TimePicker): 新增`size` API , 用于控制时间输入框大小，`pick`事件增加`context`回调参数
- feat(Dropdown): 支持透传popupProps的`on-visible-change`的写法
=> feat(color-picker): add enableMultipleGradient api

src/common.ts, src/table/_example/filter-controlled.vue, src/table/hooks/useColumnResize.ts, src/table/hooks/useFilter.tsx, src/table/table.en-US.md, src/table/table.md, src/table/type.ts
- fix(Table): 修复 SSR 环境 document 报错问题
- feat(Table): 支持设置 `filterRow=null` 隐藏过滤结果行
- docs(Table): 更新组件实例方法文档
=> [Table] support hide filter results row with filterRow=null 

src/date-picker/DatePicker.tsx, src/date-picker/DateRangePicker.tsx, src/date-picker/hooks/useRangeValue.ts, src/date-picker/hooks/useSingle.ts, src/date-picker/hooks/useSingleValue.ts, src/time-picker/panel/props.ts, src/time-picker/panel/time-picker-panel.tsx
- https://github.com/Tencent/tdesign-vue/issues/2249
- fix(DatePicker): 修复format为12小时制时功能异常的问题
=> fix(date-picker): fix 12 hour format

src/popup/popup.tsx
- fix(popup): 修复popper元素在快速操作情况下可能为空的情况
=> fix(popup): popper ele could be null

src/table/base-table.tsx
https://github.com/Tencent/tdesign-vue/pull/2275
上述pr的补充
- fix(table): 修复IE下headerAffixedTop滚动条没有隐藏的问题
=> fix(table): 修复ie滚动条判断修正之后，affixHeader的外层高度需要减去滚动条的宽度

src/input-adornment/input-adornment.tsx
- #2255 
- fix(inputAdornment): 修复 slot 方式 class 名 缺失问题
=> fix: fix inputAdornment slot class bug

src/date-picker/DatePicker.tsx
#2268
- fix(date-picker): 修复日期输入框值不更新问题
=> fix(date-picker): the input value is not updated

site/docs/getting-started.md
=> chore: update getting started docs

src/locale/ar_KW.ts, src/locale/zh_TW.ts
- feat: 国际化语言配置新增阿拉伯语(ar_KW)和中文繁体(zh_TW)
=> feat: add more locales ar_KW and zh_TW

src/transfer/components/transfer-list.tsx
#2257 
与tdesign-next行为保持一致
- fix(transfer): incorrectly checking all after filtering
=> fix(transfer): incorrectly checking all after filtering

package.json
- feat: 主题生成器升级 `1.0` 版本，支持色彩智能推荐及尺寸调整，新增腾讯云皮肤
=> feat: upgrade tdesign theme generator v1

src/popup/plugin.tsx
- https://github.com/Tencent/tdesign-vue/issues/2340
- fix(Popup): 修复 nuxt 环境中报错的问题
=> fix(popup): plugin usage error in props definition

src/select/select.tsx
=> fix(Select): multiple size style

src/hooks/useResizeObserver.ts
=> fix(common): fix useResizeObserver window ssr error

src/color-picker/color-picker.en-US.md, src/color-picker/color-picker.md, src/color-picker/color-picker.tsx, src/color-picker/props.ts, src/color-picker/trigger.tsx, src/color-picker/type.ts
- https://github.com/Tencent/tdesign-vue/issues/1548
- feat(ColorPicker): 新增`size` API
=> feat(color-picker): support size api

src/select/option-props.ts, src/select/select.tsx, src/tag-input/hooks/useHover.ts, src/tag-input/tag-input.tsx
- https://github.com/Tencent/tdesign-vue/issues/2392
- https://github.com/Tencent/tdesign-vue/issues/2378
- fix(TagInput): 修复`disabled`响应丢失导致无法切换可清空状态的缺陷
- fix(Select): 修复使用布尔值导致的控制台告警
- fix(Select): 修复多选时折叠项在表单中的异常
=> fix: resolve select issues

src/popup/popup.tsx
- https://github.com/Tencent/tdesign-vue/issues/2398
- fix(Popup): 修复onScrollToBottom 在部分windows环境下无法触发的问题
=> fix(popup): trigger on-scroll-to-bottom on windows

.vscode/settings.json
=> chore(vscode): update settings.json

src/tag-input/useTagList.tsx, src/textarea/textarea.tsx
- https://github.com/Tencent/tdesign-vue-next/issues/2862
- https://github.com/Tencent/tdesign-vue-next/issues/2855
- fix(TagInput): 修复组件初始值异常的问题
- fix(Textarea): 修复 autosize 为 null 报错的问题
=> fix(textarea): error when autosize is null

CHANGELOG.md, package.json
=> feat: release 1.3.2

CHANGELOG.md, package.json
=> feat: release 1.3.3

src/back-top/_example/baseListSmall.vue, src/back-top/back-top.tsx
- https://github.com/Tencent/tdesign-vue/issues/2432
- fix(Backtop): 修复 visibleHeight 只触发一次的缺陷
=> fix(backtop): visibleHeight only works once

src/sticky-tool/sticky-item.tsx
- https://github.com/Tencent/tdesign-vue/issues/2421
- fix(StickyTool): 修复控制台告警
=> fix(sticky-tool): fix props warning

src/input-number/_example/center.vue, src/input-number/_example/large-number.vue, src/input-number/input-number.en-US.md, src/input-number/input-number.md, src/input-number/props.ts, src/input-number/type.ts, src/input-number/useInputNumber.tsx
子仓库：https://github.com/Tencent/tdesign-common/pull/1360
子仓库：https://github.com/Tencent/tdesign-common/pull/1361
https://github.com/Tencent/tdesign-vue/issues/2456
=> [InputNumber] 修复部分小数点数字无法输入问题

babel.config.js, package.json
详情查看issue：https://github.com/Tencent/tdesign-miniprogram/issues/2045
重命名依赖名
- chore: plugin-proposal-class-properties rename to plugin-transform-xxxx
=> chore: rename babel plugin

src/image-viewer/image-viewer.tsx
=> fix(image-viewer): 修复closeBtn prop为false时的渲染异常

src/popup/_example/plugin.vue, src/popup/popup.md
- feat(popup): dd PopupPlugin usage example
=> feat(popup): add PopupPlugin usage example

src/input-number/useInputNumber.tsx
- fix(InputNumber): 支持默认格式化小数点
=> fix: support decimalPlaces=0 and default decimal places formatted

CHANGELOG.md
=> fix: 1.4.0 changelog render error

src/table/hooks/usePagination.tsx
#2439 
- fix(table): 通过current修改分页，序列号没有变化问题修复
=> fix(table): 通过current修改分页，序列号没有变化问题修复

src/cascader/components/Panel.tsx, src/color-picker/panel/index.tsx, src/tree-select/useTreeSelect.ts
- https://github.com/Tencent/tdesign-vue/issues/2498
- https://github.com/Tencent/tdesign-vue/issues/2492
- https://github.com/Tencent/tdesign-vue/issues/2454
- fix(ColorPicker): 初始化为渐变模式时 支持空字符串作为初始值
- fix(TreeSelect): 修复keys配合valueType为object时使用的异常问题
- fix(Cascader): 修复空数组选项展示异常的问题
=> fix(colorpicker): support empty initial value for graident color

src/drawer/drawer.tsx
- #2453 
与next统一行为
- fix(Drawer): 修复destroyOnClose不符合预期问题
=> fix(Drawer): 修复destroyOnClose不符合预期问题

site/docs/getting-started.en-US.md, site/docs/starter.en-US.md, site/site.config.mjs
=> docs: provide en-version docs

src/dropdown/_example/icon.vue
https://github.com/Tencent/tdesign/issues/356
- feat(dropdown): 新增带图标的下拉菜单示例
=> feat(dropdown): 新增带图标的下拉菜单示例

src/textarea/textarea.tsx
https://github.com/Tencent/tdesign-vue/issues/2522
- fix(TextArea): 修复不能响应设置 `value` 值后 autosize 自适应失效的问题
=> fix: textarea auto height

src/swiper/swiper.tsx
- fix(Swiper): 修复 `navigation` 插槽失效的问题
=> fix(swiper): navigation slot

CHANGELOG.md, package.json, site/docs/getting-started.en-US.md, site/docs/starter.en-US.md, site/site.config.mjs, src/color-picker/panel/format/index.tsx, src/drawer/drawer.tsx, src/dropdown/_example/icon.vue, src/swiper/swiper.tsx, src/textarea/textarea.tsx
=> feat(1.4.3): weekly sync update to 2.7

src/dialog/_usage/props.json, src/dialog/dialog.tsx
- [#2348 ](https://github.com/Tencent/tdesign-vue/issues/2348)
- feat(dialog): 支持full-screen模式
=> feat: dialog support full-screen mode

.gitignore, src/upload/themes/multiple-flow-list.tsx
=> chore: setup with pnpm

site/plugin-tdoc/md-to-vue.js, site/site.config.mjs, src/config-provider/config-provider.en-US.md
=> chore: complete en docs

src/date-picker/DatePicker.tsx, src/date-picker/DateRangePicker.tsx, src/date-picker/date-picker-panel-props.ts, src/date-picker/date-picker.en-US.md, src/date-picker/date-picker.md, src/date-picker/date-range-picker-panel-props.ts, src/date-picker/date-range-picker-props.ts, src/date-picker/props.ts, src/date-picker/type.ts
https://github.com/Tencent/tdesign-vue/issues/2537
- feat(DatePicker): 新增 onConfirm事件
- docs(DatePicker): clearable描述错别字 清楚改清除
- fix(DatePicker):  valueType 验证
=> feat(DatePicker): 新增 onConfirm事件

src/input-number/useInputNumber.tsx
#2516
Corrective action would not be performed when the input value is `0`
After fix:
- fix(input-number): fix calibration invalid for `value=0`
=> fix(input-number): calibration invalid for `value=0`

helper/attributes.json, helper/tags.json, helper/web-types.json
- feature: 更新 WebStorm 等编辑器的组件提示
=> chore: update helper tips

src/popup/popup.tsx
https://github.com/Tencent/tdesign-vue/issues/2518
- fix(popup): 修复 `trigger=hover` 时首次鼠标快速移动导致父级关闭。
=> fix(popup): fix comparison of initial state

src/input/input.en-US.md, src/input/input.md, src/input/props.ts
- docs(Input): 输入框的值 类型移除 Number
=> docs(Input): value type remove Number

src/date-picker/DateRangePicker.tsx, src/date-picker/hooks/useRange.ts
- feat(DatePicker): 优化关闭浮层后重置默认选中区域
=> feat(datepicker): 优化关闭浮层后重置默认选中区域

src/tabs/tab-nav.tsx
- https://github.com/Tencent/tdesign-vue/issues/2505
- fix(tabs):  修复 tabs 组件放在在 dialog 中 tab-bar 不能正常显示的问题
=> fix(tabs): change tab navs dom to method render

src/slider/slider-button.tsx
- feat(Slider): label支持`${value}%`格式
=> feat(slider): label support % format

src/input-number/useInputNumber.tsx
- fix(InputNumber): `decimalPlaces` 存在时，数值满足要求，用户未操作，就已经触发 `onChange` 事件问题，[issue#2616](https://github.com/Tencent/tdesign-vue/issues/2616)
=> fix(input-number): default onChange trigger error

src/checkbox/group.tsx, src/table/filter-controller.tsx
- fix(Checkbox): 支持 `value` 传入 `undefined`
- fix(Table): 可筛选表格场景，filterValue 透传优化，没有显示写明 value 值的筛选项，不再透传 `undefined` 到子组件，因有些组件的默认值不允许为 undefined
=> fix(table): filter table pass value improvement

script/utils/index.js, src/checkbox/group.tsx, src/common.ts, src/table/_example/filter-controlled.vue, src/table/filter-controller.tsx, src/table/hooks/useTreeSelect.tsx, src/table/table.en-US.md, src/table/table.md, src/table/type.ts, vitest.config.js
- feat(Table): 可筛选表格，支持透传 attrs/style/classNames 属性、样式、类名等信息到自定义组件，[issue#2627](https://github.com/Tencent/tdesign-vue/issues/2627)
- fix(Table): 树形结构表格，修复选中行的值 `selectedRowKeys` 不在数据 `data` 中时，报错问题
=> feat(table): support TableColumnFilter.attrs .style .classNames

CHANGELOG.md, package.json, script/rollup.config.js
=> chore: release 1.5.2

src/menu/menu-item.tsx, src/menu/menu.md, src/menu/type.ts
fix #2621
https://github.com/Tencent/tdesign-vue/issues/2621
=> feat(menu-item): click事件参数增加value

src/menu/menu-item.tsx
fix #2688
https://github.com/Tencent/tdesign-vue/issues/2688
=> fix(menu): menu的激活菜单项未发生变化时也会触发change

src/image-viewer/image-viewer.tsx
=> fix(ImageViewer): 前后浏览及关闭浏览重置图片状态

src/select/_example/scroll-bottom.vue, src/select/select-panel.tsx, src/select/select.tsx
- https://github.com/Tencent/tdesign-vue/issues/2674
- fix(Select): 远程搜索场景下不进行内部过滤
- docs(Select): 优化滚动加载场景示例代码
=> fix(select): disable internal filter when remote search

src/checkbox/group.tsx
fix #2700 
- fix(checkbox):  修复控制台报错
=> fix(checkbox):  修复控制台报错

src/checkbox/checkbox.tsx, src/checkbox/group.tsx, src/checkbox/store.ts
- fix(Checkbox): 修复 `options` 异步获取时，`disabled` 失效问题
- fix(Checkbox): 修复 `options` 异步获取时，`value` 失效问题
=> fix(checkbox): async options state

src/cascader/interface.tsx
=> chore: fix export type

src/cascader/interface.tsx
=> chore: cascader TreeKeysType export position

src/dropdown/dropdown.tsx, src/popup/popup.tsx, src/popup/utils.ts
- https://github.com/Tencent/tdesign-vue/issues/2598
- https://github.com/Tencent/tdesign-vue/issues/2280
- https://github.com/Tencent/tdesign-vue/issues/2352
- https://github.com/Tencent/tdesign-vue/issues/2594
- fix(Dropdown): 修复部分场景下展示下拉菜单异常的问题
=> fix(dropdown): add  delay time to visible status

src/upload/__tests__/__snapshots__/vitest-upload.test.jsx.snap, src/upload/_example/draggable.vue, src/upload/hooks/useUpload.ts, src/upload/themes/dragger-file.tsx, src/upload/themes/image-card.tsx
image preview
- fix(Upload): 修复非自动上传场景，无法预览图片问题，[tdesign-vue-next#3273](https://github.com/Tencent/tdesign-vue-next/issues/3273)
- fix(Upload): 修复非图片组件预览时的文本错位问题
=> fix: upload can not preview image with not autoupload

src/select/select.tsx
- https://github.com/Tencent/tdesign-vue/issues/2732
- fix(Select): 修复`1.6.2`改动导致选项 `disabled` 属性失效的问题
=> fix(Select): option disabled attr is not working

src/table/hooks/useTreeData.tsx, src/table/hooks/useTreeDataExpand.ts
- fix(Table): 树形结构，修复 v1.6.4 中 `tree.defaultExpandAll` 失效问题
=> fix(table): tree.defaultExpandAll does not work

package.json, src/dropdown/dropdown.tsx, src/popup/popup.tsx, src/popup/utils.ts, src/tabs/__tests__/index.test.jsx, src/tabs/tab-panel-props.ts, src/tabs/tab-panel.tsx, src/tabs/tabs.md, src/tabs/type.ts, src/upload/__tests__/__snapshots__/vitest-upload.test.jsx.snap, src/upload/_example/draggable.vue, src/upload/hooks/useUpload.ts, src/upload/themes/dragger-file.tsx, src/upload/themes/image-card.tsx
=> feat(1.6.4): weekly sync update to naruto

src/checkbox/_example/controlled.vue, src/checkbox/checkbox.tsx, src/checkbox/group.tsx, src/checkbox/store.ts
- fix(Checkbox): 修复同时有多个 CheckGroup 时，选中值显示异常问题，[issue#2761](https://github.com/Tencent/tdesign-vue/issues/2761)
=> fix(checkbox): multitple checkbox-group exist at the page

src/popup/popup.tsx
- fix(popup): 修复 `destroyOnClose=true` 时鼠标多次 hover 后可能无法打开的问题。
=> fix(popup): clear queued open action caused by accident

src/popup/popup.tsx
Reverts Tencent/tdesign-vue#2747
=> Revert "fix(popup): clear queued open action caused by accident"

script/rollup.config.js
- https://github.com/Tencent/tdesign-vue/issues/2749
- fix: 修复产物中 `env` 环境的问题
=> fix: fix bundle content

src/auto-complete/option-list.tsx, src/table/hooks/useAffix.ts
- https://github.com/Tencent/tdesign-vue/issues/2773
- fix(Autocomplete): 修复错误的移除事件监听时机
- fix(Table): 修复固定表头/尾错误的移除事件监听时机
=> fix: fix remove listener hook

src/loading/plugin.tsx
- https://github.com/Tencent/tdesign-vue/issues/2566
- fix(Loading): 修复Plugin在部分场景下设置 false 入参时重新创建实例的问题
=> fix(loading): fix loading false create instance again

src/tag-input/useTagList.tsx
- fix(Select): 修复删除 input 中的内容时，会删除已选项的缺陷
=> fix(Select): fix delete exist option when delete input value

src/checkbox/group.tsx, src/upload/themes/image-card.tsx
- fix(Checkbox): 修复动态设置 `options` 无效问题，[issue#2792](https://github.com/Tencent/tdesign-vue/issues/2792)
- fix(Upload): 上传组件 `theme='image'` 时，在 `disabled` 状态不显示上传按钮
=> fix(checkbox): checkbox with dynamic async group prop can not be checked

CHANGELOG.md, package.json
=> chore: release 1.6.6

src/tree-select/tree-select.tsx
- https://github.com/Tencent/tdesign-vue-next/issues/3347
- feat(TreeSelect): 支持`panelTopContent`和 `panelBottomContent` 的使用
=> feat(treeselect): support panel content API

src/hooks/useResizeObserver.ts
- fix(useResizeObserver): 修复缺少容器元素判空问题
=> useResizeObserver container.value could be empty

src/dialog/_example/base.vue, src/hooks/useResizeObserver.ts, src/input/input.tsx
#2401 
同步tdesign-vue-next:
https://github.com/Tencent/tdesign-vue-next/pull/3411
https://github.com/Tencent/tdesign-vue-next/pull/3352/files#diff-d8b69af295e334f149eec368813fea0aa1be732c2a39a248b4625d5536e3bce1
- fix(dialog): 修复 Dialog 弹框中打开表格，表格中分页组件信息出现超出省略问题
=> fix(dialog): 修复 Dialog 弹框中打开表格，表格中分页组件信息出现超出省略问题

src/image-viewer/image-viewer.tsx
fix #2815 
- fix(ImageViewer): 关闭时偶尔会出现抖动现象
=> fix(image-viewer): occasionally experiences jittering when closing

src/date-picker/DatePicker.tsx
- #2827
- fix(DatePicker): `confirm` 事件无效
=> fix(date-picker): confirm event does not work

src/cascader/core/effect.ts
fix #2835
- fix(Cascader):  `change` 事件中 `source` 异常问题([issue #2835](https://github.com/Tencent/tdesign-vue/issues/2835))
=> fix(cascader): effect source abnormal

CHANGELOG.md, package.json
=> chore: release 1.7.0

CHANGELOG.md, package.json
=> chore: release 1.7.1

src/cascader/hooks.ts
[#2859](https://github.com/Tencent/tdesign-vue/issues/2859)
=> [cascader]选项disabled修改后，选项不是禁用状态#2859

src/tree/__tests__/api.test.jsx, src/tree/__tests__/event.test.jsx, src/tree/_example/checkable.vue, src/tree/_example/operations.vue, src/tree/hooks/useTreeStore.ts, src/tree/tree.en-US.md, src/tree/tree.md, src/tree/tree.tsx, src/tree/type.ts
期望提供获取树结构数据的 api。
- fix(tree): 提供获取树结构数据的 api: getTreeData
=> feat(tree): add api getTreeData

src/anchor/__tests__/anchor-link.test.jsx, src/anchor/anchor-item.tsx, src/anchor/anchor.tsx, src/color-picker/panel/swatches.tsx
之前的某个版本里 lodash 引入方式有问题，导致构建时整个 lodash 被引入进去了
- fix: 修正 lodash 引入
=> fix: 修正 lodash 引入

src/checkbox/_example/base.vue, src/checkbox/group.tsx
- fix(Checkbox): 修复 `value.splice` 无法设置选中项变化问题（Vue2 天然支持，Vue Composition API 场景需要单独特别支持）
=> fix(checkbox): value.splice does not work

CHANGELOG.md, package.json
=> chore: release 1.7.2

src/loading/directive.ts
#2844
- feat(loading): 新增使用v-loading时元素被移除后一同隐藏
=> feat(loading): support v-loading unbind

src/table/hooks/useFixed.ts
- fix(Table): 列配置操作场景，修复表头不显示时，报错问题
=> fix(table): TypeError: Cannot read properties of undefined (reading 'length')     at calculateThWidthList2

src/cascader/cascader.tsx, src/tree-select/useTreeSelect.ts
- https://github.com/Tencent/tdesign-vue/issues/2840
- https://github.com/Tencent/tdesign-vue/issues/2701
- fix(cascader): 修复数字为value时的告警问题
- fix(tree-select): 修复数字为value时的告警问题
=> fix(cascader): fix placeholder warning

src/checkbox/hooks/useKeyboardEvent.ts, src/radio/group.tsx
https://github.com/Tencent/tdesign-vue-next/pull/3599#discussion_r1403299874
=> refactor: radio/checkbox选中判断改回正则

src/table/primary-table.tsx
- fix(Table): 可编辑表格，修复 `row-edit` 事件没有触发问题
=> fix(table): row-edit event not trigger

src/pagination/pagination.tsx
Fix #2932 
- fix(Pagination): 修复当 `total` 为 0 并且 `pageSize` 改变时， `current` 值为 0 的问题
=> fix(pagination): when total is 0 and pageSize change, current value is 0

src/image-viewer/image-viewer.tsx
自然滚动与标准滚动对图片放大缩小的操作均符合直觉
#2825
#2825 
- fix(ImageViewer): 滚轮缩放符合操作直觉
=> fix(ImageViewer): 滚轮缩放符合操作直觉

CHANGELOG.md, package.json, src/dropdown/dropdown-menu.tsx
=> chore: release 1.8.3

src/image-viewer/image-viewer.tsx, src/upload/hooks/useUpload.ts, src/upload/themes/multiple-flow-list.tsx, src/upload/upload.tsx
- fix(Upload): 修复手动上传时，无法更新上传进度问题
- fix(Upload): 修复图片预览时，无法切换预览图片问题
- feat(Upload): 手动上传场景，支持进行粘贴上传
=> fix(table): uploadFilePercent does not work with autoUpload=false

site/docs/getting-started.md
=> docs: update FAQ

src/image-viewer/const.ts, src/image-viewer/hooks.ts, src/image-viewer/image-viewer.en-US.md, src/image-viewer/image-viewer.md, src/image-viewer/image-viewer.tsx, src/image-viewer/type.ts
添加defaultScale
#2928
#2928 
- fix(ImageViewer): 添加defaultScale
=> fix(ImageViewer): 添加defaultScale

src/select/select.tsx
- fix(Select): 修复naruto版本minCollapsedNum与disabled API的功能异常问题 
=> fix(Select): naruto version bug

src/loading/plugin.tsx
#3023
- fix(loading): 修复重复调用`LoadingPlugin()`时报错
=> fix(loading): fix functional repeated call error

site/docs/getting-started.en-US.md, site/docs/getting-started.md
- https://github.com/Tencent/tdesign-vue/issues/2285
- docs: 更新`webpack`中使用`unplugin`的说明文档
=> docs: update unplugin usage desc with webpack

src/table/_example/expandable.vue, src/table/_example/filter-controlled.vue, src/table/hooks/usePagination.tsx, src/table/hooks/useRowSelect.tsx, src/table/primary-table.tsx
=> fix(table): 移除非必要的分页监听

src/tag-input/useTagList.tsx
- fix(TagInput): 修复`size` API 没有作用到折叠选项的问题
=> fix(tag-input): pass size api to collapse item

src/slider/_example/base.vue, src/slider/props.ts, src/slider/slider-button.tsx, src/slider/slider.en-US.md, src/slider/slider.md, src/slider/slider.tsx, src/slider/type.ts
=> feat(Slider): support change end API

src/utils/helper.ts
=> fix(Form): fix form string length test

src/descriptions/descriptions.tsx
fix #3063 
- fix(Descriptions): 解决控制台报错绑定属性 `title` 已声明为属性的问题
=> fix(descriptions): title is already declared as a prop

src/config-provider/config-provider.en-US.md, src/config-provider/config-provider.md, src/config-provider/type.ts, src/table/base-table-props.ts, src/table/base-table.tsx, src/table/enhanced-table-props.ts, src/table/hooks/useStyle.ts, src/table/primary-table-props.ts, src/table/primary-table.tsx, src/table/table.en-US.md, src/table/table.md, src/table/type.ts
https://github.com/Tencent/tdesign-vue-next/issues/3978
- feat(table): 支持全局配置 size
=> feat(table): 支持全局配置 size

src/table/primary-table.tsx
- https://github.com/Tencent/tdesign-vue/issues/2970
- fix(Table): 修复`Table`缺失`refreshTable`方法的异常
=> fix(table): primary-table expose refreshTable function

README-zh_CN.md, README.md
=> chore: update group code

src/transfer/components/transfer-search.tsx
fix #3117 
- fix(Transfer): `search` 事件的 `trigger` 异常
=> fix(transfer): trigger exception for the search event

src/loading/index.ts
参考：https://github.com/Tencent/tdesign-vue-next/pull/4048
默认将 `vLoading` 导出用于 `unplugin-vue-components` 后续增加 `directive` 逻辑。
=> fix(loading): export directive alias

src/checkbox/checkbox.tsx
#2908 
1.9.1版本 #2908  问题依旧存在，复现示例：https://stackblitz.com/edit/xnh4p5-iylka3?file=src%2Fdemo.vue
排查是nextTick并没有达到预期效果，替换成setTimeout可行
- fix(checkbox): checkboxGroup.max 禁用态显示问题
=> fix(checkbox): checkboxGroup max effects disable status

src/dialog/_example-composition/plugin.vue, src/dialog/_example/plugin.vue
https://github.com/Tencent/tdesign-vue/issues/3112
docs(dialog): add comment for usage precautions
=> docs(dialog): add comment for usage precautions

src/table/hooks/useFixed.ts
#3122 
- fix(Table): 使用 `fixedRows` 属性控制台报错
=> fix(table): use the `fixedRows` property console to report errors

src/date-picker/DatePicker.tsx
- fix(DatePicker): 修复周和季度模式选择异常的问题
=> fix(datepicker): fix datepicker week parse error

src/index.ts, src/loading/index.ts
=> chore: rename loading directive export

src/menu/submenu.tsx
#3143 
- feat(Submenu): 透传 `Popup` 组件全部特性
- fix(Submenu): 设置 `popup-props` 中 `placement` 属性无效
=> feat(submenu): enable props popup-props

src/upload/hooks/useUpload.ts
* #3115 
- fix(upload):修复 `uploadFilePercent` 更新 `percent` 无效。
=> fix(upload): `uploadFilePercent` reactive not triggered

CHANGELOG.md, package.json, site/docs/getting-started.en-US.md, site/docs/getting-started.md, src/menu/submenu.tsx, src/select/option-props.ts, src/select/type.ts, src/textarea/calcTextareaHeight.ts, src/upload/hooks/useUpload.ts
=> chore: release 1.9.3-naruto

src/upload/_usage/props.json, src/upload/props.ts, src/upload/type.ts, src/upload/upload.en-US.md, src/upload/upload.md
https://github.com/Tencent/tdesign-react/issues/2852
- fix(upload): fix options method
=> fix(upload): fix options method

helper/attributes.json, helper/web-types.json, package.json, src/dialog/dialog.tsx, src/radio/props.ts, src/radio/radio.md, src/radio/type.ts, src/select/select-panel.tsx, src/table/_example-composition/filter-controlled.vue, src/table/_example-composition/single-sort.vue, src/table/_example/filter-controlled.vue, src/table/_example/single-sort.vue, src/table/base-table.tsx, src/tree/hooks/useTreeScroll.ts
=> chore: fix docs

CHANGELOG.md, package.json
=> chore: release 1.9.4

package.json
=> chore: upgrade site component version

src/tabs/tab-nav.tsx
详见[#498](https://github.com/Tencent/tdesign/issues/498)
原来没有使用 `common` 公共仓库的函数代码，现在改为同步使用公共仓库函数。
- feat(tabs): 支持通过滚轮或者触摸板进行滚动操作
=> feat(tabs): supports scrolling operations via wheel or touchpad

src/tree/_example/draggable.vue, src/tree/hooks/useDragHandle.ts
- https://github.com/Tencent/tdesign-vue/issues/3211
- fix(Tree): 修复 `1.9.5` 版本使用拖拽功能的报错问题
=> fix(Tree): fix tree warning

CHANGELOG.md, package.json
=> chore: release 1.9.6

site/src/components/stackblitz/content.js
- fix: fix stackblitz demo run
=> fix: fix stackblitz demo run

src/dialog/dialog.tsx
[https://github.com/Tencent/tdesign-vue/issues/3216](https://github.com/Tencent/tdesign-vue/issues/3216)
- fix(Dialog): 修复 `Dialog` 组件在 `SSR` 环境下的使用问题
=> fix(Dialog): dialog ssr

CHANGELOG.md, package.json
=> chore: release 1.9.7

CHANGELOG.md, package.json, site/src/components/stackblitz/content.js, src/dialog/dialog.tsx
=> chore: release 1.9.7-naruto

CONTRIBUTING.md
=> chore: modify TEST_GUIDE link

src/tag-input/useTagList.tsx
- fix(TagInput): 修复`tagProps` 没有作用到折叠的标签上的缺陷
=> fix(TagInput): tagProps should effect minCollapseNum tag

src/button/_usage/props.json
- https://github.com/Tencent/tdesign-vue-next/issues/4449
- docs: 优化`Button`的文档展示和调整问题
=> chore: remove ghost config from live demo

src/time-picker/panel/single-panel.tsx
- https://github.com/Tencent/tdesign-vue/pull/3280
- https://github.com/Tencent/tdesign-common/pull/1906
=> perf: use getPickerCols

src/badge/badge.tsx
- https://github.com/Tencent/tdesign-vue/issues/3263
- fix(Badge): 修复 `content` API 的异常问题
=> fix(badge): fix content api

src/cascader/cascader-panel.tsx
- feat(Cascder): 新增级联面板支持自定义下拉选项内容的能力
=> feat(cascader): cascader panel support option slot

src/empty/empty.tsx
=> chore: replace type alias path to relative path

src/select/select.tsx
- https://stackblitz.com/edit/yra6kx?file=src%2Fdemo.vue
- fix(Select): 修复下拉面板存在自定义节点且存在回车等操作时与组件自身键盘事件冲突的问题
=> fix(Select): fix keyboard event conflict with self-defined components

src/select/select.tsx
=> chore: optimize

.github/workflows/pr-comment-ci.yml, package.json
=> chore: update pr-comment-ci

site/src/App.vue
=> feat(site): component Internationalization

src/tree-select/tree-select.tsx, src/tree/hooks/useRenderLabel.tsx
- fix(TreeSelect): 修改多选状态下默认点击父节点选项的行为为选中，如果需要点击展开，请配置`treeProps.expandOnClickNode`
- fix(Tree): 修复多选下配置 `expandOnClickNode` 后没有正确生效的问题
=> fix(tree-select): fix multiple select click parent node callback

src/locale/it_IT.ts, src/locale/ru_RU.ts
- feat(i18n): 国际化新增 意大利语`it_IT`  俄语`ru_RU` 
=> feat(i18n): add ru_RU and  it_IT

src/date-picker/_example-composition/week.vue, src/date-picker/_example/week.vue
- fix(DatePicker): 修复周选择器下，年份边界日期返回格式错误的问题
- docs(DatePicker): 优化周选择器配合`firstDayOfWeek`使用的问题
=> fix(DatePicker): fix boundary week format bug

src/cascader/core/effect.ts
- https://github.com/Tencent/tdesign-vue/issues/3329
- fix(Cascader): 修复过滤条件下选择父节点导致样式异常的问题
=> fix(cascader): fix filterable parent click bug

src/cascader/cascader.tsx
- fix(Cascader): 修复初始化滚动节点时未兼容单选父节点滚动的缺陷
=> fix(cascader): fix scroll to first selected node

script/generate-usage/config.js, src/drawer/_usage/index.vue
* [[Drawer] 官网usage demo中开关header表现不符合预期 #4697](https://github.com/Tencent/tdesign-vue-next/issues/4697)
使用`header slot` 和 `boolean header` 组合用于区分 `header` 为开关时的区别
- fix(drawer): fix the issue where the header does not behave as expected
=> fix(drawer): fix the issue in the demo where the "header" does not behave as expected

src/date-picker/date-picker.md, src/date-picker/date-range-picker-props.ts, src/date-picker/props.ts, src/switch/props.ts, src/switch/switch.md, src/switch/type.ts
=> chore: fix typo and desc

CHANGELOG.md, package.json
=> chore: release 1.10.5

package.json, src/icon/icon.en-US.md, src/icon/icon.md
- feat(Icon): 图标库发布 `0.3.0`版本，新增 907 个新图标；命名优化`blockchain` 重命名改为`transform-1`,`gesture-pray-1`重命名为`gesture-open`,`gesture-ranslation-1`重命名为`wave-bye`, `gesture-up-1`重命名为`gesture-typing`,`gesture-up-2`重命名为`gesture-right-slip`,`logo-wechat`重命名为`logo-wechat-stroke-filled`，移除`tree-list`、`logo-adobe-photoshop-1` 等错误图标
- docs(Icon): 优化图标检索功能，支持中英文搜索图标
=> feat(icons): new version

site/src/components/page.vue
=> chore: replace version request

src/transfer/_example/tree.vue, src/transfer/components/transfer-list.tsx, src/transfer/utils.ts
- 树形组件选项禁用 https://github.com/Tencent/tdesign-vue-next/issues/4809
- 拖拽排序向后移动
https://github.com/user-attachments/assets/c25ca283-9c06-4dbd-807b-a7cb2911816d
- fix(Transfer): 修复树形组件选项禁用在全选下仍可选中的缺陷
- fix(Transer): 修复拖拽排序向后移动的功能异常
=> fix(transfer): fix tree disabled and drag sort bug

src/slider/__tests__/index.test.jsx, src/slider/_example-composition/base.vue, src/slider/_example/base.vue, src/slider/index.ts, src/slider/slider.tsx
- fix(Slider): 修复`Slider`组件不支持受控用法的问题
- chore: 移除错误的测试用例
=> fix(Slider): fix controlled usage

CHANGELOG.md, package.json
=> chore: release 1.10.6

src/table/__tests__/base.test.jsx, src/table/filter-controller.tsx
- fix(Table): 修复 `filterIcon` 不生效
=> fix(table): resolve props.filterIcon not work

src/dialog/dialog.tsx
- https://github.com/Tencent/tdesign-vue/issues/3421
- fix(Dialog): 修复`dialog`组件 `props` 重复导致的异常问题
=> fix(Dialog): fix dialog props duplicate

CHANGELOG.md, package.json
=> chore: release 1.10.7

CHANGELOG.md, package.json, src/color-picker/const.ts, src/color-picker/panel/format/index.tsx, src/color-picker/panel/header.tsx, src/color-picker/panel/index.tsx, src/color-picker/panel/linear-gradient.tsx, src/color-picker/panel/saturation.tsx, src/color-picker/panel/slider.tsx, src/dialog/dialog.tsx, src/table/__tests__/base.test.jsx, src/table/filter-controller.tsx
- chore: release 1.10.7-naruto
=> chore: release 1.10.7-naruto

src/dialog/props.ts
- https://github.com/Tencent/tdesign-vue/issues/3432
- fix(Dialog): 修复`1.10.6`版本`closeOnOverlayClick`的默认行为异常的问题
=> fix(Dialog): fix closeOnOverlayClick default behavior

src/cascader/core/helper.ts
#3436
- fix(Cascader): 校验无效值逻辑错误并优化代码
=> fix(cascader): verify invalid value logic errors and optimize code

helper/attributes.json, helper/tags.json, helper/web-types.json, src/calendar/calendar.tsx, src/descriptions/descriptions.en-US.md, src/descriptions/descriptions.md
https://github.com/TDesignOteam/tdesign-api/pull/504
=> docs: fix typo

src/table/hooks/useRowSelect.tsx
- https://github.com/Tencent/tdesign-vue/issues/3441
- fix(Table): 优化`select-change`中回调参数的返回值，不返回不存在的rowData
=> fix(table): filter undefined from selectRowData

src/table/base-table.tsx, src/table/hooks/useHoverKeyboardEvent.ts, test/snap/__snapshots__/csr.test.js.snap
- https://github.com/Tencent/tdesign-vue/issues/3455
- fix(Table): 修复无法通过键盘操作表格左右滚动的问题
=> fix(Table): fix table horizontal scroll

src/auto-complete/auto-complete.en-US.md, src/auto-complete/auto-complete.md, src/auto-complete/auto-complete.tsx, src/auto-complete/option-list.tsx, src/auto-complete/props.ts, src/auto-complete/type.ts, src/config-provider/config-provider.en-US.md, src/config-provider/config-provider.md, src/config-provider/type.ts
- feat(AutoComplete): 新增`empty` API，用于配置空状态下的下拉内容展示
=> feat(auto-complete): support empty api

CHANGELOG.md, package.json
=> chore: release 1.10.9

src/transfer/utils.ts
perf(transfer): optimize filterTransferData for better performance
当 Transfer 的 `value` 
``` ts
value=['John']
```
值 不存在于 `data` 内
```ts
data = [
{
value: 'Tom',
label: 'Tom',
},{
value: 'Jim',
label: 'Jim',
}
]
```
时，函数 `filterTransferData` 会返回一个 `[undefined]` 数据，从而导致 ** 处理普通结构** 时会产生错误。
- fix(transfer): 确保 `filterTransferData` 仅返回有效值
=> fix(transfer): ensure `filterTransferData` returns only valid items

src/menu/menu-group.tsx
- fix(Menu): 修复`MenuGroup`的 title 不支持使用函数渲染的问题
=> fix(Menu): fix function usage of menu group title

src/select-input/type.ts, src/select/select.tsx
- fix(Select): 多选情况下移除标签无法正确匹配 `trigger` 值的问题
=> fix(select): enhance type handling and improve tag removal logic

src/tree/hooks/useDragHandle.ts, src/tree/tree-types.ts
=> fix: code spell error

src/image-viewer/base/ImageItem.tsx, src/image-viewer/base/ImageViewerModal.tsx, src/image-viewer/base/ImageViewerUtils.tsx, src/image-viewer/image-viewer.en-US.md, src/image-viewer/image-viewer.md, src/image-viewer/image-viewer.tsx, src/image-viewer/props.ts, src/image-viewer/type.ts, src/tree/hooks/useDragHandle.ts, src/tree/tree-types.ts
- https://github.com/Tencent/tdesign-vue/issues/3504
- feat(ImageViewer): 新增`imageReferrerpolicy`API，适用于配置Referrerpolicy的场景
- feat(ImageViewer): 新增`onDownload`API，用于自定义下载回调
=> feat(imageViewer): Custom Download Callback

script/rollup.config.js
=> fix: fix cjs build

src/date-picker/hooks/useDisableDate.ts
fix(date-picker): disable date range error
⚠️ Blocked until  https://github.com/Tencent/tdesign-common/pull/2071 is merged  
原实现逻辑会导致 date-picker 组件的禁用范围计算错误，现将其改为 common 内的公共函数进行判断，解决了多端判断逻辑的一致性。
- fix(date-picker): 修复日期禁用范围错误
=> refactor(DatePicker): `useDisableDate` to use common `isEnabledDate`

CHANGELOG.md, package.json, src/image-viewer/base/ImageViewerUtils.tsx, src/image-viewer/image-viewer.tsx
=> chore: release 1.11.1

.github/workflows/pkg-pr-new.yml, CHANGELOG.md, package.json, script/rollup.config.js, src/date-picker/hooks/useDisableDate.ts, src/dialog/actions.tsx, src/image-viewer/base/ImageItem.tsx, src/image-viewer/base/ImageViewerModal.tsx, src/image-viewer/base/ImageViewerUtils.tsx, src/image-viewer/image-viewer.en-US.md, src/image-viewer/image-viewer.md, src/image-viewer/image-viewer.tsx, src/image-viewer/props.ts, src/image-viewer/type.ts, src/message/messageList.tsx, src/message/plugin.tsx, src/select-input/type.ts, src/select/select.tsx, src/tree/hooks/useDragHandle.ts, src/tree/tree-types.ts, src/upload/hooks/useUpload.ts, src/upload/upload.tsx
- chore: release 1.11.1-naruto
=> chore: release 1.11.1-naruto

.github/workflows/naruto-publish.yml
=> chore: fix naruto publish ci

src/guide/__tests__/__snapshots__/vitest-guide.test.jsx.snap, src/progress/__tests__/__snapshots__/index.test.jsx.snap, src/tag/__tests__/vitest-tag.test.jsx, test/snap/__snapshots__/csr.test.js.snap
=> chore: update snapshot since dependency bug fix

.github/workflows/pkg-pr-new.yml
=> ci(pkg-pr-new): add running conditions

src/card/card.en-US.md, src/card/card.md
=> docs(card): fix card api documentation text

src/guide/__tests__/vitest-guide.test.jsx
当前在 windows 下 60ms 有概率因卡顿而导致测试失败
=> test(Guide): mockDelay time changed from 60ms to 200ms

script/test/setup.js
=> chore(vitest): filter log

CONTRIBUTING.md
-  添加tdesign-common仓库链接地址，避免在github搜索中浪费时间
-  优化了一些表达内容，如："遵循使用"显冗余，去除使用等
=> docs(CONTRIBUTING): improve readability of development workflow section in CONTRIBUTING.md

site/docs/getting-started.en-US.md, site/docs/getting-started.md
=> docs: optimize usage tips

src/image-viewer/base/ImageViewerUtils.tsx
- https://github.com/Tencent/tdesign-vue/issues/3537
- fix(ImageViewer): 修复设置`step` 存在精度展示异常的问题
=> fix(imageviewer): fix scale precision bug

site/vite.config.js
- https://github.com/Tencent/tdesign-vue/pull/3564
=> chore: fix site build after upgrading to vite 4+

CHANGELOG.md
=> chore: add CHANGELOG

src/upload/themes/multiple-flow-list.tsx
https://github.com/Tencent/tdesign-vue-next/issues/5324
- fix(upload): image-flow模式支持自定义错误文本
=> fix(upload): 补充image-flow模式下自定义错误文本的实现

test/snap/__snapshots__/csr.test.js.snap
https://github.com/asamuzaK/cssColor/pull/75
修正了解析 calc(2em + 24px) 变 calc((2em + 24px))
=> chore: update snapshots

site/site.config.mjs
=> docs(guide): add English component import

src/input-number/input-number.en-US.md, src/input-number/input-number.md, src/input-number/props.ts, src/input-number/type.ts
（同步一下 API 仓库）
具体逻辑都封装在 common 里了，不需要新增方法，只不过 TS 暴露出支持的写法，让用户知道可以传参覆盖
- feat(InputNumber): `decimalPlaces` 支持 `enableRound` 参数，用于控制是否启用四舍五入
=> feat(InputNumber): add `enableRound` support to `decimalPlaces` prop

.github/workflows/pkg-pr-new.yml, script/workflows/pkg-pr-new-generate-template.mjs
=> chore(ci): generation vue pkg templates

package.json
cssstyle 4.4.0 有问题，还没修复，固定4.3.1
=> chore: pin cssstyle 4.3.1

src/table/hooks/useColumnController.tsx
sync https://github.com/Tencent/tdesign-vue-next/pull/5546
- fix(Table): 优化关闭列配置弹窗时，选择列数据与所展示列数据不一致的问题
=> fix(Table): sync columnCheckboxKeys on close

package.json
=> chore: fix win run build

src/date-picker/DatePicker.tsx
close #3597
- fix(date-picker):使用 `popupProps` 控制 `visible` 属性时无法选择时间
=> fix(date-picker): unable to select time via `popupProps.visible`

src/tree/hooks/useTreeStore.ts
- feat(Tree): `expandAll` API 支持响应式
=> feat(tree): support responsive expand-all 

src/calendar/calendar-cell.tsx, src/dialog/dialog.tsx, src/drawer/drawer.tsx, src/dropdown/dropdown.tsx, src/input/input.tsx, src/slider/slider-button.tsx
```
Property 'ondblclick' does not exist on type 'ElementAttrs<HTMLAttributes>'. Did you mean 'onDblclick'?
```
=> fix: update HTMLAttributes

src/image/image.tsx, src/image/index.ts
=> perf(image):  use composition api

site/plugins/plugin-tdoc/md-to-vue.js
- fix: 修复 live demo 和设计指南展示异常的问题
=> chore: fix live demo and guide

src/hooks/useVirtualScroll.ts
#3662
- fix(Select): 修复虚拟滚动搜索后出现空白区域的问题
=> fix(hooks): improve code readability and safety in scroll calculations

src/cascader/hooks.ts
https://github.com/Tencent/tdesign-vue-next/pull/5581
- fix(Cascader): 修复 `value-type="full"` ，value 为 undefined时组件内部报错
=> fix(cascader): fix value-type="full", value is undefined error

global.d.ts, site/docs/getting-started.en-US.md, site/docs/getting-started.md
=> docs: update getting-started

package.json
=> chore: fix build

package.json, site/src/App.vue, site/src/main.js
=> chore: @tdesign/site-components instead of tdesign-site-components

package.json, site/package.json, site/vite.config.js
- 流水线两星期前已经合并内外网站点的构建和部署，观察了两周没有其他异常，内外网差异通过path和相关逻辑进行区分，不再需要区分 production 和 intranet mode
=> chore: merge deploy mode
