Tencent/tdesign-vue

site/src/App.vue
site/src/components/codesandbox/index.vue

`vite-plugin-vue2` v1.9.0 compile sfc error when use `Vue.component()`

fix: codesandbox icon render error

---

src/time-picker/panel/index.tsx

fix(timepicker): missing render under HH:mm:ss A format

---

examples/form/demos/validator-status.vue
site/src/App.vue
site/src/components/codesandbox/index.vue
src/input/input.tsx
src/time-picker/time-picker.tsx
test/ssr/__snapshots__/ssr.test.js.snap
test/unit/drawer/__snapshots__/demo.test.js.snap
test/unit/input/__snapshots__/demo.test.js.snap
test/unit/input/__snapshots__/index.test.js.snap
test/unit/pagination/__snapshots__/demo.test.js.snap
test/unit/time-picker/__snapshots__/demo.test.js.snap
test/unit/tree-select/__snapshots__/demo.test.js.snap
test/unit/tree-select/__snapshots__/index.test.js.snap
test/unit/tree/__snapshots__/demo.test.js.snap

- 修复 src/input/input.tsx 文件：input无默认placeholder的问题
- 修复 examples/form/demos/validator-status.vue 文件 help icon展示大小的问题
其余都是 snapshots update

fix: select defult placeholder

---

examples/icon/icon.md
package.json

升级展示用的icon-view包 规范web component 名称为`td-icon-view` 和其他tdesign的web-component保持一致。

chore: upgrade icon-view

---

.npmrc
package.json
site/package.json

本地开发工具由 `webpack` 改为 `vite` [commit](https://github.com/Tencent/tdesign-vue/commit/0a3a97f4099271ea3f96562ece23892f61d5d06e) 时，引入了 [npm worksapce](https://docs.npmjs.com/cli/v7/using-npm/workspaces) 特性依赖，要求开发环境为 npm >= 7.x，存在以下问题：
- 对开发者不友好，需要升级本地 nodejs 版本到 16.x LTS 以上，或 `npm i -g npm` 全局升级 npm 包版本才能参与开发
- 有可能影响到业务使用：有可能业务项目中启用了 [engine-strict](https://docs.npmjs.com/cli/v8/using-npm/config#engine-strict) 严格模式，导致在 `nodejs < 16.x LTS | npm < 7.x` 时安装包失败
为了保证体验，本次 pr 去掉 npm worksapce 特性依赖。

feat: remove workspaces to aviod npm version restrictions

---

examples/config-provider/config-provider.md
examples/input/demos/base.vue
src/config-provider/en_US_config.ts
src/config-provider/type.ts
src/config-provider/zh_CN_config.ts
src/input/input.tsx
src/time-picker/time-range-picker.tsx
test/ssr/__snapshots__/ssr.test.js.snap
test/unit/input/__snapshots__/demo.test.js.snap

- add input config provider
- fix time-range-picker placeholder overlap

feat(input): add input config provider

---

src/input/input.tsx

resolved #90 
本地已经跑过lint和test了
- Input: 修复清除数据后没有聚焦的问题，[pr#91](https://github.com/Tencent/tdesign-vue/pull/91)，[issue#90](https://github.com/Tencent/tdesign-vue/issues/90)，[@clark-cui](https://github.com/clark-cui)

fix(input): focus after clear value

---

src/steps/steps.tsx
test/ssr/__snapshots__/ssr.test.js.snap
test/unit/steps/__snapshots__/demo.test.js.snap

fix #36
- Component Name: steps.
- [issue#36](https://github.com/Tencent/tdesign-vue/issues/36)，[LuckyWinty](https://github.com/LuckyWinty)
- steps: 修复 step item extra 没有渲染出来的问题
--------
**brefore**
.....
**after**
......

fix(steps): fix step item extra

---

examples/drawer/drawer.md
src/dialog/dialog.tsx
src/drawer/drawer.tsx
src/drawer/props.ts
src/drawer/type.ts
src/loading/loading.tsx
src/loading/plugin.tsx

- fix #73 
sub modules pr address:  https://github.com/Tencent/tdesign-common/pull/59
其中涉及到了src/drawer/props.ts、src/drawer/type.ts这两个文件的变更: 增加preventScrollThrough属性

fix drawer scroll through

---

src/affix/affix.tsx

- Affix：calcInitValue方法中获取当前可视的高度逻辑冗余 处理问题或特性描述 [@kenny](https://github.com/868618)
--------
**brefore**
let containerHeight = 0; // 获取当前可视的高度
if (scrollContainer instanceof Window) {
containerHeight = scrollContainer.innerHeight;
} else {
containerHeight = scrollContainer.clientHeight;
}
**after**
const containerHeight = scrollContainer[scrollContainer instanceof Window ? 'innerHeight' : 'clientHeight'];

perf(affix.tsx): 获取当前可视的高度containerHeight用三目运算符

---

examples/input/demos/base.vue
examples/input/input.md
src/input/input.tsx
src/input/props.ts
src/input/type.ts
test/ssr/__snapshots__/ssr.test.js.snap
test/unit/date-picker/__snapshots__/demo.test.js.snap
test/unit/date-picker/__snapshots__/index.test.js.snap
test/unit/drawer/__snapshots__/demo.test.js.snap
test/unit/form/__snapshots__/demo.test.js.snap
test/unit/input/__snapshots__/demo.test.js.snap
test/unit/input/__snapshots__/index.test.js.snap
test/unit/message/__snapshots__/demo.test.js.snap
test/unit/popup/__snapshots__/demo.test.js.snap
test/unit/select/__snapshots__/demo.test.js.snap
test/unit/time-picker/__snapshots__/demo.test.js.snap
test/unit/transfer/__snapshots__/demo.test.js.snap
test/unit/tree-select/__snapshots__/demo.test.js.snap
test/unit/tree-select/__snapshots__/index.test.js.snap
test/unit/tree/__snapshots__/demo.test.js.snap

增加左侧、右侧文本。子仓库变更：https://github.com/Tencent/tdesign-common/pull/52
issue #81

feat(input): 增加左侧、右侧文本

---

CHANGELOG.md
examples/radio/radio.md
src/radio/group.tsx
src/radio/props.ts
src/radio/radio-group-props.ts
src/radio/radio.tsx
src/radio/type.ts

feat(radio): add support for allowUncheck

---

src/table/base-table/table-body.tsx

-Table: 合并单元格问题 #125
**brefore**
.....
**after**
......

fix(table): 合并单元格问题 #125

---

src/table/base-table/index.tsx
src/table/base-table/table-body.tsx
src/table/primary-table/index.tsx

修复使用firstFullRow和lastFullRow属性无效的问题。这两个属性在组件传递过程中丢失了，导致最终使用这两个属性的渲染函数拿到的是null
fix #113
- Table: 修复使用firstFullRow和lastFullRow属性无效的问题，[pr#124](https://github.com/Tencent/tdesign-vue/pull/124)，[@xiecz123](https://github.com/xiecz123)

fix(table): 修复使用firstFullRow和lastFullRow属性无效的问题。

---

src/index.ts

兼容IE，打包构建后的组件列表存在__proto__属性且为null(es/index.js)，Object.keys在IE浏览器下会将__proto__属性也输出，从而导致代码在IE浏览器下报错

fix: 兼容IE，构建后的组件列表存在__proto__属性，Object.keys在IE浏览器下会将__proto__属性也输出，从而导致代码在IE浏览器下报错

---

examples/tree/demos/filter.vue

tree:修复tree 组件 可过滤树功能示例，[pr#157](https://github.com/Tencent/tdesign-vue/pull/157)， [#156 ](https://github.com/Tencent/tdesign-vue/issues/156)[@YFAnt](https://github.com/YFAnt)
--------
**brefore**
.....
<t-input v-model="filterText" @input="onInput"/>
**after**
<t-input v-model="filterText" @input.native="onInput"/>
......

@156 修复可过滤的树示例

---

examples/cascader/cascader.md
examples/cascader/demos/value-type.vue
src/cascader/cascader.tsx
src/cascader/components/InputContent.tsx
src/cascader/interface.tsx
src/cascader/props.ts
src/cascader/type.ts
src/cascader/utils/helper.ts
src/cascader/utils/inputContent.ts
src/cascader/utils/panel.ts
test/ssr/__snapshots__/ssr.test.js.snap
test/unit/cascader/__snapshots__/demo.test.js.snap

- Component Name: cascader suport value-type 
--------
**after**
......

feat(cascader): cascader add value type

---

src/tag/tag.tsx

- Tag：全局配置，自定义关闭图标后，关闭图标点击事件失效，[pr#198](https://github.com/Tencent/tdesign-vue/pull/198)，[@chaishi](https://github.com/chaishi)

fix(tag): add click event to custom icon in tag component

---

src/table/base-table/index.tsx

- Table：空表格高度与 API `height` 保持一致，[pr#200](https://github.com/Tencent/tdesign-vue/pull/200)，[issue#194](https://github.com/Tencent/tdesign-vue/issues/194)[@realyuyanan](https://github.com/realyuyanan)
--------
**brefore**
**after**

fix(table): 空表格高度与API height 保持一致 #194

---

src/calendar/calendar.tsx

月份下拉框参数透传传错了（传成了年份下拉框的参数），已修复。

fix(calendar): 修复日历组件中月份下拉框组件参数透传错误的问题

---

package.json

升级icon包 0.0.6到0.0.7没什么变动 只是支持了一下es-check到es5
改为~ 针对一些bug fix可以平滑升级

chore: upgrade icon package version

---

examples/drawer/demos/no-mask.vue
examples/table/demos/async-loading.vue
examples/table/table.md
src/drawer/drawer.tsx
src/table/base-table-props.ts
src/table/base-table/index.tsx
src/table/base-table/table-body.tsx
src/table/enhanced-table-props.ts
src/table/primary-table-props.ts
src/table/primary-table/index.tsx
src/table/primary-table/mixins/async-loading.tsx
src/table/primary-table/mixins/expand.tsx
src/table/primary-table/mixins/filter.tsx
src/table/primary-table/mixins/select.tsx
src/table/type.ts
test/ssr/__snapshots__/ssr.test.js.snap
test/unit/table/__snapshots__/demo.test.js.snap

子仓库变更：https://github.com/Tencent/tdesign-common/pull/112
- Table：修复过滤功能不显示空数据元素问题，[pr#197](https://github.com/Tencent/tdesign-vue/pull/197)，[issue#178](https://github.com/Tencent/tdesign-vue/issues/178)，[commit](https://github.com/Tencent/tdesign-vue/pull/197/commits/72fd400ab395986b496b087ea03fa3eb2290326e)，[@chaishi](https://github.com/chaishi)
- Table：为了保证每次展开的数据最新，展开行不再进行预渲染，如果有预渲染需求，后期再新增，[pr#197](https://github.com/Tencent/tdesign-vue/pull/197)，[issue#199](https://github.com/Tencent/tdesign-vue/issues/199)，[@chaishi](https://github.com/chaishi)
- Drawer：支持 SSR，[pr#197](https://github.com/Tencent/tdesign-vue/pull/197)，[@chaishi](https://github.com/chaishi)
- Table: 异步加载功能重构，之前使用 Provider 渲染，现更为使用 `lastFullRow` 渲染，[commit](https://github.com/Tencent/tdesign-vue/pull/197/commits/656802f …

Fix table filter can not show empty data element

---

src/popup/popup.tsx
src/utils/helper.ts

- tpopup: 兼容 tpopup 组件使用的 @popperjs/core 库在 ie9 下不兼容 transform 导致弹出框错位的问题，修改为 ie9 浏览器下使用 top,right,bottom,left 定位。[pr#210](https://github.com/Tencent/tdesign-vue/pull/210)  [wwervin72](https://github.com/wwervin72)

fix(ie-tpopup): 兼容 @popperjs/core ie9下不支持 transform 的问题

---

site/src/components/page.vue

fix #238
before:
切换版本会打开新的tab页，会导致当前的tab页的版本显示错误
after
切换版本仍然会打开新的tab页，但当前tab页版本不变(参考了tdesign-react)

fix(site): changeVersion behavior

---

src/input/input.tsx

- 组件名称：修复Input组件回车事件在IE浏览器下失效的问题，[pr#268](https://github.com/Tencent/tdesign-vue/pull/268)，[smile33](https://github.com/smile33)
--------
**brefore**
IE下 code为undefined，无法识别enter事件，会导致触发keydown事件。需改为key字段
.....
**after**
可以识别enter事件
......

fix(input): 兼容IE9，修复input 在IE下 enter事件无效问题

---

package.json
test/ssr/__snapshots__/ssr.test.js.snap
test/unit/input-number/__snapshots__/demo.test.js.snap
test/unit/input-number/__snapshots__/index.test.js.snap
test/unit/menu/__snapshots__/demo.test.js.snap
test/unit/slider/__snapshots__/index.test.js.snap
test/unit/tree-select/__snapshots__/demo.test.js.snap
test/unit/tree-select/__snapshots__/index.test.js.snap

- 修复t-icon在ssr中渲染问题
- fix: `middle`改为`medium`

fix icon server side render

---

script/rollup.config.js
src/index.ts

common pr: https://github.com/Tencent/tdesign-common/pull/141
修复 umd 产物 tdesign.css 中没有 theme/_index.less 中声明的 css variables 的问题 fix issue #222 。
--------
**brefore**
每个组件样式都引入了 base.less，如 https://github.com/Tencent/tdesign-common/blob/develop/style/web/components/button/_index.less#L1
base.less 中有引入 global.less
按需引入组件时，引入了几个就会重复引入几次 global 中全局样式，需要用户自己在项目中 shanking 掉
.....
**after**
在 src/index.js 中显示引入  `src/style/index.js`，保持跟 es/esm 中引入方式一样，后续新增样式文件只在 src/style/index.js 中维护即可。
构建产物：
......

feat: import common css in index.js

---

src/slider/slider-button.tsx

- slider: 移除 slider-button的 disabled 属性，以兼容 slider disabled 状态时，ie9下鼠标移入button无法显示tooltip的问题。[pr#280](https://github.com/Tencent/tdesign-vue/pull/280)  [wwervin72](https://github.com/wwervin72)

fix(ie-slider): 去掉slider-button的disabled属性，以兼容ie9下事件触发

---

src/select/select.tsx

- 组件名称：select下拉选择框：修复visible-change关闭下拉框之后不触发问题，[issue#274 ](https://github.com/Tencent/tdesign-vue/issues/274)，[pr#281](https://github.com/Tencent/tdesign-vue/pull/281)，[xiewenxia](https://github.com/xiewenxia)

fix(select):修复visible-change关闭后不触发问题。#274

---

script/rollup.config.js
src/index-lib.ts
src/index.ts

https://github.com/Tencent/tdesign-vue/pull/271 中没有考虑 es/esm 产物入口文件中 postcss 也处理了引入的 style 的问题，本 pr 里修改引入样式入口到 index-lib 中，避免不必要的样式构建
--------
**brefore**
.....
**after**
......

feat: style import in lib

---

src/table/primary-table/expand-box.tsx
test/ssr/__snapshots__/ssr.test.js.snap
test/unit/table/__snapshots__/demo.test.js.snap

- Table：处理IE浏览器下 display:flex兼容问题导致的icon图标展开漂移问题。，[brianzhang](https://github.com/brianzhang)

fix: 修复IE下展开icon位置漂移问题

---

examples/steps/demos/icon.vue
examples/table/demos/base.vue
examples/table/table.md
src/table/base-table-props.ts
src/table/base-table/index.tsx
src/table/base-table/table-body.tsx
src/table/base-table/table-cell.tsx
src/table/base-table/table-row.tsx
src/table/enhanced-table-props.ts
src/table/primary-table-props.ts
src/table/type.ts

- Table：新增事件 `onCellClick`，[pr#297](https://github.com/Tencent/tdesign-vue/pull/297)，[#240](https://github.com/Tencent/tdesign-vue/issues/240)，[@chaishi](https://github.com/chaishi)

add cell click event to table

---

src/tree/util.ts

- Tree：IE 下第一次点击icon出现`Error in v-on handler: "TypeError: 对象不支持“getAttribute”属性或方法"` 问题修复处理，[#311](https://github.com/Tencent/tdesign-vue/issues/311)，[brianzhang](https://github.com/brianzhang)

fix(tree/util.ts): fix: ie getAttribute null

---

examples/input-number/demos/align.vue
examples/input-number/input-number.md
examples/input/demos/align.vue
examples/input/input.md
src/input-number/input-number.tsx
src/input-number/props.ts
src/input-number/type.ts
src/input/input.tsx
src/input/props.ts
src/input/type.ts
test/ssr/__snapshots__/ssr.test.js.snap
test/unit/input-number/__snapshots__/demo.test.js.snap
test/unit/input-number/__snapshots__/index.test.js.snap
test/unit/pagination/__snapshots__/demo.test.js.snap
test/unit/slider/__snapshots__/index.test.js.snap

关联子仓库 PR：https://github.com/Tencent/tdesign-common/pull/165
- Input：支持 `align` 对齐方式，[pr#320](https://github.com/Tencent/tdesign-vue/pull/320)，[issue#293](https://github.com/Tencent/tdesign-vue/issues/293)，[@chaishi](https://github.com/chaishi)
- InputNumber：支持 `align` 对齐方式，[pr#320](https://github.com/Tencent/tdesign-vue/pull/320)，[issue#293](https://github.com/Tencent/tdesign-vue/issues/293)，[@chaishi](https://github.com/chaishi)

feat(input&input-number): add align property to input and input-number

---

examples/comment/demos/reply-form.vue
test/ssr/__snapshots__/ssr.test.js.snap

- comment：解决因textarea样式变更导致comment中reply-form示例回复按钮间距消失的问题，[@dreamsqin ](https://github.com/dreamsqin)
--------
**brefore**
**after**

fix(comment): resolve margin disappearing because of textarea changes

---

src/tree-select/tree-select.tsx

- TreeSelect：
- IE9 ERROR: Unhandled promise rejection TypeError: 无法获取未定义或 null 引用的属性“data”
- [brianzhang](https://github.com/brianzhang)
fix code:
```js
const node = (tree as any).getItem(nodeValue);
if (!node) return;
```

fix: 修复select-dvalne初始化node为null ie 下报错问题

---

src/input-number/input-number.tsx

- 组件名称：修复input-number组件回车事件在IE浏览器下失效的问题，[smile33](https://github.com/smile33)
--------
**brefore**
IE下 code为undefined，无法识别enter事件，会导致触发keydown事件。需改为key字段
.....
**after**
可以识别enter事件
......

fix: 兼容IE9，修复input-number 在IE下 enter事件无效问题

---

examples/calendar/demos/events.vue
src/calendar/calendar.tsx

目前日历组件monthChange事件只通过右上角的年月份下拉框触发，实际上点击“今天”、“本月”，或者通过代码给value属性赋值等操作也可能触发月份变化
ps：commit message 中事件名写错了··· 是monthChange

fix(calendar): fix: 修复日历组件monthChange事件在年只通过月份下拉框触发的问题

---

src/select/select.tsx
src/time-picker/panel/index.tsx

- Select：优化 options 的初始化解析，[pr 344](https://github.com/Tencent/tdesign-vue/pull/344)，[@ikeq](https://github.com/ikeq)
- TimePicker：优化 panel 定位时机，[pr 344](https://github.com/Tencent/tdesign-vue/pull/344)，[@ikeq](https://github.com/ikeq)
--------
**brefore**
select: options 提取完全依赖 children 挂载 
**after**
- select: 在 children 挂载前做一次 options 的提取
- time-picker：提升一点健壮性
**PS**: 此 PR 应不会对组件目前的行为产生任何影响，是配合 Popup 组件做改动

feat: Select & TimePicker 小优化

---

examples/config-provider/config-provider.md
examples/form/demos/validate-message.vue
examples/form/form.md
src/config-provider/en_US_config.ts
src/config-provider/type.ts
src/config-provider/zh_CN_config.ts
src/form/form-item.tsx
src/form/props.ts
src/form/type.ts
test/ssr/__snapshots__/ssr.test.js.snap

- Form：支持全局配置校验错误信息，支持组件统一配置校验错误信息，[pr xxx](pr地址)，[issue#313](https://github.com/Tencent/tdesign-vue/issues/313)，[@chaishi](https://github.com/chaishi)
--------

Form 组件：支持全局配置校验错误信息，支持组件统一配置校验错误信息

---

src/drawer/drawer.tsx
test/ssr/__snapshots__/ssr.test.js.snap
test/unit/drawer/__snapshots__/demo.test.js.snap

- 修复drawer组件esc相关事件触发问题
- fix:  https://github.com/Tencent/tdesign-vue/issues/380
- tabindex需要设置 div元素才可以触发keydown事件，refer to:https://developer.mozilla.org/zh-CN/docs/Web/HTML/Global_attributes/tabindex 
- fix(drawer): 修复drawer组件keydown相关事件不触发的问题

fix(drawer): trigger keydown event

---

src/textarea/textarea.tsx

fix #387
日常 bug 修复 
https://github.com/Tencent/tdesign-vue/issues/387
- fix(textarea): 解决value未定义时初始长度为9

fix(textarea): 解决value未定义时初始长度为9

---

src/progress/progress.tsx
test/ssr/__snapshots__/ssr.test.js.snap
test/unit/progress/__snapshots__/demo.test.js.snap

fix #368
日常 bug 修复
https://github.com/Tencent/tdesign-vue/issues/368
https://github.com/Tencent/tdesign-vue/issues/368
fix(progress): 修复环形进度条不可更改未完成轨道颜色问题

fix(progress): 修复环形进度条不可更改未完成轨道颜色问题

---

examples/menu/menu.md
src/menu/head-menu-props.ts
src/menu/menu-group-props.ts
src/menu/menu-item-props.ts
src/menu/menu.tsx
src/menu/props.ts
src/menu/submenu-props.ts
src/menu/type.ts

日常 bug 修复
resolve #396 
- fix(menu): 修复 expandType 没有动态变化的问题
- fix(menu): 移除冗余事件 collapsed

fix(menu): resolve expandType correctly

---

src/popup/container.tsx
src/popup/popup.tsx
src/select/select.tsx
test/ssr/__snapshots__/ssr.test.js.snap

- fix(select): 修复多选时 options 初始化解析失败
- fix(select): 优化空样式
- fix(popup): 修复 content 事件导致的可能需多次点击进行关闭
- fix(popup): 修复 popup 触发元素尺寸变化后位置不更新

fix(select): Improve options initial parsing logic

---

examples/input/demos/format.vue
examples/input/demos/max-length-count.vue
examples/input/input.md
src/input/input.tsx
src/input/props.ts
src/input/type.ts

feat(input): 增加format属性

---

examples/drawer/demos/placement.vue
src/drawer/drawer.tsx
test/ssr/__snapshots__/ssr.test.js.snap
test/unit/drawer/__snapshots__/demo.test.js.snap

- 用户反馈，sizeDraggable未实现
- sizeDraggable打开时，增加一个侧边（right/left) 或顶边（bottom)或底边（top) 的节点，拖动时改变drawer的size
- feat(drawer): 支持sizeDraggable API, 支持用户拖动改变drawer大小

feat drawer support sizeDraggable 

---

examples/upload/demos/file-flow-list-batch-upload.vue
examples/upload/upload.md
src/upload/flow-list.tsx
src/upload/props.ts
src/upload/type.ts
src/upload/upload.tsx
test/ssr/__snapshots__/ssr.test.js.snap
test/unit/upload/__snapshots__/demo.test.js.snap
test/unit/upload/__snapshots__/index.test.js.snap
test/unit/upload/demo.test.js
test/unit/upload/index.test.js

暂无
具体场景：
多文件上传时， 可以支持一个请求包含多个文件同时上传的能力。当前 TD 只支持单文件上传的模式。
增加新的API：
* uploadAllFilesInOneRequest: 上传时是否只使用一个接口上传所有的文件，需配合 multiple 使用。
* batchUpload: 是否为合并上传模式，配合 multiple 与 uploadAllFilesInOneRequest 一起使用。当处于合并上传模式时，每次选择上传文件都会清空已上传的文件列表，等待再次合并上传。
注：需要配合 tdesign-common 的 PR 共同使用
[#267 feat: 用于支持单个请求可以上传多个文件](https://github.com/Tencent/tdesign-common/pull/267)
- feat(Uploader): 支持一个请求合并上传文件

feat: 用于支持 Uploader 批量合并上传功能

---

src/cascader/utils/item.ts

日常 bug 修复 
class 绑定了字符串和children，导致了traverse 不断触发
https://github.com/Tencent/tdesign-vue/issues/477
class 内容实用字符串，children导致

fix: class must be true/false

---

src/select/option.tsx
src/select/select.tsx

fix #495
#495  [select]select的下拉选项没跟随options slot改变而变化
select的下拉选项没跟随options slot改变而变化
- fix(select): 修复选项无法跟随options slot改变而变化

fix(select): fix slot options update

---

src/form/form-item.tsx

之前的写法只是简单的做了取反，实际上应该是 message 未定义才需要提供默认值。
https://github.com/Tencent/tdesign-vue/issues/520
- fix(Form): 当 rule message 为空时，不显示具体的文案

fix: 对齐 formRules 对 message 的实现

---

src/cascader/utils/item.ts
src/input/input.tsx
src/tree-select/tree-select.tsx
test/ssr/__snapshots__/ssr.test.js.snap
test/unit/select/__snapshots__/demo.test.js.snap
test/unit/tag-input/__snapshots__/demo.test.js.snap
test/unit/tree-select/__snapshots__/demo.test.js.snap
test/unit/tree-select/__snapshots__/index.test.js.snap

关联common修复PR：
https://github.com/Tencent/tdesign-common/pull/286
https://github.com/Tencent/tdesign-common/pull/287
修复因select，重构导致的样式问题
before
after
before
after
- fix: cascade可选任意一级缺少高亮状态。 https://github.com/Tencent/tdesign-vue-next/issues/114

fix(tree-select): add tree-select class polyfill

---

examples/input-number/demos/auto-width.vue
examples/input-number/demos/status.vue
src/input-number/input-number.tsx
src/input-number/props.ts
src/input-number/type.ts
test/ssr/__snapshots__/ssr.test.js.snap
test/unit/input-number/__snapshots__/demo.test.js.snap
test/unit/input-number/__snapshots__/index.test.js.snap
test/unit/pagination/__snapshots__/demo.test.js.snap
test/unit/slider/__snapshots__/index.test.js.snap

- 日常 bug 修复：修复由于新增tips导致的column theme的样式错误 
- 新特性提交：新增autoWidth，统一InputNumber中的Input使用Input组件 减少重复实现
- 演示代码改进：新增autoWidth的演示demo
- 修复decimal计算错误
- fix typo : inputing -> inputting
- feat(input-number): 支持autoWidth属性

fix input number tips and support autowidth

---

src/date-picker/date-picker.tsx

表单里面日期选择器组件的校验信息，还没提交就出来了
复现 demo: https://codesandbox.io/s/tdesign-vue-demo-forked-10lxi3?file=/src/demo.vue
- fix(Datepicker): 修复 Form 中使用时，触发校验时机错误的问题

fix: datepicker init validate

---

src/cascader/components/Item.tsx

resolve #561
修复文字过长时不显示 tooltip
before
after
- fix(cascader): 修复文字过长时不显示 `tooltip`

fix: cascader ellipisis tooltip

---

src/input/input.tsx

fix #580
#580 
需要和原生浏览器保持一致，当前仅会触发 blur 事件，不会触发 focus 事件
- fix(Input): focus 事件触发不应该因为 readonly 而停止 emit

fix(input): input readonly not emit focus

---

src/button/button.tsx

之前为了解决ie9下disabled属性会让文字的覆盖样式失效，把disabled属性给去掉了，可这样影响到了事件的禁用。
所以优先功能，去掉删除disabled这个方案。
- fix(button): 去掉删除disabled

fix: 去掉在ie9中会删除disabled属性

---

src/progress/progress.tsx
test/unit/progress/__snapshots__/index.test.js.snap
test/unit/progress/index.test.js

- 日常 bug 修复
- 增加plump相关更细分的单测
- https://github.com/Tencent/tdesign-vue/issues/569
- fix(progress): theme为plump时percent为10没有展示文案

fix(progress): display text when percent value=10

---

examples/input/input.md
examples/select-input/demos/custom-tag.vue
src/cascader/cascader.tsx
src/cascader/utils/cascader.ts
src/cascader/utils/helper.ts
src/common.ts
src/config-provider/context.ts
src/config-provider/index.ts
src/config-provider/useConfig.tsx
src/input/input.tsx
src/input/props.ts
src/input/type.ts
src/select-input/select-input.tsx
src/select-input/useMultiple.tsx
src/select-input/useSingle.tsx
src/tag-input/tag-input.tsx
src/textarea/textarea.tsx
src/time-picker/time-picker.tsx
src/upload/upload.tsx
test/ssr/__snapshots__/ssr.test.js.snap
test/unit/select/__snapshots__/demo.test.js.snap
test/unit/tag-input/__snapshots__/demo.test.js.snap
test/unit/textarea/__snapshots__/demo.test.js.snap
test/unit/tree-select/__snapshots__/demo.test.js.snap
test/unit/tree-select/__snapshots__/index.test.js.snap

关联common PR https://github.com/Tencent/tdesign-common/pull/325
**TimePicker focused 态样式修复**
before
after
**DatePicker focused 态样式修复**
before
after
- refactor(input):
-  外部传入样式挂载至 `t-input__wrap`, breaking-change
-  feat(input): 增加 inputClass API，用于透传class到 t-input 同级
- refactor(textarea): 去除 `t-textarea__wrap`, breaking-change
- fix(date-picker): focused 态样式修复
- fix(time-picker): focused 态样式修复
- fix(upload): 修复upload组件 method props 失效
- fix(select-input): 
- 修复在非输入状态下无focused态
- 修复在非输入状态下不能显示清除按钮
- 修复在`single`模式下inputValue 的受控表现
- fix(cascader): 
- 修复value为number类型时无法回显 https://github.com/Tencent/tdesign-vue/issues/619
-  修复动态改options为空数组不生效 https://github.com/Tencent/tdesign-vue/issues/467

refactor(input): refactor input wrap

---

src/calendar/calendar.tsx

日历组件代码优化，解决年月模式切换到过程中单元格高亮会闪烁的问题。
问题原因是v-for的key没有完全区分开。

fix: 日历组件代码优化，解决年月模式切换到过程中单元格高亮会闪烁的问题

---

examples/upload/demos/file-flow-list-duplicate.vue
examples/upload/upload.md
src/common.ts
src/upload/flow-list.tsx
src/upload/props.ts
src/upload/type.ts
src/upload/upload.tsx
src/upload/util.ts
test/ssr/__snapshots__/ssr.test.js.snap
test/unit/upload/__snapshots__/demo.test.js.snap
test/unit/upload/demo.test.js

- Upload 组件新增：`allowUploadDuplicateFile` 属性支持重复文件名的文件上传
- fix(upload): 新增：`allowUploadDuplicateFile` 属性，支持重复文件名的文件上传

feat(upload): add allowUploadDuplicateFile props

---

examples/select-input/demos/collapsed-items.vue
examples/select-input/demos/excess-tags-display-type.vue
examples/select-input/demos/multiple.vue
src/select-input/useSingle.tsx

before
after
- fix(select-input): 修复单选可输入状态下的 `focus` 时 `inputvalue ` 的错误
- feat(select-input): 实现 `enter` 事件
- docs: 修复文档demo样式

fix: select-input demo style and input focus inputValue

---

src/upload/upload.tsx
src/upload/util.ts

```js
innerFiles.forEach((file) => {
file.percent = Math.min(percent, 100);
this.loadingFile = file.status === 'success' ? null : file;
});
```
添加文件status状态判断
- fix(upload): 处理 `success` 事件先于 `progress` 事件触发时，上传文件 `loadingFile` 值不正确的场景
- fix(upload): 处理最大数量限制 `max` 在多次文件选择中判断不正确问题

【Upload】 fix: 修复handleProgress file状态判断

---

src/tree-select/tree-select.tsx

https://github.com/Tencent/tdesign-vue/issues/622
1.解决透传treeProps时，同时使用keys、load属性导致的选中项显示问题
2.问题的是getTreeNode方法里调用的getTreeData方法返回nodes时没使用keys里的属性别名来命名label、value
3.解决方案是getTreeData方法返回nodes时使用keys里的属性别名来命名label、value
- fix(tree-select):  修复treeProps同时使用keys、load的选中项显示问题

fix(tree-select):  修复treeProps同时使用keys、load的选中项显示问题

---

src/table/tr.tsx

- fix(Table): 处理IE浏览器下无`IntersectionObserver`方法，无法调用回调函数执行方法的兼容问题

fix: Ie not method IntersectionObserver

---

src/pagination/pagination.tsx
test/ssr/__snapshots__/ssr.test.js.snap
test/unit/config-provider/__snapshots__/demo.test.js.snap
test/unit/pagination/__snapshots__/demo.test.js.snap
test/unit/table/__snapshots__/demo.test.js.snap

inputnumber 未配置 placeholder 时会有默认文案填充：
pagination 中引入 inputnumber 时需要手动设置 placeholder 为空
- fix(Pagination): 修复跳转页输入框展示了额外 placeholder 默认内容的问题
- [] 本条 PR 不需要纳入 Changelog

fix: pagination inputnumber placeholder

---

src/tree-select/tree-select.tsx

fix #617
fix #617
TreeSelect 与常规的 Select 的交互行为展现不符，多次点击可以取消当前选择，该 PR 用于修复该问题，让 TreeSelect 的交互行为更加接近 Select 组件。
- fix(TreeSelect): 修正 TreeSelect 的交互行为，与 Select 保持一致。

fix(treeselect): click twice will disapear select value

---

examples/input-number/demos/align.vue
src/table/filter-controller.tsx
src/table/tbody.tsx
src/table/tr.tsx
test/ssr/__snapshots__/ssr.test.js.snap

common pr: https://github.com/Tencent/tdesign-common/pull/342

Fix inputnumber width and SSR render

---

src/dialog/actions.tsx
src/popconfirm/popconfirm.tsx

before
after
- fix(popConfirm): 修复popConfirm默认按钮大小为small

fix: popconfirm button size

---

examples/dropdown/demos/multiple.vue
src/popup/container.tsx
src/popup/popup.tsx

- fix(popup): content 尺寸变化后自动更新位置
- docs(dropdown): 优化示例文案

fix(popup): content 尺寸变化后自动更新位置

---

examples/slider/demos/base.vue
examples/slider/demos/input-number.vue
examples/slider/slider.md
src/slider/props.ts
src/slider/slider-button.tsx
src/slider/slider.tsx
src/slider/type.ts
test/ssr/__snapshots__/ssr.test.js.snap
test/unit/checkbox/index.test.js
test/unit/slider/__snapshots__/index.test.js.snap
test/unit/slider/index.test.js

- 日常 bug 修复 slider组件 inputNumberProps失效
- 测试用例 增加Slider组件的单测
- 相关PR：https://github.com/Tencent/tdesign-common/pull/376
- https://github.com/Tencent/tdesign-vue/issues/585
- https://github.com/Tencent/tdesign-vue-next/issues/544
- fix(slider): inputProps属性属性问题
- feat(slider): label为function新增`value`和`position`参数

fix(slider): inputnumberProps

---

src/date-picker/date-picker.tsx
src/time-picker/time-picker.tsx
src/time-picker/time-range-picker.tsx

- 日常 bug 修复 修复time-picker手动情况value的异常
- 修复点击clear按钮 timepicker和datepicker样式的异常
- fix(timepicker): 修复time-picker手动清空value的异常

fix(timepicker): clear value reset current time

---

src/cascader/components/InputContent.tsx
src/cascader/utils/inputContent.ts

过滤状态下的交互问题
- fix(cascader):
- 修复可过滤状态下的下拉面板拉起闪烁
- 修复可过滤状态下的输入内容未被正常销毁

fix: cascader filter

---

examples/collapse/collapse.md
examples/collapse/demos/base.vue
examples/collapse/demos/icon.vue
examples/collapse/demos/mutex.vue
examples/collapse/demos/other.vue
examples/collapse/demos/rightSlot.vue
site/site.config.mjs
src/collapse/collapse-panel-props.ts
src/collapse/collapse-panel.tsx
src/collapse/collapse.tsx
src/collapse/index.ts
src/collapse/props.ts
src/collapse/style/css.js
src/collapse/style/index.js
src/collapse/type.ts
src/collapse/useCollapseAnimation.ts
src/components.ts
test/ssr/__snapshots__/ssr.test.js.snap
test/unit/collapse/__snapshots__/demo.test.js.snap
test/unit/collapse/demo.test.js

feat: add collapse component

---

src/select/option.tsx
src/select/select.tsx
test/ssr/__snapshots__/ssr.test.js.snap
test/unit/calendar/__snapshots__/demo.test.js.snap
test/unit/calendar/__snapshots__/index.test.js.snap
test/unit/config-provider/__snapshots__/demo.test.js.snap
test/unit/pagination/__snapshots__/demo.test.js.snap
test/unit/select/__snapshots__/demo.test.js.snap
test/unit/select/__snapshots__/index.test.js.snap
test/unit/table/__snapshots__/demo.test.js.snap
test/unit/transfer/__snapshots__/demo.test.js.snap

Fixes #769 
目前select选中项和select的下拉项中均有title属性， 并且没有提供相应控制。
由于业务上需要自定义提示信息样式，经讨论去掉select选中和下拉项中的title属性
- fix(select): 去掉select选中和下拉项中的title属性

fix(select): 去掉select选中和下拉项中的title属性

---

examples/dialog/dialog.md
src/dialog/props.ts
src/dialog/type.ts

- fix(dialog): 修复 `alert` 类型错误

fix: dialog alert  ts error

---

examples/popup/popup.md
examples/tooltip/demos/mouse.vue
examples/tooltip/tooltip.md
examples/tooltip/usage/props.json
src/popup/props.ts
src/popup/type.ts
src/tooltip/props.ts
src/tooltip/tooltip.tsx
src/tooltip/type.ts
test/ssr/__snapshots__/ssr.test.js.snap

#785 
- feat(tooltip): `placement` 新增 `mouse` 枚举值，用于支持基于鼠标位置定位

feat(tooltip): set placement by mouse

---

examples/slider/slider.md
src/select/select.tsx
src/slider/type.ts

- 日常 bug 修复
- https://github.com/Tencent/tdesign-vue/issues/841
- fix(Select): 修复textarea作为panelContent时无法使用键盘事件的问题
- fix(Slider): 修复`InputProps`属性传递布尔值时ts错误的问题

fix(Select): textarea keyboard event is prevented as panelContent

---

src/dialog/dialog.tsx

- 日常 bug 修复 修复Dialog默认都加入lock的问题
- fix(Dialog): 修复`normal`下加入lock导致页面无法滚动的问题
- feat(Dialog): 支持`preventScrollThrough` API

fix(dialog): dialog lock when preventScrollThrough and modal mode

---

examples/steps/steps.md
examples/steps/usage/index.vue
examples/steps/usage/props.json
script/generate-usage/config.js
src/steps/props.ts
src/steps/step-item-props.ts
src/steps/step-item.tsx
src/steps/steps.tsx
src/steps/type.ts
test/ssr/__snapshots__/ssr.test.js.snap
test/unit/config-provider/__snapshots__/demo.test.js.snap
test/unit/steps/__snapshots__/demo.test.js.snap

- feat(Steps): 支持 separator api & 完善反转逻辑

feat(steps): 支持 separator api & 完善反转逻辑

---

src/table/hooks/useColumnResize.tsx
src/table/hooks/useRowSelect.tsx
src/table/primary-table.tsx

Fixes #859 
1. mousemove的时候，target可能是文本, 边缘会出现定位错误
2. 列拖动后，再选中某一行，列拖动后到距离被重置了
- fix(table): 列拖动优化：target定位错误；选中行后列拖动距离被重置问题

[table]列拖动功能优化

---

src/tree-select/tree-select.tsx

Fixes #888 
配置treeProps.keys的children为自定义值。选中子节点， 选中展示的是value值， 应该展示label。
经排查是tree-select未支持自定义的treeProps.keys.children配置
- fix(tree-select): 支持treeProps.keys.children字段配置

fix(tree-select): 支持treeProps.keys.children字段配置

---

src/table/hooks/useFixed.ts

Fixes #909 
table初始化时，fixed的阴影效果没有出现
排查是shadowLastScrollLeft 初始化时设置为0， 而 scrollLeft 也为0，导致初始化时没有更新固定列阴影
- fix(table):  table初始化时，fixed的阴影效果没有出现

fix(table): table初始化时，fixed的阴影效果没有出现

---

src/date-picker/date-picker.tsx
src/date-picker/interface.ts

https://github.com/Tencent/tdesign-vue/issues/958
https://github.com/Tencent/tdesign-vue/issues/964
datepicker中传入popup组件的popupProps实现有误
- fix(datepicker): 修复datepicker组件popupProps传入无效问题

fix(datepicker): 修复datepicker组件popupProps传入无效问题

---

src/table/base-table.tsx
test/ssr/__snapshots__/ssr.test.js.snap
test/unit/table/__snapshots__/demo.test.js.snap

- fix(table): 修复table透传loading size为枚举无效的问题

fix: table loading props enum size

---

src/select/option.tsx
src/select/select.tsx
src/select/util.ts

- #1022
- fix(select):  #修复t-option方式渲染时内部数组的清除逻辑

fix(select): 修复t-option方式渲染时内部数组的清除逻辑

---

src/tag-input/tag-input.tsx

fix #945
https://github.com/Tencent/tdesign-vue/issues/945
- fix(tag-input): 中文输入按下 Enter 时不触发新标签

fix(tag-input): 中文输入按下 Enter 时不触发新标签

---

src/input-number/input-number.tsx
src/input-number/type.ts

fix #1033
[https://github.com/Tencent/tdesign-vue/issues/1033](https://github.com/Tencent/tdesign-vue/issues/1033)
1. 要解决的具体问题：1）enter 事件应从 keypress 监听，keydown 监听不到；2）事件响应出错
2. 列出最终的 API 实现和用法：1）enter 事件转移至 keypress 下监听；2）[PR 541](https://github.com/Tencent/tdesign-vue/pull/541) 将原生 `input` 更新为了 `t-input`，Event 参数需一起由1个变成2个
3. 涉及UI/交互变动需要有截图或 GIF：
修改前：
修改后：
- fix(input-number): enter 等事件响应

fix(input-number): fix events after use t-input

---

script/rollup.config.js
site/docs/getting-started.md
src/select-input/useSingle.tsx
src/table/hooks/useDragSort.ts
src/table/hooks/useFixed.ts
src/table/tbody.tsx

- fix(table): 处理table在部分SSR场景渲染失败的问题
- feat(Table): fullRow不参与排序
- fix(Table): 修复仅有`firstFullRow`不渲染的问题
- fix(SelectInput): 修复展开下拉时失去焦点不高亮的问题
- chore: 更新文档

fix(table): ssr render fail

---

src/input/input.tsx
src/tag-input/tag-input.tsx
test/ssr/__snapshots__/ssr.test.js.snap
test/unit/select/__snapshots__/demo.test.js.snap
test/unit/select/__snapshots__/index.test.js.snap

- https://github.com/Tencent/tdesign-vue/issues/1089
- fix(Select): 修复多选模式下展示placeholder的异常
- fix(Select): 修复可筛选换行高度异常的问题

fix select multiple mode

---

src/config-provider/config-provider.tsx
src/config-provider/context.ts
src/config-provider/useConfig.tsx

…导致卡顿的性能问题
目前在内存较大的页面再 window.open() tdesign 的表格组件，此时会卡顿，最根本原因是 config-provider 提供了两种 provide，导致有冲突，改成一种形式即可解决
- fix(ConfigProvider): 修复 config-provider 同时存在 provide 和 setup#provide 导致卡顿的性能问题

fix(ConfigProvider): 修复 config-provider 同时存在 provide 和 setup#provide 导致卡顿的性能问题

---

src/config-provider/useConfig.tsx

fix: 更改 useConfig computed属性计算导致列表渲染卡顿问题

---

src/input/input.tsx

修复Input 组件 切换 type 后不生效的问题，官网 Input 中组件示例 选择 type 切换时 Input 中的 type 不会变化。
1. 修复Input 组件 切换 type 后不生效的问题，官网 Input 中组件示例 选择 type 切换时 Input 中的 type 不会变化。
2. 添加watch
3. 复现地址：https://tdesign.tencent.com/vue/components/input 示例中切换 type 即可复现
- fix(Input): 修复Input 组件 切换 type 后不生效的问题。

fix(Input): 修复Input 组件动态 切换 type 后不生效的问题

---

site/docs/getting-started.md

- https://github.com/Tencent/tdesign-vue/issues/1152
- 增加更多的文档说明 避免用户使用2.7版本使用异常

docs: update docs for 2.7

---

src/select-input/select-input.tsx

- fix(SelectInput): 修复透传 disabled 失效问题

fix: 修复 select-input 透传 disabled 失效问题

---

src/table/hooks/useColumnResize.ts

https://github.com/Tencent/tdesign-vue/issues/1067
解决问题：由于计算精度问题，导致拖拽的宽度和minWidth/maxWidth有一点偏差，无法出发二次拖拽事件
- fix(table): 表格列宽拖拽到最大或最小时，有可能无法二次拖拽

【修复】表格列宽拖拽到最大或最小时，有可能无法二次拖拽

---

src/table/hooks/useRowSelect.tsx

修复可选中行table组件，data为空数据时，默认全选按钮会选中的问题
PR来源： https://github.com/Tencent/tdesign-vue-next/pull/1188
修复后
原因
对空数据没进行判断
解决方案
对空数据做处理
- fix(Table): 修复可选中行 `table` 组件，`data` 为空数据时，默认全选按钮会选中的问题

fix(table): 修复可选中行table组件，data为空数据时，默认全选按钮会选中的问题

---

src/table/base-table.tsx

IE 下，滚动条高度计算相差4像素，导致吸顶header不能盖住滚动条
- fix(table): 兼容IE滚动条高度计算覆盖不全问题

fix: 兼容IE滚动条高度计算覆盖不全问题

---

src/date-picker/DateRangePicker.tsx
src/date-picker/hooks/useRange.ts
src/date-picker/hooks/useSingle.ts
src/select-input/useOverlayStyle.ts

- fix(`DatePicker`): 修复重置日期后面板月份未重置问题 

fix: 修复重置日期后面板月份未重置问题

---

src/table/hooks/useRowSelect.tsx

列拖动后，选择行导致拖动后的距离被重置问题
https://github.com/Tencent/tdesign-vue/issues/859#issuecomment-1123176523
- fix(table): 列拖动后，选择行导致拖动后的距离被重置

fix(table): 列拖动后，选择行导致拖动后的距离被重置

---

examples/select-input/usage/props.json
src/select-input/select-input.tsx
src/select-input/useOverlayStyle.ts

https://github.com/Tencent/tdesign-react/issues/919
react 对应修改：https://github.com/Tencent/tdesign-react/pull/1174
vue-next 对应修改：https://github.com/Tencent/tdesign-vue-next/pull/1299
- feat(SelectInput): SelectInput 及相关的 Select/Cascader/TreeSelect 组件交互调整，再次点击输入框时也可以收起下拉框。

feat: support close popup when double click input area

---

examples/table/demos/affix.vue
examples/table/demos/filter-controlled.vue
examples/table/demos/merge-cells.vue
src/table/base-table.tsx
src/table/hooks/useColumnResize.ts
src/table/hooks/useFixed.ts
src/table/interface.ts
src/table/thead.tsx
test/ssr/__snapshots__/ssr.test.js.snap
test/unit/table/__snapshots__/demo.test.js.snap

#1067 
1. 使用thWidthList记录拖动后的实际列宽
2. 根据拖动结果重新计算其余各列的宽度，使之能够确保列宽总和大于等于表宽
- fix(table): 列宽度和小于表宽的情况下，调整列宽的结果与预期不符

fix(table): 列宽度和小于表宽的情况下，调整列宽的结果与预期不符

---

examples/select/demos/creatable.vue
examples/select/demos/custom-options.vue
examples/select/demos/custom-selected.vue
examples/select/demos/group.vue
examples/select/usage/props.json
src/select/hooks.ts
src/select/hooks/useSelectOptions.ts
src/select/option.tsx
src/select/optionGroup.tsx
src/select/select-panel.tsx
src/select/select.tsx
src/select/util.ts
src/utils/dom.ts
test/ssr/__snapshots__/ssr.test.js.snap
test/unit/calendar/__snapshots__/demo.test.js.snap
test/unit/calendar/__snapshots__/index.test.js.snap
test/unit/config-provider/__snapshots__/demo.test.js.snap
test/unit/pagination/__snapshots__/demo.test.js.snap
test/unit/select/__snapshots__/demo.test.js.snap
test/unit/table/__snapshots__/demo.test.js.snap

- #1039
- #1175
- #1213 
现有的 t-select （父组件）依赖 t-option 在页面渲染出 dom 节点后的生命周期钩子构建内部 options 记录数组。在远程搜索 / 筛选的场景下，可能导致用户传入的 t-option 因原数组为空而无法完成注册、记录异常的问题。
通过将 t-select 自身 slot 进行遍历并代理渲染 t-option 的方式，将父组件的 options 数组依赖自身的 slot 属性，从而解决 options 记录数组数据源冲突的问题，也能一并支持虚拟滚动的场景。
- fix(select): 修复开启虚拟滚动配合自定义面板使用卡顿的问题
- fix(select): 修复使用 t-opiton 自定义选项无法动态筛选问题
- fix(select): 修复 t-opiton 配合远程搜索使用异常的问题
- fix(select): 修复 `empty` 与 `loadingText` 在传参为 `string` 类型时，包裹元素消失的问题
- fix(select): 修复 `loadingText` slot 失效的问题

fix(select): 统一处理options和t-option传入的选项；精简t-option逻辑

---

src/select/hooks/useSelectOptions.ts

- fix(select): 处理 group-option 下 style 和 class 的透传

fix(select): 处理 group-option 下 style 和 class 的透传

---

CHANGELOG.md
src/table/base-table.tsx
src/table/tfoot.tsx

- feat(Table): `footerSummary` 支持通过 Props 属性传入
- [] 本条 PR 不需要纳入 Changelog

add footerSummary to props

---

examples/config-provider/config-provider.en-US.md
examples/config-provider/config-provider.md
src/config-provider/type.ts
src/date-picker/hooks/useTableData.ts

- feat(`DatePicker`): 支持季度国际化配置

feat: 支持季度国际化配置

---

src/color-picker/color-picker-panel.tsx
src/color-picker/panel/index.tsx

fix #1268
- fix(color-picker): 修复color-picker 切换模式卡死问题; 修复panel模式@change事件无法触发问题

fix(color-picker): 修复color-picker 切换模式卡死问题; 修复panel模式@change事件无法触发问题

---

examples/table/demos/editable-row.vue
examples/table/table.en-US.md
examples/table/table.md
src/table/base-table-props.ts
src/table/editable-cell.tsx
src/table/hooks/useEditableRow.ts
src/table/type.ts

- feat(Table): 可编辑行功能，校验函数 validateRowData 和 validateTableData 返回值支持 Promise 对象
- fix(Table): 可编辑单元格，多选和日期选择，点击下拉浮层中的内容会导致退出编辑，[issue#1384](https://github.com/Tencent/tdesign-vue-next/issues/1384)

[Table] set return value of validateRowData and validateTableData to be a Promise ; stopPropagation popup content click bubble to document

---

src/popup/popup.tsx
src/utils/dom.ts

https://github.com/Tencent/tdesign-vue/issues/1146
- fix(popup): 修复嵌套使用点击 trigger 元素时异常关闭

fix(popup): use capturing listener to improve robustness

---

src/date-picker/DateRangePicker.tsx
src/date-picker/panel/PanelContent.tsx
src/date-picker/panel/RangePanel.tsx

- fix(Datepicker): 修复时间面板展示错误
- feat(Datepicker): 区间选择器结束时间调整为默认展示当天最后一秒

fix: 修复时间面板展示错误 & 区间选择器结束时间默认展示当天最后一秒

---

.github/workflows/typos-config.toml
script/rollup.config.js
site/docs/getting-started.md

当前打包版本会将`@vue/composition-api`打入umd的包中 当用户自身项目也使用`@vue/composition-api` Vue无法判断注册过了一次 会出现2次注册的情况 导致项目报错 
将umd版本改为不打包`@vue/composition-api`  由用户手动引入 
- fix(umd): 修复umd版本的使用问题，具体使用方式请参考`浏览器引入`相关文档说明

fix: umd version usage

---

src/select-input/useSingle.tsx

#1241 
select, datePicker,  cascade等组件在配置了clearable时， 如果disabled为true， 依旧可以清空操作。
经排查这些组件都是由selectInput控制， 修改selectInput的showClearIconOnEmpty，让disabled的情况下自动禁止清空按钮
- fix(selectinput): disabled的情况下自动禁止clearable功能

fix(selectinput): disabled的情况下自动禁止clearable功能

---

src/checkbox/checkbox.tsx
src/tree/td-tree.tsx
src/tree/tree-item.tsx

由于checkbox的整个区域都支持点击选中 在tree组件中 与expandOnClickNode存在冲突 即表现为点击checkbox的label 会同时 
触发树的展开 和checkbox的选中 实际项目中 配置expandOnClickNode的用户需要的只是展开节点 而非同时选中 
调整为expandOnClickNode时 叶子节点保持原有交互 非叶子节点点击label只展开 点击输入框为选中
修复前
https://user-images.githubusercontent.com/26377630/184812350-aad2b037-6644-4800-91c7-6f04bad0bbf5.mp4
修复后
https://user-images.githubusercontent.com/26377630/184811964-b4f33af1-5427-4f5a-b9d2-ed3c0e2bd334.mp4
- fix(tree): 修复`expandOnClickNode`点击展开与checkbox点击选中的冲突问题

fix(tree): checkable and expandOnClickNode conflict

---

src/table/base-table.tsx

- fix(Table): [吸顶表头，末尾有 1px 未对齐](https://github.com/Tencent/tdesign-vue-next/issues/1434)

fix(table): affixed header 1px

---

src/table/base-table.tsx
src/table/hooks/useFixed.ts

- https://github.com/Tencent/tdesign-vue/issues/1289
- fix(Table): 固定列阴影样式不能随窗口放大缩小而变化

20220816 feature table

---

examples/dialog/demos/base.vue
examples/dialog/dialog.en-US.md
examples/dialog/dialog.md
src/dialog/dialog.tsx
src/dialog/props.ts
src/dialog/stack.ts
src/dialog/type.ts
test/ssr/__snapshots__/ssr.test.js.snap
test/unit/dialog/__snapshots__/demo.test.js.snap

#1376
[#1376](https://github.com/Tencent/tdesign-vue-next/issues/1376)
[#1159](https://github.com/Tencent/tdesign-vue-next/issues/1159)
[#1249](https://github.com/Tencent/tdesign-vue/issues/1249)
feat(dialog): 支持回车键确认弹框，`onConfirm` 事件参数 `e` 或为键盘事件
feat(dialog): 支持多个弹框同时存在时，通过 `ESC` 键盘逐个关闭
fix(dialog): `confirmBtn` 支持数据类型 `null`

fix(dialog): 弹窗回车事件API、多个dialog同时存在时使用esc关闭异常

---

examples/dialog/demos/async.vue
examples/dialog/demos/attach.vue
examples/dialog/demos/base.vue
examples/dialog/demos/custom.vue
examples/dialog/demos/custom/body.vue
examples/dialog/demos/custom/bottom.vue
examples/dialog/demos/drag.vue
examples/dialog/demos/icon.vue
examples/dialog/demos/modal.vue
examples/dialog/demos/plugin.vue
examples/dialog/demos/position.vue
examples/dialog/demos/warning.vue
test/ssr/__snapshots__/ssr.test.js.snap
test/unit/dialog/__snapshots__/demo.test.js.snap

- chore: 更新dialog组件的示例代码，添加space组件，但有一个文件存在jest测试未能通过

chore: update dialog demo

---

src/table/hooks/useColumnResize.ts
src/table/thead.tsx

1. 鼠标hover在表头分割线上的时候也是能显示拖拽光标的
1. 新增左侧判定距离，并调整对应列
- fix(table): 允许在表头分割线一定范围内触发列宽调整逻辑

fix(table): 允许在表头分割线一定范围内触发列宽调整逻辑

---

examples/select/demos/remote-search.vue
src/select/select-panel.tsx
src/select/select.tsx
src/select/util.ts
test/ssr/__snapshots__/ssr.test.js.snap

- feat(select): 远程搜索场景增加 label 回显能力
- fix(select): 调整loading态显示优先于empty属性

feat(select): 远程搜索场景增加 label 回显能力

---

src/cascader/core/helper.ts
src/cascader/hooks.ts

- https://github.com/Tencent/tdesign-vue/issues/1223
- https://github.com/Tencent/tdesign-vue-next/issues/1448
- https://github.com/Tencent/tdesign-react/issues/1293
- fix(Cascader): 修复异步获取 `options` 后的懒加载无效 ([issue #1448](https://github.com/Tencent/tdesign-vue-next/issues/1448)) ([issue #1223](https://github.com/Tencent/tdesign-vue/issues/1223))
- fix(Cascader): 修复 `value` 不是 options 的健值会报错 ([issue #1293](https://github.com/Tencent/tdesign-react/issues/1293))

fix: cascader lazy options

---

src/popup/popup.tsx

修复popup在ie9-10点击报错问题
问题： ie9-10调用handleDocumentClick方法时没有传递参数
解决方案：加上需要传递的参数。
- fix(popup): 修复popup在ie9-10点击时，控制台报错问题

fix(popup): 修复popup在ie9-10点击报错问题

---

src/hooks/useDefaultValue.ts
src/hooks/useVModel.ts

- https://github.com/Tencent/tdesign-vue/issues/1178
useModel无法兼容导致v-model初始值为undefined进入非受控状态无法切换
- fix(useModel):  兼容因 `v-model` 初始值为 `undefined`  导致 `useModel` 的失效

fix: vModel invalid when initial

---

examples/form/demos/align.vue
examples/form/demos/base.vue
examples/form/demos/clear-validate.vue
examples/form/demos/custom-validator.vue
examples/form/demos/disabled.vue
examples/form/demos/error-message.vue
examples/form/demos/layout.vue
examples/form/demos/login.vue
examples/form/demos/reset.vue
examples/form/demos/size.vue
examples/form/demos/validate-complicated-data.vue
examples/form/demos/validate-message.vue
examples/form/demos/validator-status.vue
examples/form/demos/validator.vue
test/ssr/__snapshots__/ssr.test.js.snap
test/unit/form/__snapshots__/demo.test.js.snap

- https://github.com/Tencent/tdesign-vue/issues/1281
用 `space` 组件替换更新 `form` 的示例代码
- chore: 用 `space` 组件替换更新 `form` 的示例代码

chore: update form demo

---

src/cascader/_example/panel.vue
src/cascader/_tests_/index.test.js
src/cascader/cascader-panel.tsx
src/cascader/components/Panel.tsx

#1389 
现有特性下，如果用户想要自定义 cascader 的表现，只能根据 cascader-panel 派发的 change 事件处理 panel 的显示和隐藏，但在单选模式下点击已选择项 change 事件是不会被触发的，此时用户没有一种方式能感知到操作已经发生，所以没办法比较方便地维护自定义组件的状态。
PR 通过点击 cascader-panel 选项时派发点击事件 `click`，实现用户对 panel 状态的感知
- feat(CascaderPanel): 点击选项时派发 `click` 事件

feat(cascader-panel): 点击选项时派发 click 事件

---

src/calendar/_example/events.vue

根据issue：https://github.com/Tencent/tdesign-vue-next/issues/1526
优化demo

docs: 修改日历组件事件示例

---

src/input/input.tsx

feat(input): 优化 `clearable` 按钮显示逻辑区分 `password` 输入框

feat(input): 优化 `clearable` 按钮显示逻辑

---

src/date-picker/DatePickerPanel.tsx
src/date-picker/DateRangePickerPanel.tsx
src/date-picker/_example/panel.vue
src/date-picker/base/Header.tsx

- fix(`DatePicker`): 修复 panel-click 事件失效问题

fix: 修复 panel-click 事件失效问题

---

src/button/__tests__/__snapshots__/demo.test.js.snap
src/button/button.tsx
src/dialog/__tests__/__snapshots__/demo.test.js.snap
src/utils/ripple.ts
test/ssr/__snapshots__/ssr.test.js.snap

fix #1246
- https://github.com/Tencent/tdesign-vue/issues/1246
区分 button 组件 loading 和 disabled 状态，并修改 styles
- fix(Button): 修复幽灵按钮 loading 状态背景色

fix(button): fix loading status for ghost button

---

src/popup/popup.en-US.md
src/popup/popup.md
src/popup/popup.tsx
src/popup/props.ts
src/popup/type.ts

- feat(popup): add `delay` prop
- fix(popup): 修复子 popup 销毁时父级意外关闭

feat(popup): add `delay` prop

---

src/table/hooks/useColumnResize.ts
src/table/hooks/useFixed.ts

#1428 
1. 计算列宽时考虑每一列的minWidth属性
2. 列属性更新后重新计算各列宽度
- fix(table): 列宽调整需要考虑列的最小宽度

fix(table): 列宽调整需要考虑列的最小宽度

---

script/generate-usage/config.js
src/drawer/_usage/index.vue
src/message/_usage/index.vue
src/notification/_usage/index.vue

generate-usage生成的基础用例文件存在同名属性覆盖了组件props，导致基础用例切换该属性值时不生效
- fix(generate-usage): 修复文档中基础用例与预期不符

fix: drawer message notification组件基础用例的generate配置有误

---

src/select/instance.ts
src/select/select-panel.tsx
src/select/select.tsx

[#1433 ](https://github.com/Tencent/tdesign-vue/issues/1433)
keydownEvent()的数据来源是useSelectOption的optionsList，而不是filter之后的displayOptions，所以会出现可以选择过滤之外的数据的问题。
为了能使上下键移动时正确触发hover，需要单独处理一下displayOptions里的index属性，使其根据过滤后的数组大小依次递增，而不是在useSelectOption里处理的值。
- fix(select): 修复过滤掉数据后上下键仍可以选择过滤外的数据问题

fix(select): 修复过滤掉数据后上下键仍可以选择过滤外的数据问题

---

src/cascader/__tests__/__snapshots__/demo.test.js.snap
src/cascader/_example/base.vue
src/cascader/_example/check-strictly.vue
src/cascader/_example/collapsed.vue
src/cascader/_example/disabled.vue
src/cascader/_example/ellipsis.vue
src/cascader/_example/filterable.vue
src/cascader/_example/keys.vue
src/cascader/_example/load.vue
src/cascader/_example/max.vue
src/cascader/_example/multiple.vue
src/cascader/_example/panel.vue
src/cascader/_example/show-all-levels.vue
src/cascader/_example/size.vue
src/cascader/_example/trigger.vue
src/cascader/_example/value-mode.vue
src/cascader/_example/value-type.vue
src/cascader/cascader.tsx
src/cascader/components/Item.tsx
src/cascader/components/Panel.tsx
src/select-input/useMultiple.tsx
src/table/__tests__/__snapshots__/demo.test.js.snap
test/ssr/__snapshots__/ssr.test.js.snap

https://github.com/Tencent/tdesign-common/pull/804
- fix(Cascader): 修复 `loadingText` 无效 ([vue-next #1555](https://github.com/Tencent/tdesign-vue-next/issues/1555))
- fix(Cascader): 修复 `value` 为 `number` 类型时有告警 ([vue-next #1570](https://github.com/Tencent/tdesign-vue-next/issues/1570))
- fix(Cascader): 修复在输入时 `entry` 键会默认全选第一个选项的全部内容 ([vue-next #1529](https://github.com/Tencent/tdesign-vue-next/issues/1529))
- fix(Cascader): 修复通过 `SelectInputProps`  透传方法属性导致传入 `SelectInput` 的数据变成的数组 ([vue-next #1502](https://github.com/Tencent/tdesign-vue-next/issues/1502))
- fix(SelectInput): 修复多选清除无效导致 `Cascader` 点击清除按钮表现异常
- chore: 示例代码使用 `space` 组件替换 ([issue #1281](https://github.com/Tencent/tdesign-vue/issues/1281)) 

fix: cascader loading text and demo space replace

---

src/form/form-item.tsx

#1435
- fix(form): 修复 form 组件 labelAlign 属性为 top 时 form-item lable 为空 lable 还会占据空间的问题

fix(form): 修复 form 组件 labelAlign 属性为 top 时 form-item lable 为空 lable 还会占据空间的问题

---

src/upload/dragger.tsx

- fix(Upload): 在 `wujie` 环境中，部分按钮会触发两次
已在实际业务中验证

fix(upload): upload trigger twice

---

src/date-picker/DatePicker.tsx
src/date-picker/DatePickerPanel.tsx
src/date-picker/DateRangePicker.tsx
src/date-picker/DateRangePickerPanel.tsx
src/date-picker/__tests__/__snapshots__/demo.test.js.snap
src/date-picker/_example/base.vue
src/date-picker/_example/date-range.vue
src/date-picker/date-picker.en-US.md
src/date-picker/date-picker.md
src/date-picker/date-range-picker-props.ts
src/date-picker/hooks/useRange.ts
src/date-picker/hooks/useRangeValue.ts
src/date-picker/hooks/useSingle.ts
src/date-picker/hooks/useSingleValue.ts
src/date-picker/props.ts
src/date-picker/type.ts
test/ssr/__snapshots__/ssr.test.js.snap

- feat(`DatePicker`): 废弃 valueType api，提供 dayjs 封装对象供用户自定义格式化数据

feat: 移除 valueType api

---

src/select-input/_example/autocomplete.vue
src/select-input/_example/autowidth-multiple.vue
src/select-input/_example/autowidth.vue
src/select-input/_example/borderless-multiple.vue
src/select-input/_example/borderless.vue
src/select-input/_example/collapsed-items.vue
src/select-input/_example/custom-tag.vue
src/select-input/_example/excess-tags-display-type.vue
src/select-input/_example/label-suffix.vue
src/select-input/_example/multiple.vue
src/select-input/_example/single.vue
src/select-input/_example/status.vue
src/select-input/_example/width.vue

- fix(Demos): 修复 `select-input` 示例展示 ([issue #1640](https://github.com/Tencent/tdesign-vue-next/issues/1640)) ([issue #1641](https://github.com/Tencent/tdesign-vue-next/issues/1641))

fix: select-input demo style

---

src/table/hooks/useColumnResize.ts
src/table/hooks/useFixed.ts
src/table/thead.tsx
src/table/type.ts

#1348 
1. 新增 column.resizable 支持自定义任意列是否可拖拽调整宽度
- feat(table): 新增 column.resizable 支持自定义任意列是否可拖拽调整宽度

feat(table): 新增 column.resizable 支持自定义任意列是否可拖拽调整宽度

---

src/table/base-table.tsx
src/table/hooks/useFixed.ts

#1437 
- fix(table): 修复数据变化时,吸底滚动条位置没有变化的问题

fix(table): 修复数据变化时,吸底滚动条位置没有变化的问题

---

src/collapse/__tests__/__snapshots__/demo.test.js.snap
src/collapse/collapse-panel.tsx
src/input/input.tsx
src/slider/__tests__/__snapshots__/demo.test.js.snap
test/ssr/__snapshots__/ssr.test.js.snap

* 问题1：Input组件聚焦时，父级节点无法通过类变化监听到从而修改样式
解决方案：聚焦时在父级添加t-input__wrapper--focused类
* 问题2：Collapse-panel组件的header内容直接渲染，没有父级包裹，在做ie兼容时无法针对对应的部分编写样式
解决方案：在header中添加left、content、right三个父级盒子包裹左、中、右的内容
- fear(Collapse): 增加节点和类名处理IE样式
- fix(InputNumber): 处理0比较的异常 [#common850](https://github.com/Tencent/tdesign-common/pull/850)

feat: Input和Collapse组件增加节点类名

---

src/swiper/swiper-item.tsx
src/swiper/swiper.tsx

修复swiper三个问题
#1537 
(1)修复鼠标悬停移出后没有重新轮播问题 
(2)修复trriger属性不生效问题 
(3)修复fade特效下,click事件获取到的数据一直为最后一个问题
- fix(swiper): 修复鼠标悬停移出后没有重新轮播问题 
- fix(swiper): 修复trriger属性不生效问题 
- fix(swiper): 修复鼠标悬停移出后没有重新轮播问题

fix(swiper): 修复swiper三个问题

---

src/table/hooks/usePagination.tsx

修复PrimaryTable触发两次onPageChange问题
re #1465
#1465(https://github.com/Tencent/tdesign-vue/issues/1465)
目前onPageChange会同时触发两次，修改后只触发一次
- fix(table): 修复PrimaryTable触发两次onPageChange问题

fix(table): 修复PrimaryTable触发两次onPageChange问题

---

src/cascader/cascader.tsx
src/cascader/components/Item.tsx

- fix(Cascader):修复面板 `padding`, 优化多选状态下叶子结点点击交互

fix: cascader padding

---

src/collapse/__tests__/index.test.js
src/collapse/collapse-panel.tsx

#1418 
- test(collapse): add unit test for collapse and support content api

test(collapse): add unit test for collapse and support content api

---

src/tree-select/tree-select.tsx

[#229](https://github.com/Tencent/tdesign/issues/229)
与 Select 组件保持一致，popup Content 中的内容应当包裹在  t-select__dropdown-inner t-select__dropdown-inner--size-s  内，同时给 t-select__dropdown-inner--size > t__tree 添加 padding

fix: treeSelect padding 为空

---

src/upload/upload.tsx

- fix(Upload): 修复sizeLimit计算错误的问题

fix(upload): sizelimit api

---

src/date-picker/panel/RangePanel.tsx
src/date-picker/panel/SinglePanel.tsx

- fix(`DatePicker`): 修复 `disableDate` 传入 lambda 函数被频繁触发问题

fix: 修复 disableDate 传入 lambda 函数被频繁触发问题

---

src/time-picker/panel/single-panel.tsx
src/time-picker/panel/time-picker-panel.tsx

- fix(TimePicker): 关闭面板不再滚动 避免部分场景滚动未结束关闭面板继续滚动引发的问题

fix(timepicker): prevent scroll after closing panel

---

src/input/input.tsx

https://github.com/Tencent/tdesign-vue/issues/1484
- fix(Form): 修复 Form 中使用 Input/InputNumber 组件时，无法通过 `trigger = blur` 触发校验的问题 https://github.com/Tencent/tdesign-vue/issues/1484

fix: input blur trigger in form

---

src/select-input/useOverlayInnerStyle.ts

- https://github.com/Tencent/tdesign-react/issues/1523
- feat(Select): 调整下拉交互 允许输入时不关闭下拉面板 减少相关交互问题

feat(SelectInput): keep panel display when allow input

---

src/form/form-item.tsx

feat: 调整 requiredMark api 可独立控制星号展示

---

CHANGELOG.md
src/hooks/useCommonClassName.ts
src/message/plugin.tsx
src/notification/plugin.ts
src/table/__tests__/__snapshots__/demo.test.js.snap
src/table/_example/custom-col-button.vue
src/table/_example/ellipsis.vue
src/table/_example/merge-cells.vue
src/table/_example/select-single.vue
src/table/_example/style.vue
src/table/_example/tree.vue
src/table/base-table.tsx
src/table/ellipsis.tsx
src/table/enhanced-table.tsx
src/table/hooks/useClassName.ts
src/table/hooks/useFilter.tsx
src/table/hooks/useFixed.ts
src/table/hooks/useStyle.ts
src/table/hooks/useTableHeader.tsx
src/table/hooks/useTreeData.tsx
src/table/primary-table-props.ts
src/table/primary-table.tsx
src/table/tbody.tsx
src/table/thead.tsx
src/table/tr.tsx
src/table/type.ts
test/ssr/__snapshots__/ssr.test.js.snap

- feat(Table): 表格列属性 `attrs` 支持自定义任意单元格属性
- feat(Table): 新增列属性 `colspan`，用于设置单行表头合并
- feat(Table): 超出省略功能，支持同时设置省略浮层内容 `ellipsis.content` 和属性透传 `ellipsis.props`
- feat(Table): 增强型表格，支持列配置，支持不传 `displayColumns` 时默认显示全部列，[issue#1784](https://github.com/Tencent/tdesign-vue-next/issues/1784)
- fix(Table): 筛选功能，`resetValue` 无效，[issue#1611](https://github.com/Tencent/tdesign-vue/issues/1611)
- fix(Table): 表头吸顶功能，数据变化更新吸顶位置，[issue#1585](https://github.com/Tencent/tdesign-vue/issues/1585)

[Table] ellipsis.props and ellipsis.content support

---

src/table/base-table.tsx
src/table/hooks/useAffix.ts

table配置了吸底滚动条，但是表格没有滚动条时，没有底部border: 
https://codesandbox.io/s/tdesign-vue-demo-forked-zzpftg?file=/src/demo.vue
[table] 分页器吸底 在 windows的firefox下样式异常:
#1452 
当配置了吸底滚动条，但表格没有滚动条时，吸底滚动条的 `margin-top` 造成遮挡。
解决方案：
检查当表格没有横向滚动条时，去掉margin-top并隐藏吸底滚动条
- fix(table): 当配置吸底滚动条时，margin-top造成遮挡

fix(table): 当配置吸底滚动条时，margin-top造成遮挡

---

package.json
src/dialog/dialog.tsx

问题：当dialog组件的footer参数为false时，footer节点还渲染问题
解决方案：当dialog组件的footer参数为false时，footer节点不渲染
- fix(dialog): 修复参数footer为false时，footer节点还渲染问题

fix(dialog): 修复参数footer为false时，footer节点还渲染问题

---

src/calendar/__tests__/__snapshots__/index.test.jsx.snap
src/calendar/_example/cell-append.vue
src/calendar/calendar-cell.tsx

- 优化日历组件“单元格插槽-追加内容” 的 demo 示例，和 tdesign-vue-next 中示例展示保持一致。
- 优化 demo 过程中发现单元格外层dom样式问题，已优化。
- fix(Calendar): 修复日历组件单元格外层dom样式问题，在使用 `cellAppend` 插槽后可能样式会有异常

fix: 修复日历组件单元格外层dom样式问题；优化单元格插槽demo

---

src/time-picker/_example/hms.vue
src/time-picker/_example/range.vue
src/time-picker/panel/single-panel.tsx
src/time-picker/panel/time-picker-panel.tsx
src/time-picker/props.ts
src/time-picker/time-picker.en-US.md
src/time-picker/time-picker.md
src/time-picker/time-picker.tsx
src/time-picker/time-range-picker-props.ts
src/time-picker/time-range-picker.tsx
src/time-picker/type.ts

- https://github.com/Tencent/tdesign-vue/issues/1703
- feat(TimePicker): 新增`onPick` API 用于每次选中面板值进行回调处理
- fix(TimePicker): 修复12小时制时分的显示异常

feat(timepicker): support onPick API

---

src/table/base-table.tsx

…x header
https://github.com/Tencent/tdesign-vue-next/issues/1934
1. 表格在resizable=false是，基础表格的表头读取用户设置进来的默认宽度
- fix(table): 当禁用resizable时，基础表格表头默认使用用户定义的列宽 

fix(table): 当禁用resizable时，基础表格表头默认使用用户定义的列宽 

---

src/input/input.tsx
src/pagination/pagination.tsx

子仓库：https://github.com/Tencent/tdesign-common/pull/968
- [] 新特性提交
- fix(Input): 修复在输入框进行预渲染处于 `display: none` 状态时，宽度计算不正确问题，[issue#1678](https://github.com/Tencent/tdesign-vue/issues/1678)

fix(Input): fix auto-width in display: none

---

src/tree/__tests__/filter.test.jsx
src/tree/td-tree.tsx

使用 filter 过滤后，过滤结果为空，不显示 empty的 slot
- #1744 

fix(tree): 修复使用 filter 过滤后，过滤结果为空，不显示 empty的 slot

---

src/form/form-model.ts

fix(form): fix: 修复min为0时不校验问题

---

src/form/form-item-props.ts
src/form/props.ts
src/form/type.ts
src/time-picker/__tests__/index.test.jsx

- fix(Form): 修复`requiredMark`默认值的问题

fix(Form): fix requiredMark default value

---

src/select/option.tsx

- 梳理 option 内部禁用态逻辑，统一禁用入口 
- fix(select): 修复限制可选条目数下禁用态不能反选的问题 (#1819)

fix(select): 修复限制可选条目数下禁用态不能反选的问题

---

src/time-picker/panel/single-panel.tsx
src/time-picker/props.ts
src/time-picker/time-picker.tsx
src/time-picker/time-range-picker-props.ts
src/time-picker/time-range-picker.tsx
src/time-picker/type.ts

- https://github.com/Tencent/tdesign-vue/issues/1808
- fix(TimePicker): 修复面板打开时清空内容回填的问题
- feat(TimePicker): `TimePicker` 新增`tips`和`status`的API

feat(timepicker): add tips and status apis

---

src/progress/__tests__/__snapshots__/index.test.jsx.snap
src/progress/__tests__/index.test.jsx
src/progress/progress.tsx

- #1789
修复percentage值为100时,会忽略status设置的值问题
- fix(progress): 修复percentage值为100时,会忽略status设置的值问题

fix(progress): 修复percentage值为100时,会忽略status设置的值问题

---

src/input/input.tsx

- fix(Input): 宽度自适应 `auto-width` 支持中文拼音输入也实时调整宽度，[issue#2079](https://github.com/Tencent/tdesign-vue-next/issues/2079)
实现效果如下，
https://user-images.githubusercontent.com/11605702/204307601-e5bb39d9-c392-4a8c-b49d-1e22e2aae62f.mov

fix(input): auto-width support chinese pinyin

---

src/checkbox/checkbox.tsx
src/common.ts
src/radio/radio.tsx
src/table/filter-controller.tsx
src/table/hooks/useFilter.tsx
src/table/hooks/useRowSelect.tsx
src/table/hooks/useSorter.tsx
src/table/primary-table-props.ts
src/table/primary-table.tsx
src/table/table.en-US.md
src/table/table.md
src/table/type.ts

- feat(Table): 可筛选表格，新增 `filter.popupProps` ，支持透传 Popup 组件全部属性，[tdesign-vue-next#2088](https://github.com/Tencent/tdesign-vue-next/issues/2088)
- feat(Table): 选中行表格，新增 `selectOnRowClick`，支持点击行选中，[tdesign-vue-next#1954](https://github.com/Tencent/tdesign-vue-next/issues/1954)
- feat(Table): 本地排序功能，支持对默认数据进行排序
- refactor(Radio): `click` 事件更为从最外层输出，否则会出现无法在外层阻止冒泡问题
- refactor(Checkbox): `click` 事件更为从最外层输出，否则会出现无法在外层阻止冒泡问题

[Table]Support Select on Row Click

---

src/table/_example/tree-select.vue
src/table/enhanced-table.tsx
src/table/hooks/useTreeData.tsx
src/table/type.ts

- feat(Table): 树形结构，支持点击行展开树节点，[issue#1847](https://github.com/Tencent/tdesign-vue/issues/1847)
- feat(Table): 树形结构，点击树节点展开图标时，不触发 `onRowClick` 行点击事件，[issue#1847](https://github.com/Tencent/tdesign-vue/issues/1847)

feat(table): support expand tree node on row lick

---

src/textarea/textarea.tsx

https://github.com/Tencent/tdesign-vue/issues/1852
- fix(TextArea): 修复中文输入法等 IME 情况下，`autosize` 计算失效的问题

fix: text auto height in IME

---

site/src/components/stackblitz/content.js

部分组件 demo 中使用了 less
但没有在 stackblitz 的 demo 中引入 less 依赖，导致打开例子时报错：
- stackblitz 添加 less 依赖，防止 demo 中使用 less 维护样式打开报错的问题

fix: stackblitz less dependency error

---

src/upload/themes/normal-file.tsx
src/upload/upload.tsx

https://github.com/Tencent/tdesign-vue/issues/1925
- fix(Upload): 上传组件的输入框模式在 Form 表单中的宽度问题修复

[Upload] fix upload put into form width when theme=single-input

---

src/checkbox/_example/group.vue
src/checkbox/group.tsx

- fix(Checkbox): 修复禁用的选项依然会被选中的问题

fix(checkbox): disabled checkbox could be checked

---

src/select/_example/multiple.vue
src/select/props.ts
src/select/select.en-US.md
src/select/select.md
src/select/select.tsx
src/select/type.ts

- https://github.com/Tencent/tdesign-vue/issues/2002
- feat(Select):  `valueDisplay`回调新增`displayValue`参数，用于设置`minCollapsedNum`的场景

feat(select): add valueDisplay callback param

---

src/tree-select/tree-select.tsx
src/tree/hooks/useItemEvents.ts
src/tree/hooks/useRenderIcon.tsx
src/tree/hooks/useTreeItem.tsx

- fix(tree-select): 修复单选下选中值后没有触发onblur的问题

fix(tree-select): trigger onblur exclude expand icon

---

src/tree-select/tree-select.tsx
src/tree-select/useTreeSelect.ts

- fix(TreeSelect): 修复第一次点击无法显示下拉框问题，[issue#2123](https://github.com/Tencent/tdesign-vue/issues/2123)
- fix(TreeSelect): 修复 `treeProps.keys` 无效问题（仅 1.1.0 有这个问题）

[TreeSelect] fix can not show popup at first click; fix treeProps.keys does not work

---

src/tree-select/__tests__/mount.jsx
src/tree-select/__tests__/vitest-tree-select.test.jsx
src/tree-select/_example/props.vue
src/tree-select/props.ts
src/tree-select/tree-select.md
src/tree-select/tree-select.tsx
src/tree-select/type.ts

- feat(TreeSelect): 支持使用 `keys` 定义字段别名
- test(TreeSelect): 输出 `keys` 和 `treeProps.keys` 测试用例检测 

[TreeSelect] support tree.keys

---

src/table/base-table.tsx
src/table/hooks/useColumnResize.ts
src/table/hooks/useFixed.ts
src/table/hooks/usePagination.tsx
src/table/interface.ts
src/table/tbody.tsx
src/table/thead.tsx

- fix(Table): 列宽调整功能，修复添加 `resizable` 属性后，在 Dialog 组件中宽度计算问题，并非提前设置好的 column.width，[issue#2116](https://github.com/Tencent/tdesign-vue/issues/2116)
- fix(Table): 列宽调整功能，修复 `column.resizable=false` 在某些场景下无效问题，[issue#1765](https://github.com/Tencent/tdesign-vue/issues/1765)
- fix(Table): 列宽调整功能，在自定义列数量场景，表格宽度未能根据列数自适应，[issue#1861](https://github.com/Tencent/tdesign-vue/issues/1861)
- fix(Table): 列宽调整功能，修复宽度计算的各类问题，[issue#1663](https://github.com/Tencent/tdesign-vue/issues/1663)
- fix(Table): 空数据功能，修复空表格在 Dialog 组件中，文本显示位置不正确问题，[issue#2082](https://github.com/Tencent/tdesign-vue/issues/2082)
- fix(Table): 分页功能，修复 `pagination.onChange` 被调用两次问题，[issue#2066](https://github.com/Tencent/tdesign-vue/issues/2066)

fix(table): fix resizable table width problems

---

src/cascader/core/helper.ts

修复在级联组件单选状态下，选中项value为0时，label不能正常显示
fix #2143
#2143 
- fix(cascader): 修复级联组件无法选中值为 0 的选项

fix(cascader): 修复级联组件无法选中值为 0 的选项

---

src/table/hooks/useFixed.ts

问题：表格宽度出现小数时导致吸顶和吸底出现横向滚动条
方案：表格宽度向下取整
- fix(table): 表格宽度向下取整，修复表格宽度出现小数时导致吸顶和吸底出现横向滚动条

fix(table): 表格宽度向下取整，避免出现小数时导致吸顶和吸底出现横向滚动条

---

src/table/_example/fixed-column.vue
src/table/base-table.tsx
src/table/hooks/useColumnResize.ts
src/table/hooks/useFixed.ts

- fix(Table): 列宽调整功能，修复左右侧固定列宽度调整问题，[issue#2168](https://github.com/Tencent/tdesign-vue/issues/2168)
- fix(Table): 列宽调整功能，修复吸顶表头列宽调整问题

fix(table): column resize

---

src/hooks/useFormDisabled.ts
src/upload/upload.tsx

#2184 
禁用态的表单(disabled)对upload组件无效，即form组件disabled为true，里面upload组件没有变为禁用状态，还是可以上传
- fix(upload): 修复禁用态的表单对upload组件无效问题

fix(upload): 修复禁用态表单对upload组件无效问题

---

src/guide/__tests__/__snapshots__/vitest-guide.test.jsx.snap
src/textarea/__tests__/__snapshots__/index.test.jsx.snap
src/textarea/_example/maxlength.vue
src/textarea/textarea.tsx

解决textarea字符限制文案遮挡文本内容的问题，textArea的内容长度限制提示，位置从textarea的右下角移动到textarea之外的右下角，与tips在同一行
tdesign-react 的textarea组件PR 已合并，相应的tdesign-common PR 已合并

fix(textarea): mdoify textarea styles

---

src/table/base-table.tsx

背景：table的headerAffixedTop和footerAffixedBottom渲染的表头和表尾没有过长时出现滚动条
解决方案：多级表头左边线缺失减少的1px在IE上不用减少
- fix(table): 修复由于表头左边线缺失减少1像素后导致在IE上affix表头和表尾出现滚动条问题

fix(table): 修复由于表头左边线缺失减少1像素后导致在IE上affix表头和表尾出现滚动条问题

---

src/cascader/_example/load.vue
src/cascader/components/Panel.tsx
src/cascader/hooks.ts
src/cascader/interface.tsx

问题：cascader组件的动态加载模式不支持回显
解决方案：使用动态模式时，如果valueType为full，且value不为空时，下拉框首次弹出时支持自动选择已有的值和加载子列表
https://user-images.githubusercontent.com/16223845/224270087-196e6909-32f4-46b9-b13f-cd9b0a269e0a.mov
-fix(cascader): 动态加载模式支持回显

fix(cascader): 动态加载在value-type为full时支持回显

---

src/input-number/useInputNumber.tsx

问题：小数点后存在非0数字后无法再输入0
解决方案：优化正则表达式兼容
- fix(inputNumber): 修复小数点后存在非0数字后无法再输入0的问题

fix(inputNumber): 修复小数点后存在非0数字后无法再输入0的问题

---

src/table/hooks/useRowSelect.tsx

- fix(Table): 单行选中功能，修复 `allowUncheck: false` 无效问题，[tdesign-vue-next#2561](https://github.com/Tencent/tdesign-vue-next/issues/2561)

fix(table): checkProps.allowUncheck = false does not work

---

src/tag-input/tag-input.tsx
src/tag-input/useTagList.tsx

fix #2261
- https://github.com/Tencent/tdesign-vue/issues/2261
- fix(TagInput): 修复基于`TagInput`的组件使用筛选时删除关键词时会删除已选值的问题

fix(tag-input): select使用筛选时删除filterWords偶尔会删除已选值

---

src/form/form.tsx

#2295 
Issue:  the reset operation creates an `undefined` key for `data`.
Solution: check whether the `name` is in the `fields`
```js
resetHandler(e?: FormResetEvent) {
if (this.preventSubmitDefault) {
e?.preventDefault();
e?.stopPropagation();
}
const fields = keys(this.data);
this.children
.filter((child) => this.isFunction(child.resetField) && this.needValidate(String(child.name), fields))
.forEach((child) => child.resetField(this.resetType || 'initial'));
emitEvent<Parameters<TdFormProps['onReset']>>(this, 'reset', { e });
}
```
- fix(form): the `undefined` key created after the reset

fix(form): `undefined` key created after the reset

---

src/tree/hooks/useRenderLabel.tsx

- fix(tree): 修复懒加载子节点时点击label会触发选中的问题

fix(tree): prevent trigger check when branch lazy load

---

src/input-number/useInputNumber.tsx

https://codesandbox.io/s/tdesign-vue-demo-forked-m372sx?file=/src/demo.vue
如 当输入1.01后失焦，再输入1.00，会被重置会1.01
- fix(InputNumber): 修复小数位操作以0结尾时部分边界场景异常的问题

fix(input-number): change decimal value on blur when end of 0

---

src/upload/upload.tsx

1. API属性，triggerButtonProps在theme为file-input下失效
2. jsx需要把triggerButtonProps挂到props下
- fix(upload): triggerButtonProps在theme为file-input下失效

fix(upload): triggerButtonProps在theme为file-input下失效

---

src/loading/_example/directive.vue
src/loading/directive.ts
src/loading/loading.md

#2284 
需求背景：v-loading可配置属性过少
实现：保持原有使用方式不变的情况下，额外支持以 `Object` 形式传参
```vue
<template>
<div v-loading="loading" class="loading-container">Loading...</div>
<template>
<script>
export default {
data() {
return {
loading: {
loading: false,
delay: 300,
showOverlay: true,
},
};
},
}
</script>
```
- feat(loading): supports custom configuration for v-loading

feat(loading): supports custom configuration for v-loading

---

src/table/hooks/useColumnResize.ts
src/table/thead.tsx

1. vue 1.2.5版本组件库的table组件，在固定列生效且存在可横向滚动的滚动条时，当开启列拖拽宽度后拖拽使横向滚动条消失，此时拖拽某一列横向不超过后一列时，后一列宽度可以被无限缩小，min-width和max-width不生效
2. 修复table组件中开启左侧列固定并且固定列配置resizable=false时，拖动此固定列相邻非固定列列宽时控制台报错的问题
3. 修复table组件在开启多级表头时点击子表头后控制台报错的问题
1. 通过判断控制canResizeSiblingColWidth的值，判断逻辑新增后一列宽度与min-width和max-width的关系
2. 在左侧有列固定且resizable=false这种情况时进行异常处理不允许拖动相邻列左侧使其能调整宽度
3. 表头点击时禁止冒泡，防止重复触发列鼠标事件导致报错
- fix(Table): 列宽调整功能，修复即使 `resizable=false` 时，也会显示拖拽调整列宽图标和辅助线问题
- fix(Table): 列宽调整功能，修复开启左侧列固定并且固定列配置 `resizable=false` 时，拖动此固定列相邻非固定列列宽时控制台报错的问题
- fix(Table): 列宽调整功能，修复在拖拽任意列宽使表格横向滚动条消失之后列宽无法正常调整的问题
- fix(Table): 列宽调整功能，修复开启多级表头时点击子表头后控制台报错的问题

Fix table 20230411

---

src/date-picker/panel/ExtraContent.tsx

#2283 
时间戳类型数据是Number类型，但是对selectedValue却断言只有String类型，补充对应的类型判断
补充对应的类型判断
- fix(DatePicker): 修复时间戳模式下控制台警告props类型错误的问题
- [√] 文档已补充或无须补充
- [√] 代码演示已提供或无须提供
- [√] TypeScript 定义已补充或无须补充
- [√] Changelog 已提供或无须提供

fix(DatePicker): 修复时间戳模式下props类型检测报错问题

---

src/date-picker/DatePicker.tsx
src/date-picker/DatePickerPanel.tsx
src/date-picker/DateRangePicker.tsx
src/date-picker/DateRangePickerPanel.tsx
src/date-picker/base/Footer.tsx
src/date-picker/date-picker-panel-props.ts
src/date-picker/date-picker.en-US.md
src/date-picker/date-picker.md
src/date-picker/date-range-picker-panel-props.ts
src/date-picker/date-range-picker-props.ts
src/date-picker/props.ts
src/date-picker/type.ts

- fix(Datepicker): 支持 `onPresetClick` 事件

feat(datepicker): 支持 onPresetClick 事件触发

---

src/table/hooks/useColumnResize.ts
src/table/thead.tsx

问题如下：
1. 左侧固定列单列设置fixed和resizable=false时，固定列与相邻列之间仍然能够在拖动调整列宽时出现辅助线
2. 表头中两列之间相交处拖动调整列宽时，鼠标拖动其实位置在相交处的左侧和右侧对列宽调整限制不一致
如下图所示，在鼠标起始位置在相交处右侧时，左侧列的列宽限制被按照右侧列的min-width,max-width属性值进行处理
修复内容如下：
1. 传参值由effectNextCol改成effectPrevCol
2. 通过dataset.colkey === col.colkey判断鼠标拖动起始位置是否在相交线的左侧，根据起始位置在左侧还是右侧进行不同处理
1. 左侧固定列单列设置fixed和resizable=false时，固定列与相邻resizable=true的列之间在拖动调整列宽时不出现辅助线
2. 表头中两列之间相交处拖动调整列宽时，鼠标拖动起始位置在相交处的左侧和右侧时不影响辅助线能够拖动的最左侧和最右侧的位置
- fix(table): 修复table组件在开启固定列单列resizable禁用时，相邻resizable启用的列列宽调整范围与预期不一致的问题

[Table] fix sibling column resizable does not work

---

src/cascader/cascader.tsx

- https://github.com/Tencent/tdesign-vue/issues/2203
- fix(Cascader): 修复 `valueType = full` 模式下，设置 `minCollapsedNum` 渲染报错的问题

fix: collapse render error in full path valueType mod

---

src/date-picker/DatePickerPanel.tsx
src/date-picker/DateRangePickerPanel.tsx
src/date-picker/type.ts

- [√] 日常 bug 修复
#2279 
组件单独使用的时候并没有传递popupVisible属性，本身在单独使用的时候并没有父组件为date-picker-panel & date-range-picker-panel传递该属性，导致在single-panel(time-picker/panel/single-panel.tsx)中handleScroll方法对props.isShowPanel判断结果为真，卷动无法继续运行
添加了popupVisible属性
- fix(date-picker): 修复单独的panel拎出来并且启用enable-time-picker时，时分秒无法双向绑定且无法滚动的问题
- [√] 文档已补充或无须补充
- [√] 代码演示已提供或无须提供
- [√] TypeScript 定义已补充或无须补充
- [√] Changelog 已提供或无须提供

fix(datepicker): fix single panel with enable-time-picker not available

---

src/select-input/useSingle.tsx

https://github.com/Tencent/tdesign-vue/issues/2322
- fix(select-input): 修复单模式下，定制 `valueDisplay` 后输入不显示的问题

fix: 修复valueDisplay模式下输入不显示的问题

---

src/table/hooks/useFixed.ts

问题：在表格设置bordered和列设置fixed: 'right'后，如果出现小数点，则可能出现表头无法对齐情况
解决方案：表格宽度不能格式化为整数
- fix(table): 修复表格右侧冻结时表头无法对齐问题

feat(table): 修复表格宽度格式化为整数后导致的右侧表头无法对齐问题

---

src/date-picker/DateRangePicker.tsx
src/select/select.tsx
src/time-picker/time-picker.tsx
src/time-picker/time-range-picker.tsx

- https://github.com/Tencent/tdesign-vue/issues/2376
- fix(Form): 修复`disabled`下部分组件未禁用的缺陷

fix(form): form disabled affect components

---

src/message/plugin.tsx

https://github.com/Tencent/tdesign-vue/issues/2415
复现代码
```
<template>
<div>
<div class="message-wrap" ref='mss'>
111
</div>
<t-space>
<t-button variant="outline" @click="closeFunc"> 自由控制关闭时机（{{ msg ? '关闭' : '打开' }}） </t-button>
</t-space>
</div>
</template>
<script>
export default {
data() {
return {
msg: null,
};
},
methods: {
// 自由控制关闭时机
closeFunc() {
this.$message.closeAll()
if(this.msg) {
this.$refs.mss.innerHTML = ''
}
this.msg = this.$message.info({
attach:'.message-wrap',
content: '调用关闭函数关闭信息提示框',
duration: 0,
zIndex: 1001,
});
},
},
};
</script>
```
message的attachDom被清空(如attachDom.innerHtml='')，之前的缓存实例也会存在，需要判断下dom包含关系
- fix(message): message通过命令调用时，attach所在Dom被清空后，新的message无法显示问题修复

fix(message): 修改创建MessageList实例的判断条件

---

src/input-adornment/input-adornment.tsx

- https://github.com/Tencent/tdesign-vue/issues/2356
- fix(InputAdornment): 修复prepend或append为空字符串时仍然渲染节点的问题

fix(input-adornment): fix render empty string prepend and append

---

src/loading/plugin.tsx

问题：函数式关闭全屏loading时，若多次调用关闭函数则会报错
解决方案：卸载全屏loading实例时，需判断实例是否存在
- fix(loading): 修复多次调用关闭全屏函数时控制台报错问题

fix(loading): 函数式关闭全屏loading时，需要先判断全屏实例是否存在，避免实例已销毁情况的报错

---

src/menu/__tests__/__snapshots__/menu-item.test.jsx.snap
src/menu/__tests__/__snapshots__/menu.test.jsx.snap
src/menu/__tests__/__snapshots__/submenu.test.jsx.snap
src/menu/_example/single-side.vue
src/menu/const.ts
src/menu/menu-item.tsx
src/menu/menu.tsx
src/menu/submenu.tsx

https://github.com/Tencent/tdesign-vue-next/issues/1671
修复菜单层级判断逻辑，只有在一级菜单收起时展示 tooltip
在传入 href 时使用 <a> 标签渲染菜单内容 DOM，与 vue-next 实现保持一致：
- refact(Menu): 使用 Popup 重构 Menu 弹出菜单实现
- fix(Menu): 修复收起菜单时超出内容无法滚动的问题 https://github.com/Tencent/tdesign-vue/issues/2435
- fix(Menu): 修复侧边导航菜单，次级弹出菜单也会展示 Tooltip 的问题
- feat(Menu): 设置 `href` 时使用 <a> 标签渲染菜单项 https://github.com/Tencent/tdesign-vue-next/issues/1671

feat: refact menu by popup

---

src/checkbox/checkbox.tsx
src/input/input.tsx
src/radio/radio.tsx
src/tabs/tabs.tsx
src/utils/map-props.ts

- fix: 修复 radio/checkbox/input/tabs/popup 等多个组件的编译结果缺少 ts type 问题
处理前的结果
处理后的结果

fix radio/checkbox/input/tabs/popup/.. ts type of build files

---

src/input/input.tsx

- https://github.com/Tencent/tdesign-vue/issues/2436
- https://github.com/Tencent/tdesign-vue/issues/2350
- 由于TD需要实现受控的关系 组件本身控制了input的value 同时此前修复在popup中nextTick的位置异常重新计算了光标位置 此时如果快速或同时按下多个输入符 会重复触发位置计算的逻辑 这里通过throttle避免多次触发 让输入位置为正确的位置
- fix(Input): 修复快速输入或同时输入时输入值异常的问题

fix(input): resolve quick input error

---

src/input-adornment/input-adornment.tsx
src/select/option.tsx

- https://github.com/Tencent/tdesign-vue/issues/2438
- https://github.com/Tencent/tdesign-vue-next/issues/2926
- fix(InputAdornment): 修复1.3.4中修复空字符串导致插槽没有正常渲染的问题
- feat(Select): 优化选项结构 移除多余的span节点

fix(input-adornment): fix render  prepend and append slot

---

site/docs/getting-started.md
site/src/components/page.vue

docs: update documentation for vue 2.7 support

---

.github/workflows/pull-request.yml
README.md
site/docs/getting-started.md
src/back-top/back-top.tsx

chore: add 2.7 infra

---

package.json
site/site.config.mjs
site/src/main.js
src/icon/icon.en-US.md

docs: add EN version site

---

src/alert/alert.tsx

https://stackblitz.com/edit/sxrzm5?file=src%2Fdemo.vue
现有判断会导致子元素 opacity 变化结束时（比如 link hover 颜色变化后）也触发 Alert 的隐藏关闭逻辑。
- fix(Alert): 修复内部自定义元素透明度变化，意外导致 Alert 隐藏的问题

fix: alert opacity style when closed

---

src/menu/menu-item-props.ts
src/menu/menu-item.tsx
src/menu/type.ts

样式修改已在common仓库提PR https://github.com/Tencent/tdesign-common/pull/1506
vue-next仓库的PR https://github.com/Tencent/tdesign-vue-next/pull/3057
- feat(MenuItem): 新增API: routerLink，可指定菜单项渲染为Router控制跳转的a标签
- fix(MenuItem): 渲染为a标签时，a标签覆盖范围扩大至整个菜单项，而不是只有文本部分
- fix(MenuItem): 修复当菜单项渲染a标签并且menu在collapsed状态时，菜单项内区隐藏导致无法点击跳转的问题
- fix(MenuItem): 修复渲染为a标签时并在popup出现时，文本对齐与正常菜单项的位置不一致的问题

feat(menu-item): 修正菜单项为a标签时的跳转行为与渲染样式

---

src/dialog/dialog.tsx

1.  https://github.com/Tencent/tdesign-vue/issues/2006
2. https://github.com/Tencent/tdesign-vue-next/pull/2242
1. 在Dialog组件销毁后，没有正确的对DOM元素进行销毁，导致内存泄露
解决方案：
在beforeDestroy函数中，对创建的DOM元素进行销毁
- fix(Dialog): 修复Dialog组件销毁后，没有销毁DOM，导致内存泄漏

[+] 销毁前需要移除dialog创建的DOM

---

src/transfer/transfer.tsx
src/transfer/utils.ts

- https://github.com/Tencent/tdesign-vue/issues/2564
- fix(transfer): 修复穿梭框存在默认已选且不允许移除的值被移除的异常问题

fix(transfer): fix disabled value removed from target

---

src/tree-select/tree-select.tsx

修复关闭自定义标签报错,并无法关闭
#2601
#2601 

fix(tree-select): 自定义标签关闭异常

---

script/utils/index.js
src/table/hooks/useFixed.ts
src/table/tbody.tsx
vitest.config.js

- fix(Table): 修复 1.5.0 版本空表格没有显示占位元素问题
- fix(Table): 固定列空数据场景，元素显示错位问题

fix(table): table doest not show empty elements

---

src/input/input.tsx

修复form disabled状态input依然显示clear
#2589
#2589 
- fix(Input): form表单disabled状态下input异常显示clear

fix(input): form disabled状态input显示clear

---

src/dialog/dialog.tsx

#2106 
初始化就执行一次移动相关初始化的逻辑
- fix(dialog): 修复dialog初始化时没有执行移动相关的初始化逻辑,导致image-viewer小窗口图片查看器无法移动问题

fix(dialog): 修复dialog初始化时没有执行移动相关的初始化逻辑,导致image-viewer小窗口图片查看器无法移动问题

---

src/common.ts
src/table/_example/tree-select.vue
src/table/_example/virtual-scroll.vue
src/table/base-table.tsx
src/table/enhanced-table.tsx
src/table/primary-table.tsx

- feat(Table): 虚拟滚动场景，支持通过行唯一标识跳转到指定行（通过行下标跳转到指定行，以前的版本已支持）

feat(table): scrollToElement By row key

---

src/dialog/dialog.tsx

- https://github.com/Tencent/tdesign-vue/issues/2636
- fix(Dialog): 反馈类对话框补齐body class

fix: dialog body class

---

src/select-input/useMultiple.tsx

fix #2525
https://github.com/Tencent/tdesign-vue/issues/2525

fix(select-input): 多选情况下按下Enter键后触发了focus事件而不是enter事件

---

CHANGELOG.md
package.json

chore(release): 1.6.2

---

src/tabs/__tests__/index.test.jsx
src/tabs/tab-panel-props.ts
src/tabs/tab-panel.tsx
src/tabs/tabs.md
src/tabs/type.ts

re #2666
re #2666 
- feat(tabs): 支持tab-panel内容懒加载

feat(tabs): support tab-panel content lazy load

---

src/input/input.en-US.md
src/input/input.md
src/input/input.tsx
src/input/props.ts
src/input/type.ts
src/textarea/props.ts
src/textarea/textarea.en-US.md
src/textarea/textarea.md
src/textarea/textarea.tsx
src/textarea/type.ts

- feat(input & textarea): 添加maxlength属性String类型

feat(input & textarea): add maxlength string prop type

---

src/form/form.tsx

#2757 
- fix(form): 修复调用`form`组件暴露的`reset`方法后未定义`name`的`form-item`也被一同加入清除

fix(form): fix reset form error

---

src/dialog/_example/async.vue
src/table/hooks/useEditableRow.ts

- fix(Table): 可编辑表格，修复多个可编辑表格同时存在时，校验互相影响问题

fix(table): multiple editable table

---

src/dialog/actions.tsx
src/dialog/dialog.md

- fix(Dialog): 修复没有定义确认按钮属性场景时（即没有设置 confirmBtn），`confirmLoading` 无效问题

fix(dialog): Dialog component support confirmLoading

---

CHANGELOG.md
package.json

chore: release 1.6.7

---

src/table/_example/filter-controlled.vue
src/table/filter-controller.tsx

- feat(Table): 可筛选表格，支持设置 `confirmEvents: ['onChange']` 后，单选筛选器(Radio) 选择完成后自动关闭筛选器浮层

feat(table): radio filter controller improvement

---

src/tree/__tests__/api.test.jsx
src/tree/hooks/useTreeAction.ts
src/tree/tree.tsx

…变更事件，并触发对应 props 的变更
解决问题：tree 组件的 setItem 方法设置 checked, actived, expanded 属性时，未能触发相应变更事件，也未触发 props 对应的值变更。
解决方式：setItem 方法对于这3个属性，变更为调用组件内部的 setChecked 等方法，而不是直接操作 store。
- fix(tree): setItem 方法设置 checked, actived, expanded 属性时，未触发 props 变更与相应事件

fix(tree): setItem 方法设置 checked, actived, expanded 属性时，应当触发 props 变更

---

src/tree/__tests__/api.test.jsx
src/tree/hooks/useTreeStore.ts
src/tree/tree.tsx

https://github.com/Tencent/tdesign-vue/issues/2870
实际测试发现，重构后，composition api 提供的 watch 事件，回调发生事件迟于 nextTick。
导致 data 设置后，在 nextTick 无法取得变更数据。
暂时无法查明回调被推迟的实际原因，先改为直接使用 vue 组件的 watch 方法。
- fix(tree): 解决 watch 回调时间过迟的问题
- test(tree): 补充该问题对应的单元测试

fix(tree): tree 组件，解决 watch 回调时间过迟的问题

---

src/image-viewer/_example/base.vue
src/image-viewer/image-viewer.en-US.md
src/image-viewer/image-viewer.md
src/image-viewer/image-viewer.tsx
src/image-viewer/props.ts
src/image-viewer/type.ts
src/image-viewer/utils.ts

- feat(ImageViewer): 新增支持 `closeOnEscKeydown` ，用于控制是否允许 ESC 键关闭预览

feat(ImageViewer): support closeOnEscKeydown

---

src/select/props.ts
src/select/select.md
src/select/type.ts
src/slider/_example/input-number.vue
src/slider/slider.tsx

- https://github.com/Tencent/tdesign-vue/issues/2880
- https://github.com/Tencent/tdesign-vue/issues/2878
- fix(Slider): 修复 `step` 小于 1 无法正常使用的问题
- fix(Link): 修复样式居中的缺陷

fix(slider): step < 1 is not working

---

src/popup/popup.tsx

https://github.com/Tencent/tdesign-vue/issues/2897
问题背景：
Popup 在 destroyOnClose 的值为 true 的时候，在 pupup 逐渐消失的过程中如果鼠标 hover 上去，popup 将再也不会出现。
解决方案：
如果 destroyOnClose 的值为 true ，那让 popup 在渐变消失的过程中，不再响应鼠标进入事件。
```typescript
onMouseEnter() {
if (this.destroyOnClose && this.isLeaving) {
// 如果 popup 在关闭的时候会被销毁，那在它消失的过程中，不响应鼠标进入事件，因为否则不会触发 mouseleave
return;
}
this.mouseInRange = true;
this.handleOpen({});
},
```
- fix(popup): ignore mouseenter when destroyOnClose is true and is leaving

fix(popup): ignore mouseenter when destroyOnClose is true and is leaving

---

src/checkbox/checkbox.tsx

fix #2908 
- fix(Checkbox): 修复 `CheckboxGroup.max` 超出数量限制时的禁用态显示问题

fix(checkbox): unexpected behavior when disabled is handled

---

src/checkbox/checkbox.tsx
src/checkbox/store.ts
src/hooks/useElementLazyRender.ts

https://codesandbox.io/s/tdesign-vue-demo-forked-42rhg8?file=/src/demo.vue 
- fix(Checkbox): 修复提前设置某个选项的值在选中项 `CheckboxGorup.value` 里面，再放入选项到 `options` 中，选项呈现状态为非选中问题

[Checkbox] fix set value checked before options pushed, while checkbox UI is not checked

---

src/textarea/textarea.tsx

[#2912](https://github.com/Tencent/tdesign-vue/issues/2912)
问题：value的改变往nextTick push了一次autosize计算，然后组件destroy了，之后nextTick执行计算去$refs里拿ref为null，导致了报错
解决方案：
autosize计算方法里判定ref为null直接return
- fix(Textarea): autosize nextTick null err ([#2912](https://github.com/Tencent/tdesign-vue/issues/2912))

fix(Textarea): autosize nextTick null err

---

src/statistic/statistic.tsx

#2931 
未设置 `decimalPlaces` 小数保留位数时，`tween` 更新数值时精度很高导致数字动画变化时很长。
1. 根据用户传入的 `value` 得到默认小数点位数，动画进行时保持这个小数点位数更新。
2. 优化原本代码风格 避免散开。
- CN:  fix(statistic): 修复动画缺失默认位数问题
- US：fix(statistic):  with missing default precision in animation

fix(statistic): fix  with missing default precision in animation

---

src/radio/group.tsx

https://github.com/Tencent/tdesign-vue/issues/2930
1. 要解决的具体问题
radio button组建label变化时，选中的背景色没有同步变化
2. 列出最终的 API 实现和用法
```
const observer = new MutationObserver(this.calcBarStyle);
observer.observe(this.$el, {
childList: true,
attributes: true,
subtree: true,
// 新增参数，监听字符串变化
characterData: true,
});
```
- fix(radio): 选项内容变化后样式问题修复

fix(radio): 选项内容变化后样式问题修复

---

src/auto-complete/_example/filter.vue
src/auto-complete/highlight-option.tsx
src/auto-complete/option-list.tsx

fix(auto-complete): using lodash escapeRegExp transform keyword text

---

src/tree/__tests__/activable.test.jsx
src/tree/__tests__/adapt.js
src/tree/__tests__/checkable.test.jsx
src/tree/__tests__/expand.test.jsx
src/tree/hooks/useTreeAction.ts
src/tree/hooks/useTreeStore.ts

https://github.com/Tencent/tdesign-vue-next/issues/3670
变更了 value, expanded, actived 属性的监听方式
- fix(tree): value, active, expanded 属性, 支持数组操作触发视图变更

fix(tree): tree 组件, value, active, expanded 属性, 支持数组操作触发视图变更

---

src/table/_example/pagination.vue
src/table/hooks/usePagination.tsx

- fix(Table): 分页场景，动态切换分页数据从 undefined 到具体真实数据时，分页无效问题，[#2867](https://github.com/Tencent/tdesign-vue/issues/2867)

fix(table): pagination won't work if switch it to truthy value from undefined

---

src/upload/hooks/useUpload.ts
src/upload/props.ts
src/upload/type.ts
src/upload/upload.en-US.md
src/upload/upload.md
src/upload/upload.tsx

- fix(Upload): 卡片式文件上传，修复取消上传时，文件依然显示问题，[issue#2955](https://github.com/Tencent/tdesign-vue/issues/2955)
- feat(Upload): 新增支持 `uploadPastedFiles`，用于控制是否允许用户粘贴文件上传，默认允许

feat(upload): support uploadPastedFiles

---

src/date-picker/DateRangePicker.tsx

fix https://github.com/Tencent/tdesign-vue-next/issues/3683
- fix(date-range-picker): 修复12月时选择同一个月内的日期后，第一次打开面板左右月份一样的问题

fix(date-range-picker): 修复12月时选择同一个月内的日期后，第一次打开面板左右月份一样的问题

---

src/image-viewer/base/ImageItem.tsx
src/image/props.ts

- https://github.com/Tencent/tdesign-vue/issues/2877
- fix: 修复 SSR 场景报错的问题
- fix(Tree): 解决初始化节点选中态异常的问题 @TabSpace 

chore: fix ssr error

---

CHANGELOG.md
package.json

chore: release 1.8.2

---

src/hooks/useVirtualScrollNew.ts
src/table/filter-controller.tsx
src/table/hooks/useAffix.ts

- fix(Table): 横向滚动场景，修复吸顶表头在移动端无法跟随滚动问题，[#2976](https://github.com/Tencent/tdesign-vue/issues/2976)
- fix(Table): 横向滚动场景，修复横向滚动在有惯性滚动浏览器中的滚动问题
- fix(Table): 横向滚动场景，修复在 Windows 场景中，按下鼠标（不松开鼠标）横向滚动时，表头没有跟随滚动问题
- fix(Table): 可筛选表格，修复筛选值为 `0` 时，筛选图表没有高亮问题，[#2987](https://github.com/Tencent/tdesign-vue/issues/2987)

fix(table): affixed bugs, filter icon highlight bug

---

src/radio/__tests__/vitest-radio.test.jsx
src/radio/radio.tsx

fix #2995 
- fix(Radio): 处理选中状态也会触发 `change` 事件的问题

fix(radio): the checked state also triggers the change event

---

src/textarea/textarea.tsx

- #2809 
需求背景：
使用者提出issue，反馈t-textarea公共组件存在高度计算问题，经定位，该组件已知存在两个问题
1. 没有在任何组件中嵌套的情况：当使用该组件时，如果v-model初始绑定的值是固定值(而不是异步赋的值，比如通过接口请求或者使用宏任务模拟的赋值)，比如v-model绑定的值是value，在data中为value赋了很长的初始值，此时会存在issue中提到的这个问题，但是如果初始值不是固定值是后期通过接口请求或者宏任务模拟赋的值，则不会存在这个问题。
2. 当该组件在部分组件内嵌套使用时，比如t-collapse-panel中，则初始时该组件并没机会通过计算获得高度，而面板再次被展开该组件再次可视后，组件内并没有针对这种场景做高度的重新计算，因此该组件的响应式高度在此场景下失效。
解决方案：
针对问题1：需要确保高度的计算是在DOM挂载完成后进行
针对问题2：仅通过在mounted中和监听value值的变动时做高度响应式计算是不够的，还需要考虑这种初始时该组件处于“隐藏”再次可视的情况。
- fix(Textarea): 修复组件初始处于隐藏状态，可视后未做高度再计算的问题

fix(textarea): 公共组件当初始处于隐藏状态再次可视后未做高度再计算的问题

---

CHANGELOG.md
package.json

chore: release 1.8.4

---

src/form/type.ts

change form methods type-definition to required

feat(form): change form methods type-definition to required

---

src/textarea/textarea.tsx

#3041 
**背景**：用户提出issue,反馈设置maxlength后，windows自带输入法，当输入中文时所输入字符还没有达到最大长度也会没法输入。
**问题描述**：textarea公共组件做输入字符限制时，每次 input 事件触发时剪切输入值以符合最大长度。这种剪切假设了所有字符将键入的同时变成结果字符，也就是说，如果用户正在输入一个长拼音字符序列（比如汉字的拼音），但还没有选择对应的汉字结果，输入就会被提前剪切，因为拼音可能会超过最大长度。
**解决方案**：用户在构词状态时不应该设置输入限制和字符剪切，而是等完成后。
- fix(Textarea): 修复设置`maxlength`后，在windows自带输入法中，中文时不到最大长度也会自动覆盖之前已输入内容的缺陷

Fix the bug of textarea with maxlength can't input before limit

---

src/select/select.tsx

- fix(Select): 修复点击清除按钮触发多次`onChange`事件的异常

fix(Select): fix clear trigger onchange callback twice

---

src/textarea/textarea.tsx

#3049 
因为中文输入中时，拼音不会触发change时间，当textareaStyle改变，textarea渲染时value值并没有改变，导致不能输入中文。
参考vue-next中textarea的做法，使用setStyle方法来控制textareaStyle
- fix(textarea): value绑定值时，autosize时无法输入中文问题

fix(textarea): value绑定值时，autosize时无法输入中文问题

---

CHANGELOG.md
package.json

chore: release 1.9.0

---

src/table/_example-composition/filter-controlled.vue
src/table/_example/filter-controlled.vue
src/table/base-table-props.ts
src/table/filter-controller.tsx
src/table/hooks/useClassName.ts
src/table/hooks/useFixed.ts
src/table/hooks/useTreeDataExpand.ts
src/table/primary-table-props.ts
src/table/table.en-US.md
src/table/table.md
src/table/type.ts

- feat(Table): 可筛选表格，单选/多选筛选条件 支持搜索选项，[issue#3988](https://github.com/Tencent/tdesign-vue-next/issues/3988)
- fix(Table): 树形结构表格，修复同时异步设置 data 和 expandedTreeNodes 时，展开节点无效问题（延迟设置有效），[tdesign-vue-next#3873](https://github.com/Tencent/tdesign-vue-next/issues/3873)
- fix(Table): 固定列表格，修复固定多列时，在 Dialog 中固定列位置压缩问题

[Table] support table filter input; fix fixed columns in dialog problem

---

helper/attributes.json
helper/tags.json
helper/web-types.json

- https://github.com/Tencent/tdesign-vue/issues/3099
- 相关PR https://github.com/Tencent/tdesign-common/pull/1745
- fix: 修复编辑器对`t-descriptions-item`组件的提示缺失问题
- fix(Descriptions): 优化自适应宽度的问题

fix(Descriptions): fix descriptions item prompt

---

src/date-picker/DatePicker.tsx

- https://github.com/Tencent/tdesign-vue/issues/3068
- formatDate 方法需要Date对象来计算，部分场景下，value.value为普通字符串或时间戳，无法得出正确的结果，需统一转为Date再进行计算
- 相关PR https://github.com/Tencent/tdesign-common/pull/1746
- fix(DatePicker): 修复 `format` 与 `valueType` 不一致的场景下计算错误的问题

fix(Datepicker): value display wrong with special format

---

CHANGELOG.md
package.json
src/date-picker/DatePicker.tsx

chore: release 1.9.1

---

src/date-picker/DatePicker.tsx

- fix(DatePicker): 修复`valueType` 为 `Date ` 类型时仍然进行转换的缺陷

fix(date-picker): over parse when valueType is Date

---

package.json

chore: release 1.9.2

---

CHANGELOG.md
site/docs/getting-started.en-US.md
site/docs/getting-started.md

docs: optimize docs and CDN usage 

---

src/textarea/calcTextareaHeight.ts

解决与此 [pr](https://github.com/Tencent/tdesign-vue-next/pull/4104) 相同的问题。
- fix(Textarea): `autosize` 在 `Firefox` 中不生效。

fix(textarea): `autosize` doesn't work in Firefox

---

src/select/option-props.ts
src/select/type.ts

- https://github.com/Tencent/tdesign-vue/issues/3146
- fix(Select): 修复 `option` 插槽 value 为 `Boolean` 类型的报错问题

fix(Select): option slot bool error

---

CHANGELOG.md
package.json

chore: release 1.9.3

---

src/select-input/useMultiple.tsx

fix(select-input): allowInput is true and cannot be entered in multiple selection cases
#2336 
* fix(select-input): 修复多选情况下设置allowInput为true无法输入的问题

fix(select-input): allowInput is true and cannot be entered in multiple selection cases

---

src/date-picker/DateRangePicker.tsx
src/date-picker/DateRangePickerPanel.tsx
src/date-picker/utils.ts

优化前，选择后左侧区间大于右侧区间只会同步右侧区间
优化后，选择后左侧区间大于右侧区间，默认调整为左侧区间始终比右侧区间小1，增加可操作范围
切换年且只有年选择器：
1. 点击左侧，且左侧大于右侧，右侧要自动加1；
2. 点击右侧，且右侧小于左侧，左侧要自动减1；
切换年且要有月份选择器：
1. 点击左侧，且左侧大于右侧，右侧要自动切换至左侧年+月份 加1；
1. 点击右侧，且右侧小于左侧，左侧要自动切换至右侧年+月份 减1；
切换月份选择器：
1. 点击左侧，且左侧大于右侧，右侧要自动切换至左侧年+月份 加1；
1. 点击右侧，且右侧小于左侧，左侧要自动切换至右侧年+月份 减1；
- feat(DatePicker): 优化日期区间选择器头部区间的变化逻辑，选择后左侧区间大于右侧区间，则默认调整为左侧区间始终比右侧区间小 1

feat(DatePicker): optimize range picker panel header click logic

---

CHANGELOG.md
package.json

chore: release 1.9.5

---

CHANGELOG.md
package.json
src/tree/hooks/useDragHandle.ts

chore: release 1.9.6-naruto

---

src/tree/__tests__/index.test.jsx
src/tree/_example/filter.vue
src/tree/hooks/useTreeNodes.tsx

- https://github.com/Tencent/tdesign-vue/issues/3227
- fix(Tree): 修复树形组件错误过滤 `value` 为 `0` 的节点的问题

fix(Tree): fix nil value filter bug

---

CHANGELOG.md
package.json

chore: release 1.9.8

---

src/upload/themes/multiple-flow-list.tsx
src/upload/upload.tsx

- fix(Upload): 修复部分图标不支持全局替换的问题

fix(Upload): fix global icon replacement

---

src/common.ts
src/descriptions/descriptions-body.tsx
src/descriptions/descriptions.tsx

- https://github.com/Tencent/tdesign-vue-next/pull/3939
- feat(Description): layout 类型定义调整为字符串多类型

feat(descriptions): make layout type to be multiple type

---

src/cascader/core/effect.ts

- https://github.com/Tencent/tdesign-vue-next/issues/4457
- 相关PR 
- https://github.com/Tencent/tdesign-common/pull/1880
- https://github.com/Tencent/tdesign-common/pull/1879
- fix(Table): 修复拖拽排序时，祖先节点内的顺序错误的问题
- fix(InputNumber): 修复小数点精度计算，以0开头的计算边界逻辑缺失导致计算错误的问题
- fix(Cascader): 修复多选下点击清空按钮的功能异常及多次触发 `onChange` 事件的问题

chore: update common

---

CHANGELOG.md
package.json

chore: release 1.9.9

---

src/select/select.tsx
src/select/util.ts

>> - 修复了 flattenOptions 函数未正确扁平化分组，导致在分组间切换时上下键无法正确切换的问题。
>> - 修复了上下键切换时，激活项未能滚动到下拉面板视口内的问题。
issue链接 ：https://github.com/Tencent/tdesign-vue/issues/3272
需求背景： 展开下拉框后，用键盘的方向键向下选取，当选项数量多超出下拉面板有滚动条时，继续用方向键向下，下拉面板内容不会跟着滚动。
解决方案：在监听上下键事件的地方，加上滚动方法 setHoverIntoView，使键盘选取项滚动到下拉面板视口
- fix(Select): 修复分组状态下，通过上下键切换时下拉面板不会跟随滚动的问题
- fix(Select): 修复分组状态下，通过上下键切换时无法正确切换的问题

fix(select): 修复 flattenOptions 方法分组扁平化问题及上下键切换功能

---

src/color-picker/panel/format/index.tsx

https://github.com/Tencent/tdesign-vue/issues/3271
- 修复ColorPicker透传SelectInputProps无效问题
- fix(color-picker):修复ColorPicker透传SelectInputProps无效问题

fix(ColorPicker):  selectInputProps API can't work 

---

src/time-picker/__tests__/index.test.jsx
src/time-picker/panel/single-panel.tsx

目前time-picker  format仅支持 HH:mm:ss 这种格式化的使用，当 format 设置了 HH时mm分ss秒 这种格式时，选择器仅允许选择小时。
- fix(TimePicker):  修复format 仅支持 HH:mm:ss 格式的问题;

fix(TimePicker): fixed only support hh:mm format

---

CHANGELOG.md
package.json

chore: release 1.10.0

---

src/button/button.en-US.md
src/button/button.md
src/button/props.ts
src/button/type.ts
src/form/form.en-US.md
src/form/form.md
src/form/props.ts
src/form/type.ts

- https://github.com/Tencent/tdesign-vue-next/issues/4448
- feat(Form): 新增`id` API，表单原生的 id 属性，支持用于配合非表单内的按钮通过 form 属性来触发表单事件
- feat(Button): 新增`form` API，原生的 form 属性，支持用于通过 form 属性触发对应 id 的 form 的表单事件

feat(form): support form id and button form API

---

src/icon/icon.en-US.md
src/icon/icon.md

docs(icon): fix installation instructions

---

src/cascader/cascader.tsx
src/popup/popup.tsx

- feat(Cascader): 支持打开菜单时滚动到首个已选项所在节点

feat(cascader): support scroll to first selected node

---

CHANGELOG.md
package.json
src/cascader/core/effect.ts

chore: release 1.10.1

---

src/tree/__tests__/expand.test.jsx
src/tree/hooks/useTreeAction.ts

https://github.com/Tencent/tdesign-vue-next/issues/4571
- fix(tree): custom icons cannot be clicked without child nodes

fix(tree): custom icons cannot be clicked without child nodes

---

src/drawer/drawer.tsx

- https://github.com/Tencent/tdesign-vue/issues/3360
- https://github.com/Tencent/tdesign-vue/issues/3356
此前计算滚动条的方式是基于浏览器默认宽度，定制滚动条的场景会失效，修改计算滚动条的方式，相关PR如下
- https://github.com/Tencent/tdesign-common/pull/1968
Drawer中对是否存在滚动条的判断存在问题，调整判断方式，配合common调整，使 Drawer 开启正确计算scrollbar宽度
- fix(Drawer): 修复打开 `drawer` 时页面抖动的问题
- fix(Dialog): 修复打开 `dialog` 时页面抖动的问题 @RSS1102 

fix: fix shaking when dialog and drawer show

---

src/time-picker/_usage/time-range-picker-props.json
src/time-picker/time-picker.en-US.md
src/time-picker/time-picker.md
src/time-picker/time-range-picker-props.ts
src/time-picker/time-range-picker.tsx
src/time-picker/type.ts

- feat(TimePicker): 新增 `autoSwap` API，支持`1.10.2` 版本之后仍支持保持选定的左右侧时间大小顺序

feat(TimePicker): support autoswap API

---

src/date-picker/DateRangePickerPanel.tsx

- #3368
- fix(DatePicker): `DateRangePickerPanel`组件`mode`为`week`时无法通过左右箭头调整月份

fix(DatePicker): panel top arrow doesn't work when using week mode

---

src/table/thead.tsx

1. 多级表头下的表头通过colspan进行合并
2. 在thead.tsx下的colspanSkipMap函数下，增加children的处理逻辑
- fix(Table): 多级表头下的通过colspan合并表头

fix(table): resolve colspan handling for multi-header

---

src/tag-input/__tests__/vitest-tag-input.test.jsx
src/tag-input/useTagList.tsx

- fix(tag-input):修复在`readonly`模式下仍可以通过Backspace按键删除已选项的缺陷

fix(tag-input): prevent backspace event in readonly mode and add test

---

src/color-picker/panel/index.tsx
src/color-picker/panel/swatches.tsx

[#3383](https://github.com/Tencent/tdesign-vue/issues/3383)
最近颜色的删除功能：删除后需要重新选择一个最近颜色才能继续删除
- fix(color-picker): 最近使用颜色需要选中才能删除

fix(color-picker): recentColors delete

---

src/cascader/core/effect.ts

- feat(Cascader): 单选模式下当`trigger`为`hover`时，选中选项后自动关闭面板

feat(cascader): click item to  close panel when trigger is hover

---

src/dialog/dialog.en-US.md
src/dialog/dialog.md
src/dialog/dialog.tsx
src/dialog/props.ts
src/dialog/type.ts
src/drawer/drawer.en-US.md
src/drawer/drawer.md
src/drawer/drawer.tsx
src/drawer/props.ts
src/drawer/type.ts

- https://github.com/Tencent/tdesign-vue-next/issues/4709
- https://github.com/Tencent/tdesign-vue-next/pull/4733
- feat(Dialog): 新增 `beforeOpen` 和 `beforeClose` API
- feat(Drawer): 新增 `beforeOpen` 和 `beforeClose` API

feat(Dialog&Drawer): support `beforeOpen` And `beforeClose` API

---

src/transfer/components/transfer-list.tsx

[#3268 ](https://github.com/Tencent/tdesign-vue/issues/3268)
transfer-list组件内会接收page得参数pageSizeOptions，但由于使用??语法得问题(只有null以及undefined时才会继续往右取值)，this.defaultPageSize又设置为0，所以computed的pageSize一直为0，所以把defaultPageSize初始值设置为null就正常了。defaultCurrent也是同理，会导致外部传进来的pagination.defaultCurrent一直无法生效，所以一并改正。
- fix(Transfer): 修复设置pageSizeOptions时切换pageSize无法生效得问题

fix(Transfer): 修复设置pageSizeOptions时切换pageSize无法生效得问题

---

src/input-number/useInputNumber.tsx

#3397 
- fix(InputNumber): 限制输入超过范围外的数字未触发 `blur` 事件

fix(input-number): limiting the input of numbers exceeding the range does not trigger the blur event

---

src/select/hooks/useSelectOptions.ts
src/select/select.tsx
src/select/util.ts

[#3405](https://github.com/Tencent/tdesign-vue/issues/3405)
增加option cache，避免搜索过滤时optionsList为空导致选中选项显示异常；修改基本参照vue-next端处理。
- fix(Select): 修复搜索过滤选项列表时选中值显示错误问题

fix(Select): 增加option cache，避免搜索过滤时optionsList为空导致选中选项显示异常

---

src/cascader/hooks.ts

#3430
- fix(Cascader): 当 `valueType` 为 `full` 时会意外触发 `change` 事件

fix(cascader): change event is triggered unexpectedly when value-type is full

---

.github/workflows/pr-comment-ci.yml

fix(PR_COMMENT_CI): resolve snap conflicts

---

src/select/select.tsx

befor: 
在 `multiple`、`filterable` 和 `reserveKeyword` 的状态下，筛选数据之后，进行全选会选中 当前 filter 之后的数据，但是不能再次点击 **全选** 进行取消选择(全选)。
now:
在 `multiple`、`filterable` 和 `reserveKeyword` 的状态下，筛选数据之后，进行全选会选中 当前 filter 之后的数据，但是再次点击 **全选** 进行取消选择(全选)。
---
将部分在点击全选的方法进行抽离到公共函数内调用，保持代码简洁和复用。
> [!TIP]
> 目前看起来似乎不是一个 breaking change，不会对之前的逻辑产生影响，更像一个错误的修复。
- fix(select): 在保留关键字的情况下使用筛选，全选会对于筛选后的`options` 进行操作和比较。

fix(select): `checkAll` will check all filtered data of `reserveKeyword`

---

src/select/hooks/useSelectOptions.ts
src/select/option-group-props.ts
src/select/optionGroup.tsx
src/select/select-panel.tsx

当在分组的情况下，
如不想显示分组的标题只想显示分割线，则可以通过只传入 `divider: true,` 而不传 `group：“xx” 字段即可实现`。
- perf(select): 可以使在 `group` 标题不存在的时候仍能正确渲染

perf(select): `group` title  not exist still renders children

---

CHANGELOG.md
package.json

chore: release 1.10.8

---

src/auto-complete/_example/base.vue
src/auto-complete/auto-complete.tsx
src/auto-complete/option-list.tsx

options = [], 点击 没展示 empty 节点
修改后
- fix(AutoComplete): 修复 `options` 为空数组，empty 节点没显示

fix(auto-complete): options is an empty array, empty is not effective

---

src/form/form-item.tsx
src/form/form.en-US.md
src/form/form.md
src/form/type.ts

SYNC: https://github.com/Tencent/tdesign-vue-next/pull/5008
1. 当前没有实现的 `status` 和 `tips` 功能
2.  移除 `status`  中的 `'validating'` 属性
- feat(form): `form-item` 新增 `status` 和 `tips` API

feat(form): add `status` and `tips` rendering in `form-item` component

---

src/config-provider/config-receiver.ts
src/config-provider/type.ts
src/dialog/dialog.tsx
test/snap/__snapshots__/csr.test.js.snap

chore(config-provider): improve globalAttach method to handle string and object types
当前：当 `<t-dialog header="Title" body="Would you like to be my friends？" mode="normal" theme="default" visible />` 时，会将 dialog 会挂载在`body` 下。
预期：应该默认跟随之前的文档结构不变。
- fix(dialog): 修复当 mode 为 "normal" 时不正确的节点附件

fix(dialog): incorrect node attachment when `mode = "normal"`

---

CHANGELOG.md
package.json

chore: release 1.11.0

---

src/upload/hooks/useUpload.ts
src/upload/upload.tsx

close #3524 close #3523
- fix(upload): 为上传组件增加表单禁用状态支持

fix(upload): integrate form disabled state into upload component

---

src/message/messageList.tsx
src/message/plugin.tsx

#3488 
在多次调用messagePlugin方法的场景下，它返回的promise中的实例总是指向最后一次调用的实例。
修复方式：
1. 在message被添加的时候，生成一个随机的key
2. 在plugin resolve的时候，根据生成的key获取对应的实例
- fix: 修复连续调用messagePlugin时，返回的实例不正确的问题

fix: fix messagePlugin instance error

---

src/dialog/actions.tsx

resolve  https://github.com/Tencent/tdesign-vue-next/issues/5158
- fix(Dialog):  自定义 `cancelBtn` 文本时保留 `t-dialog__cancel` 样式

fix(Dialog):  custom `cancelBtn` text retains `t-dialog__cancel` className

---

src/form/_usage/props.json
src/form/form-item.tsx
src/form/form.en-US.md
src/form/form.md
src/form/props.ts
src/form/type.ts

VueNext栈的同步修改
- https://github.com/Tencent/tdesign-vue-next/pull/5223
- feat(Form): 新增`requiredMarkPosition`，用于支持定义必填符号的位置

feat(Form): support right required mark

---

src/transfer/utils.ts

当前如果节点内 包含有 `children:[]` 时，这个节点都不会被渲染。
- fix(transfer): 确保空 children 数组的节点能正确渲染

fix(transfer): ensure nodes with empty children arrays render correctly

---

src/select/hooks/useSelectOptions.ts

https://github.com/Tencent/tdesign-vue-next/issues/5088
1. 需要解决的问题
在Select 组件中使用 keys 属性时，如果使用了content 作为自定义字段名，会和内置 content 属性冲突，导致失效
2. 解决办法
在解析 options 配置并且初始化innerOptions 的时候，去除掉自定义 keys 相关属性的透传
- fix(Select): keys 属性配置 content 作为 value 时不生效问题

fix(select): fix select keys props has content not work 

---

src/select/select.tsx

[#3576](https://github.com/Tencent/tdesign-vue/issues/3576)
修复valueType:object与keys同时设置时的绑定值错误
- fix(Select): 修复valueType:object与keys同时设置时的绑定值错误

fix(Select): 修复valueType:object与keys同时设置时的绑定值错误

---

src/tag/__tests__/vitest-tag.test.jsx
src/tag/tag.tsx

from https://github.com/Tencent/tdesign-vue-next/issues/5411
- fix(Tag): 未设置 `max-width` 导致无法渲染 `title` 属性的问题

fix(tag): allow title rendering without max-width restriction

---

README-zh_CN.md
README.md

Hi Tencent/tdesign Community
tdesign-vue is a vibrant open-source community where its products and frameworks are loved by lots of users and developers. As people use it, they contribute by raising issues, engaging in discussions, or directly contributing code, all of which help in continuously improving tdesign-vue.
However, GitHub's default contributor list simply enumerates users who have committed code, failing to proportionately reflect the broader range of community contributors.
Therefore, we have designed a new chart that showcases active contributors from three perspectives: issues, PRs, and discussions. This is similar to embedding star-history within the README:
By clicking on the link, you can view the specific contributions made by each individual: …

docs: A new contributor graph that evaluates community activities from all dimensions

---

src/drawer/drawer.en-US.md
src/drawer/drawer.md
src/drawer/props.ts
src/drawer/type.ts

Sync https://github.com/Tencent/tdesign-vue-next/pull/5555
- fix(drawer):  修复 `cancel-btn` 和 `confirm-btn` 的类型缺失`null` 声明的问题

fix(drawer): `cancel-btn` and `confirm-btn` type supports `null`

---

src/image-viewer/base/ImageViewerUtils.tsx
src/image-viewer/image-viewer.tsx

- Container 仍然是options API 的写法导致context失效，考虑到Vue 2 接下来以维护已有功能为主，修改为props传递最小化修改修复问题
- fix(ImageViewer): 修复图片预览操作栏多语言失效的问题

fix(image-viewer): fix i18n text

---

src/radio/group.tsx

- https://github.com/Tencent/tdesign-vue/issues/3632
- ColorPicker 引用了这个组件...也产生了相同问题
- 内置的 `useResizeObserver` 期望接收一个响应式的 Ref<HTMLElement>，内部使用 `watch(container, ...)` 来监听容器变化，这对于 Vue 2.7 (支持 `@vue/composition-api`) 是生效的，但低版本的 Vue 中创建的对象是非响应式的，实际传入的是一个普通的 DOM 元素...之前直接迁移导致了问题
- 顺便把以前操控键盘事件中的 `$el` 统一改用 `$refs`
- fix(RadioGroup): 修复 `naruto` 版本的 ResizeObserve 兼容性

fix(radio-group): improve resize observer handling

---

.vscode/settings.json
src/alert/__tests__/index.test.jsx
src/alert/alert.en-US.md
src/alert/alert.md
src/alert/alert.tsx
src/alert/props.ts
src/alert/type.ts

closes #3630
https://github.com/Tencent/tdesign-vue/issues/3630
增加closeBtn，先保留close，逐渐过渡。
- fix(alert): close属性同步为closeBtn，close即将废弃

fix(alert): close属性同步为closeBtn，close即将废弃

---

src/table/__tests__/pagination/onpage-scroll.test.jsx
src/table/base-table.tsx
src/table/hooks/usePagination.tsx

- feat(table): 新增切换分页后重置滚动条回到顶部的特性

feat(table): initialize the scroll bar when switching pages

---

src/textarea/props.ts
src/textarea/textarea.en-US.md
src/textarea/textarea.md
src/textarea/textarea.tsx
src/textarea/type.ts

- feat(Textarea): 添加 API `allowInputOverMax` 允许输入超过 `maxlength`

feat(Textarea): add `allowInputOverMax` to allow exceeding `maxlength`

---

helper/attributes.json
helper/web-types.json
src/table/primary-table-props.ts
src/table/table.md
src/table/type.ts

- https://github.com/TDesignOteam/tdesign-api/pull/711

docs(Table): fix `asyncLoading` state description

---

src/select/hooks/useSelectOptions.ts
src/select/select-panel.tsx
src/select/select.tsx

- https://github.com/Tencent/tdesign-vue/issues/3707
- https://github.com/Tencent/tdesign-vue/pull/3540 优化使用content做keys的问题引入的缺陷，同步 Vue3 的处理方式
- fix(Select): 修复设置 `keys` 后， onChange 回调参数中 selectedOptions 参数缺失的问题

fix(Select): return complete option when keys is set

---

CHANGELOG.md
package.json
src/tabs/_usage/index.vue

chore: release 1.14.0

---

src/watermark/_example/layout.vue
src/watermark/props.ts
src/watermark/type.ts
src/watermark/watermark.en-US.md
src/watermark/watermark.md
src/watermark/watermark.tsx
test/snap/__snapshots__/csr.test.js.snap
test/snap/__snapshots__/ssr.test.js.snap

- feat(Watermark): 新增 `layout` API，支持生成不同布局的水印
- fix(Watermark): 修复多行图文水印图片配置了灰度时，整个画布内容也会灰度的问题

feat(Watermark): support layout API
